### ISSUE TITLE
Webmaker App for Android no longer available

### ISSUE THREAD

**Issue by madb1lly** [mozilla/webmaker-core#1018]
Hi all,
The Webmaker app for Android isn't on the Play store anymore. Is this intentional? Is the project defunct? If it is, why is the website www.webmaker.org still up with a link to the Play store?
Cheers,

**Comment by KevZawacki** [comment]
Hi @madb1lly  

Mozilla is no longer supporting Webmaker for Android; we're currently devoting our resources to our [advocacy](https://foundation.mozilla.org/campaigns/facebook/), [leadership](https://foundation.mozilla.org/fellowships/), and [Internet Health Report](https://internethealthreport.org/2018/) work. 

Mozilla is in the process of updating older properties. Thanks for writing — and let me know if I can answer further questions.

**Comment by madb1lly** [comment]
So you mean Mozilla isn't going to do or support any technical initiatives anymore? That doesn't sound very promising.

**Comment by KevZawacki** [comment]
Hi @madb1lly,

To clarify: The specific teams at the Mozilla Foundation that supported Webmaker are now working on our advocacy, leadership, and Internet Health Report work.

You can find a list of projects that Mozilla is supporting -- many of them technical -- here: https://www.mozillapulse.org/featured

**Comment by madb1lly** [comment]
Hi @KevZawacki 
Thanks for the reply and link to Pulse. It's good to know that Mozilla is keeping the technical projects going. It's a shame that Webmaker couldn't be kept going, these education tools are one of the best things to come from Mozilla. I hope that Thimble, Xray goggles and other education tools will be kept alive?
Cheers :)
