### ISSUE TITLE
Pull to refresh UX issues

### ISSUE THREAD

**Issue by toolness** [mozilla/webmaker-core#126]
This issue has been migrated from mozilla/webmaker-android#1927.

It was originally written by [flukeout](https://api.github.com/users/flukeout) on Wed May 20 2015 and had the following description:

> **Some notes on the pull-to-refresh feature on the Discover & Make page**
> - Don't hide the list of projects while the view is checking for and loading new projects
> - Don't hide the spinner until the view has finished loading

**Comment by xmatthewx** [comment]
tracking in #841
