### ISSUE TITLE
Limit Pull-to-refresh action to the Discover & Make View

### ISSUE THREAD

**Issue by toolness** [mozilla/webmaker-core#130]
This issue has been migrated from mozilla/webmaker-android#1941.

It was originally written by [flukeout](https://api.github.com/users/flukeout) on Wed May 20 2015 and had the following description:

> Currently, I'm able to initiate the pull to refresh action in the Make, Page Editor and Edit Element views. It's only necessary on the Discover view.

On Wed May 20 2015, [thisandagain](https://api.github.com/users/thisandagain) commented:

> Good catch!

On Wed May 20 2015, [k88hudson](https://api.github.com/users/k88hudson) commented:

> **@****thisandagain** **@****flukeout** do we want to maybe remove this for all views? Seems to be a new feature in Chrome that refreshes the page.
> 
> If you're OK with default browser behaviour (i.e. white screen before things load) we'll leave it in, but what are your thoughts?

On Wed May 20 2015, [flukeout](https://api.github.com/users/flukeout) commented:

> **@****k88hudson** I changed the issue to reflect this - we should only have this available in the Discover view.

**Comment by xmatthewx** [comment]
tracking #841
