### ISSUE TITLE
Specify UX for changing the z-index of elements

### ISSUE THREAD

**Issue by toolness** [mozilla/webmaker-core#136]
This issue has been migrated from mozilla/webmaker-android#1961.

It was originally written by [flukeout](https://api.github.com/users/flukeout) on Wed May 20 2015 and had the following description:

> We used to have a ticket, or at least the interaction was described somewhere. I can't find it so we'll do it again. Our previous assumption was that you would tap an already selected element to raise it to the top of the z-index pile among the other elements on the page.

On Fri May 22 2015, [vazquez](https://api.github.com/users/vazquez) commented:

> I also like the icon for bring button to front.
> 
> For icons, these are some benchmarks to visually connotate z-index:  
> 
> ![screenshot 2015-05-22 13 50 12](https://cloud.githubusercontent.com/assets/1119821/7776543/b2e14f24-0089-11e5-9e3e-eabb098d2d13.png)
> 
> ![screenshot 2015-05-22 13 52 54](https://cloud.githubusercontent.com/assets/1119821/7776589/e4b50ec8-0089-11e5-8899-88e976d6b44a.png)
> 
> ![screenshot 2015-05-22 13 53 53](https://cloud.githubusercontent.com/assets/1119821/7776598/013db0c2-008a-11e5-924a-31f50ecee18d.png)

On Fri May 22 2015, [flukeout](https://api.github.com/users/flukeout) commented:

> **@****vazquez** Thanks! Let's work on the treatment in the next phase. 
> 
> Here's an **[Updated Z-index Diagram](https://dl.dropboxusercontent.com/u/109902/tiles/z-index.pdf)** with the option we liked.
> 
> I've also added an idea for selecting overlapped elements at the bottom of the diagram.

On Fri May 22 2015, [vazquez](https://api.github.com/users/vazquez) commented:

> Solid diagram Luke :rocket:. I think we should run with this. I think the radical approach might be a bit too radical (I find it confusing to use 2 icons), but let's have it on the table! :)

On Tue May 26 2015, [flukeout](https://api.github.com/users/flukeout) commented:

> For the **Radical Mode** let's make it so that the overlapping toucan has a "down" arrow instead of hte invisible eyeball thingy on the button. I'll update the diagram.

On Wed May 27 2015, [xmatthewx](https://api.github.com/users/xmatthewx) commented:

> This could be a good candidate for an in-app prototype.

**Comment by flukeout** [comment]
Closing this - as we'll be implementing the spec in #170
