### ISSUE TITLE
Complete L10N

### ISSUE THREAD

**Issue by toolness** [mozilla/webmaker-core#148]
This issue has been migrated from mozilla/webmaker-android#2002.

It was originally written by [secretrobotron](https://api.github.com/users/secretrobotron) on Tue May 26 2015 and had the following description:

> See https://github.com/mozilla/webmaker-android/issues/1599#issuecomment-103712914 for recommendations
> - [x] Clean-up `strings.xml` resource - Andrew
> - [x] Provide JS API to Android string resource - Andrew
> - [x] Add filters to static files - K88
> - [x] Add filters to functional code (where necessary) - K88
> - [x] Upload json files to Transifex - Bobby
> - [x] Shout-out on Transifex - Bobby
> - [x] Alert launch teams
> - [x] Create QA checklist (#2061)
> 
> Resources:
> - webmaker-mailroom: https://www.transifex.com/projects/p/webmaker/resource/user_createdjson/
> - webmaker-android: https://www.transifex.com/projects/p/webmaker/resource/webmaker-stringsxml/
> - webmaker landing page
> - play store?

On Wed Jun 03 2015, [k88hudson](https://api.github.com/users/k88hudson) commented:

> **@****secretrobotron** is there any action required from me during this heartbeat?

On Wed Jun 03 2015, [thisandagain](https://api.github.com/users/thisandagain) commented:

> Assigning to self so I can get the first two items done.

On Wed Jun 03 2015, [secretrobotron](https://api.github.com/users/secretrobotron) commented:

> :+1: **@****k88hudson** and I just spoke about that. If needed, when it's done someone (e.g. me) can hop in and replace strings with appropriate API.

On Sat Jun 06 2015, [LauraReynal](https://api.github.com/users/LauraReynal) commented:

> We have a team ready in Bangladesh, and we would like to know:
> - How many string will be in the app for localization? 
> - Is it possilbe to put the strings in the Pontoon localization tool ? 
> 
> cc / team members : **@****bellayet** **@****tapuafrad** 
> Tracking in lauch repo here https://github.com/mozilla/webmaker-launch/issues/19

On Mon Jun 15 2015, [LauraReynal](https://api.github.com/users/LauraReynal) commented:

> some things might be of interest here https://github.com/mozilla/webmaker-launch/issues/28

On Thu Jun 18 2015, [k88hudson](https://api.github.com/users/k88hudson) commented:

> **@****secretrobotron** ok, i probably missed a few but most of them are in here:
> https://github.com/k88hudson/webmaker-android/blob/intl/app/src/main/res/values/strings.xml
> 
> That work for you?

On Fri Jun 19 2015, [secretrobotron](https://api.github.com/users/secretrobotron) commented:

> **@****k88hudson** yay! The comments you left `<!-- Make -->` are good indicators for localizers. Can we work on a [QA checklist ](https://github.com/mozilla/webmaker-android/issues/2061) now?

On Fri Jun 19 2015, [k88hudson](https://api.github.com/users/k88hudson) commented:

> **@****secretrobotron** yep, will do

On Fri Jun 19 2015, [secretrobotron](https://api.github.com/users/secretrobotron) commented:

> **@****k88hudson** are you landing that today, btw?

On Fri Jun 19 2015, [k88hudson](https://api.github.com/users/k88hudson) commented:

> **@****secretrobotron** no, I want to wait until after launch

**Comment by secretrobotron** [comment]
@alicoding: @k88hudson says we need to add the locale to the request that gets sent to the server here: https://github.com/mozilla/webmaker-core/blob/develop/src/pages/login/sign-up.jsx#L96

**Comment by secretrobotron** [comment]
From the wisdom of @alicoding:

webmaker.org (including login.webmaker.org/accounts and probably everything else that uses webmaker-i18n probably) only supports `in`, not `in-ID`, which is what our app attempts to pass on to id.webmaker.org.

Solution: use [locale mapping](https://github.com/mozilla/webmaker.org/blob/master/app.js#L130). Simply add `mappings` to the middleware options, map the language we don’t support to language we support e.g.

```
{
  `in-ID`: `in`
}
```

(more examples: https://github.com/mozilla/webmaker-locales-mapping-configuration/blob/master/index.js#L8-L9)

**Comment by secretrobotron** [comment]
@cadecairos can you identify which systems are going to need this change?
@alicoding can you verify that `in-ID` is the only language we need to map (at least for launch)?

**Comment by alicoding** [comment]
So I was wrong about the locale code and the correct one suppose to be `id-IN` and not `in-ID`. Right now I'm debugging something here to get this problem sorted out.
