### ISSUE TITLE
The app cannot be used without network connectivity, due to how api.js works

### ISSUE THREAD

**Issue by toolness** [mozilla/webmaker-core#149]
This issue has been migrated from mozilla/webmaker-android#2005.

It was originally written by [Pomax](https://api.github.com/users/Pomax) on Tue May 26 2015 and had the following description:

> We've tied a lot of calls to network connectivity by hook up the api.js function to first communicate the changes to the API server, and then allow them back through to the local client, instead of doing things the other way around. This might be easy to fix by being more permissive in terms of what to do on an error (still send the modification on as a success, for instance) but that feels like it'll leave us with a questionable design in terms of code flow. Ideally, ops should happen, and only then sent on to the API for syncing, caring about whether they sync only for the purposes of known whether we're in synced or desynced state.

On Wed Jun 03 2015, [thisandagain](https://api.github.com/users/thisandagain) commented:

> Need to split this into three:
> - Network loading state design / display (already tracking in other tickets)
> - Offline consumption (GET)
> - Offline creation / production (POST, PUT, DEL)

**Comment by Pomax** [comment]
this can be closed due to all the followup
