### ISSUE TITLE
QA/Testing scripts

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker-core#16]
Prior work by @k88hudson here: https://gist.github.com/k88hudson/16e0b6a720f33e1f7c3e
Some more brainstorming here: https://etherpad.mozilla.org/webmaker-qa-stuff-vectors
- How do we split this up into small, repeatable tasks that people can jump in and test?
- Does it cover localization, QA, and user-testing?

cc @flukeout

**Comment by secretrobotron** [comment]
QA Checklist for Localization: https://github.com/mozilla/webmaker-android/issues/2061

**Comment by xmatthewx** [comment]
## Support matrix
- [ ] Android Browser `p1`
  - [ ] Chrome (latest)
  - [ ] Firefox (latest)
  - [ ] Android browser (4.4+)
- [ ] iOS Browser `p1`
  - [ ] Chrome (latest)
  - [ ] Safari (latest)
- [ ] Desktop `p2`
  - [ ] Chrome (latest - 1)
  - [ ] Firefox (latest - 1)
  - [ ] Safari (latest - 1)

## Test
- Browser
  - What's your browser? OS? Device?
- Page
  - [ ] page is visible and centered
  - [ ] page elements appear with layout as expected 
- Page navigation
  - [ ] neighboring pages are visible with minimal opacity
  - [ ] navigation arrows are positioned correctly and point toward neighboring pages
  - [ ] tap an arrow to navigate to a neighboring page
  - [ ] view transitions smoothly with correct page, neighbors, and arrows
- Button links
  - [ ] find a page with button. tap it to navigate to another page
  - [ ] page transitions smoothly with correct page, neighbors, and arrows
- Header
  - [ ] project title and author appears aligned left, truncated with ellipsis (...) if necessary
  - [ ] tap the Webmaker logo to visit the website
- Get the app
  - [ ] "get the app" appears (desktop & tablet only)
  - [ ] tap app button to load play store page
  - [ ] text is localized properly

**Comment by xmatthewx** [comment]
Links to projects and screenshots to help testing: https://github.com/mozilla/webmaker-browser/issues/174#issuecomment-122050095

**Comment by xmatthewx** [comment]
Not quite as nice as the project found by @secretrobotron, but there are fewer options on staging.  https://webmaker-desktop-staging.herokuapp.com/#/player?user=638&project=691

**Comment by xmatthewx** [comment]
Let's use the `QA` label

**Comment by secretrobotron** [comment]
@cadecairos's script might be able to port them over.

**Comment by k88hudson** [comment]
@secretrobotron @xmatthewx i just deployed to prod so you should be able to use it there as soon as it builds

**Comment by k88hudson** [comment]
i.e. https://beta.webmaker.org/#/player?user=638&project=691

**Comment by secretrobotron** [comment]
Coolness factor: :bomb: .... :boom: !!

**Comment by xmatthewx** [comment]
Amazing. I'll see your i.e. and raise it to e.g. :boom: :rocket: 
- draw: https://beta.webmaker.org/#/player?user=446905&project=4072 
- pokemon: https://beta.webmaker.org/#/player?user=426154&project=2926
- !!!!!: https://beta.webmaker.org/#/player?user=277436&project=2413
- sketchbook: https://beta.webmaker.org/#/player?user=438321&project=2369

It'd be nice if the user:1, project:1 on staging was nice for testing with community. Obviously not critical.

**Comment by secretrobotron** [comment]
:rocket: 
:boom: 
:boom: 
:boom: 
:boom: 
:boom: 
:boom: 
:boom: 
:boom: 
:boom: 
:boom:

**Comment by xmatthewx** [comment]
Moved script and links to a google doc for use by community: http://bit.ly/wm-browser-QA

**Comment by xmatthewx** [comment]
QA for browser-based player
- start here: http://bit.ly/wm-browser-QA 

QA for Android app: 
- WIP: http://bit.ly/wm-android-QA
