### ISSUE TITLE
UX - "send to back" for zindex

### ISSUE THREAD

**Issue by toolness** [mozilla/webmaker-core#170]
This issue has been migrated from mozilla/webmaker-android#2102.

It was originally written by [secretrobotron](https://api.github.com/users/secretrobotron) on Fri Jun 05 2015 and had the following description:

> Can we implement a "send to back" feature for moving elements as far back as possible? Maybe press & hold?
> 
> Really difficult to quickly move small objects forward (like text on top of an image).

On Fri Jun 05 2015, [xmatthewx](https://api.github.com/users/xmatthewx) commented:

> Agreed. Current z-index seems to have a few bugs that need squashing, that make it a bit harder to use. mozilla/webmaker-android#2101 mozilla/webmaker-android#2103. Send to back would require some UX design. 

On Fri Jun 05 2015, [xmatthewx](https://api.github.com/users/xmatthewx) commented:

> Here's is an option. Opinions **@****flukeout** **@****vazquez** ? 
> 
> ![send to back](https://cloud.githubusercontent.com/assets/53411/8461172/a9a5a520-1ff8-11e5-9fae-6d1518a94279.png)

On Fri Jun 05 2015, [secretrobotron](https://api.github.com/users/secretrobotron) commented:

> Just want to check: are you proposing a popup menu?

On Fri Jun 05 2015, [xmatthewx](https://api.github.com/users/xmatthewx) commented:

> Yep. A little pop up menu.

**Comment by xmatthewx** [comment]
tracking #244
