### ISSUE TITLE
Localize Welcome Email 

### ISSUE THREAD

**Issue by toolness** [mozilla/webmaker-core#172]
This issue has been migrated from mozilla/webmaker-android#2108.

It was originally written by [gauthraj](https://api.github.com/users/gauthraj) on Sun Jun 07 2015 and had the following description:

> When registering for webmaker account from the webmaker app still receving the same welcome mail received when registered from desktop - featuring X-ray googles, Thimble and Popcorn maker. Expected result - welcome email should hightlight and provide info about webmaker app
> ![photo_2015-06-07_10-43-55](https://cloud.githubusercontent.com/assets/11516300/8022696/3e5f38a2-0d02-11e5-8dc7-f92a30c52f24.jpg)

On Sun Jun 07 2015, [LauraReynal](https://api.github.com/users/LauraReynal) commented:

> The one I received was a different one from Mark
> 
> ![screen shot 2015-06-07 at 12 09 46](https://cloud.githubusercontent.com/assets/8261945/8022827/2c70e8aa-0d0e-11e5-9397-37c5bae4dc44.png)

On Mon Jun 08 2015, [thisandagain](https://api.github.com/users/thisandagain) commented:

> **@****secretrobotron** **@****hpauljohnson** Is this something the two of you can tackle this week?

On Mon Jun 08 2015, [HPaulJohnson](https://api.github.com/users/HPaulJohnson) commented:

> Yes - on my list for the next few days. 

On Wed Jun 10 2015, [HPaulJohnson](https://api.github.com/users/HPaulJohnson) commented:

> Updated copy attached. Assumption is that we implement once we have a fully functional app - meaning people download/create an account. If we need something for the interim we can make some tweaks. 
> 
> https://etherpad.mozilla.org/webmaker-welcome-email
> 
> **@****thisandagain** When does the /app page (and homepage redirect) go from lead gen to download the (beta) app?

On Wed Jun 10 2015, [HPaulJohnson](https://api.github.com/users/HPaulJohnson) commented:

> Also, would love to plug an additional email in for 5-7 days after install (maybe even 3 because, as I understand it, that's where the point of no return is for many new users). If we work up some copy is this something we can setup? This relates to: https://github.com/mozilla/webmaker-launch/issues/12

On Wed Jun 10 2015, [thisandagain](https://api.github.com/users/thisandagain) commented:

> Nice. Copy looks :+1: 
> 
> We'll move from lead gen to Play Store when the beta goes live on Google Play (given the lag from the Play Store, let's say Wednesday next week). Work for you **@****HPaulJohnson** ?

On Wed Jun 10 2015, [LauraReynal](https://api.github.com/users/LauraReynal) commented:

> How possible or crazy would it be to have a localized email according to the user ?
> Do we know other apps / soft who does that ? 

On Wed Jun 10 2015, [HPaulJohnson](https://api.github.com/users/HPaulJohnson) commented:

> If you mean localized as in language, I'd assume we can/will do that for this communication. 
> 
> If you mean personalization, I'd love to do that too though I don't think our current transactional email platform is well setup for that. 

On Wed Jun 10 2015, [secretrobotron](https://api.github.com/users/secretrobotron) commented:

> :+1: to "localizing as in language". Should be able to get that going quickly.

On Wed Jun 10 2015, [LauraReynal](https://api.github.com/users/LauraReynal) commented:

> Yes as in language
> On Jun 10, 2015 11:24 PM, "Bobby Richter" notifications@github.com wrote:
> 
> > [image: :+1:] to "localizing as in language". Should be able to get that
> > going quickly.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/mozilla/webmaker-android/issues/2108#issuecomment-110843255
> > .

On Fri Jun 12 2015, [secretrobotron](https://api.github.com/users/secretrobotron) commented:

> English version being done here: https://github.com/mozilla/webmaker-mailroom/pull/35

On Fri Jun 12 2015, [secretrobotron](https://api.github.com/users/secretrobotron) commented:

> Landed. Need to address https://github.com/mozilla/webmaker-mailroom/issues/34 next week with **@****cadecairos** .

On Sat Jun 13 2015, [LauraReynal](https://api.github.com/users/LauraReynal) commented:

> Are you sure the english verison is landed ? 
> I made a new account this morning and I received the same email by Surman
> **@****HPaulJohnson** **@****secretrobotron** 

On Sat Jun 13 2015, [secretrobotron](https://api.github.com/users/secretrobotron) commented:

> It's landed. Probably needs to be pushed up to production though. **@****jbuck** ?
> On Jun 13, 2015 12:06 AM, "Laura de Reynal" notifications@github.com
> wrote:
> 
> > Are you sure the english verison is landed ?
> > I made a new account this morning and I received the same email by Surman
> > **@****HPaulJohnson** https://github.com/HPaulJohnson **@****secretrobotron**
> > https://github.com/secretrobotron
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/mozilla/webmaker-android/issues/2108#issuecomment-111667823
> > .

On Sat Jun 13 2015, [jbuck](https://api.github.com/users/jbuck) commented:

> ```
> Jons-MacBook-Pro-2:sawmill jbuck$ git push production master
> Everything up-to-date
> ```
> 
> Uhhh lemme look into this

On Sat Jun 13 2015, [jbuck](https://api.github.com/users/jbuck) commented:

> Oh wait, **@****LauraReynal**, you received two emails; one from Bobby and one from Surman, right. The one from Surman is sent by BSD after you check "Tell me about Mozilla news & events"

On Mon Jun 15 2015, [LauraReynal](https://api.github.com/users/LauraReynal) commented:

> Oh Really ? **@****jbuck** I did not see the one from **@****secretrobotron** and I just asked Mozillians who dont remember getting one neither.

On Mon Jun 15 2015, [LauraReynal](https://api.github.com/users/LauraReynal) commented:

> ok I will ask others and let you know if there is anything. 
> Thanks 

On Mon Jun 15 2015, [jbuck](https://api.github.com/users/jbuck) commented:

> **@****LauraReynal** When you get the new email it should look like this:
> 
> ![screenshot 2015-06-15 10 45 39](https://cloud.githubusercontent.com/assets/578466/8162531/e1e9362c-134b-11e5-96e2-3d8cced99713.png)

On Fri Jun 19 2015, [secretrobotron](https://api.github.com/users/secretrobotron) commented:

> Uploaded this file to Transifex yesterday. Should be good to start.

On Wed Jun 24 2015, [secretrobotron](https://api.github.com/users/secretrobotron) commented:

> **@****cadecairos** what do we need to do on id.webmaker.org to ensure the right locale is used?

On Wed Jul 08 2015, [alicoding](https://api.github.com/users/alicoding) commented:

> **@****secretrobotron** do we call this done?

On Wed Jul 08 2015, [secretrobotron](https://api.github.com/users/secretrobotron) commented:

> I'd like it to be integrated with the app first, **@****alicoding** . Make sense?

**Comment by alicoding** [comment]
This is actually done, so let's close this ticket \o/
