### ISSUE TITLE
We should be able to organize your own projects 

### ISSUE THREAD

**Issue by toolness** [mozilla/webmaker-core#177]
This issue has been migrated from mozilla/webmaker-android#2138.

It was originally written by [LauraReynal](https://api.github.com/users/LauraReynal) on Wed Jun 10 2015 and had the following description:

> Today you can't delete projects and it's very frustrating. 
> Also could we move them within the page to have the ones we want to display first ? 

On Wed Jun 10 2015, [xmatthewx](https://api.github.com/users/xmatthewx) commented:

> Delete is coming soon in mozilla/webmaker-android#2018. The ability to organize your projects could be something we consider when we dig into profile and social later this year.

**Comment by xmatthewx** [comment]
tracking in #650
