### ISSUE TITLE
Add commit hash/version number to style guide

### ISSUE THREAD

**Issue by toolness** [mozilla/webmaker-core#182]
This issue has been migrated from mozilla/webmaker-android#2166.

It was originally written by [k88hudson](https://api.github.com/users/k88hudson) on Thu Jun 11 2015 and had the following description:

> It would be great to have a commit hash for people to ensure they are on the right build when testing patches/filing bugs.

On Fri Jun 12 2015, [xmatthewx](https://api.github.com/users/xmatthewx) commented:

> major :+1: 

On Fri Jun 12 2015, [ryanw-se](https://api.github.com/users/ryanw-se) commented:

> **@****k88hudson** **@****xmatthewx** Can I take this ticket over the weekend?

On Fri Jun 12 2015, [xmatthewx](https://api.github.com/users/xmatthewx) commented:

> Thanks **@****ryanw-se** - sounds great to me. **@****thisandagain** would know if there's anything more interesting or higher priority, but this seems like a nice bite-sized weekend project.  

On Fri Jun 12 2015, [xmatthewx](https://api.github.com/users/xmatthewx) commented:

> Slightly related: Are we going to hide the button to access this guide on Beta release? Or, wait until v1?

On Fri Jun 12 2015, [ryanw-se](https://api.github.com/users/ryanw-se) commented:

> **@****xmatthewx** It's only displayed if the APK is a debug build. Otherwise, unless it is set to a non-debug build (shipping to Google Play, Exporting APK) it will not appear for users.
> 
> Edit: It appears that BuildConfig's debug value will need to be set to false in order for the button not to appear, since it apparently isn't setting that value automatically.

**Comment by errietta** [comment]
closed per 14:02 < ryanw-se> Can someone please close tickets, #281, #182, #365
14:02 < ryanw-se> All of them contain fixes that were landed a short while ago, except for the style guide git hash, that was landed a few months
ago and got reopened when they migrated tickets
