### ISSUE TITLE
Login - Explore using onBlur for validation errors rather than onKeyUp

### ISSUE THREAD

**Issue by toolness** [mozilla/webmaker-core#186]
This issue has been migrated from mozilla/webmaker-android#2187.

It was originally written by [thisandagain](https://api.github.com/users/thisandagain) on Fri Jun 12 2015 and had the following description:

> We are currently really aggressive about displaying validation errors for `username` and `email` fields which is fairly jarring during the sign-up UX. I'd like to explore some options including only displaying validation errors onBlur.

On Fri Jun 12 2015, [thisandagain](https://api.github.com/users/thisandagain) commented:

> /cc **@****k88hudson** **@****xmatthewx** **@****vazquez**

**Comment by vazquez** [comment]
![error annotations](https://cloud.githubusercontent.com/assets/1119821/9252880/c2152e06-41a8-11e5-8422-16f9defe0a35.png)

Let me know what you think  @xmatthewx

**Comment by xmatthewx** [comment]
Looks good. Couple of minor bits to discuss. Seems like enhancement of error handling can proceed independent of new UI, correct?

**Comment by vazquez** [comment]
@xmatthewx - Updating the UI to the old UI so work can continue on this bug. R?

![error annotations](https://cloud.githubusercontent.com/assets/1119821/9339292/3690b022-45b7-11e5-8c4b-5fe032125537.png)

**Comment by xmatthewx** [comment]
While an error should first appear onblur, it should be rechecked as user types, cleared when fixed.
