### ISSUE TITLE
Discover gallery has 0 height thumbnails

### ISSUE THREAD

**Issue by toolness** [mozilla/webmaker-core#189]
This issue has been migrated from mozilla/webmaker-android#2207.

It was originally written by [k88hudson](https://api.github.com/users/k88hudson) on Fri Jun 12 2015 and had the following description:

> After creating a new account and opening discovery for the first time, I was somehow able to get to a state where all the thumbnails were 0 height. After refreshing, they were fine. Not able to reproduce this a second time.

On Fri Jun 12 2015, [xmatthewx](https://api.github.com/users/xmatthewx) commented:

> I saw the same thing recently. I left Discover and saw the same thing in Make. Refreshed to fix it there, but I believe I returned to Discover and saw thumbnails without a refresh. Slow loading?

On Fri Jun 12 2015, [thisandagain](https://api.github.com/users/thisandagain) commented:

> I wonder if this could be coming from the `react-imageloader`? I can only replicate on a totally fresh install (no state in-memory).

On Sat Jun 13 2015, [LauraReynal](https://api.github.com/users/LauraReynal) commented:

> Same thing here in Bangladesh at random moments. 

On Mon Jun 15 2015, [thisandagain](https://api.github.com/users/thisandagain) commented:

> Tracking in mozilla/webmaker-android#2208 

On Mon Jun 15 2015, [jbuck](https://api.github.com/users/jbuck) commented:

> **@****cadecairos** and I think this is a different issue from mozilla/webmaker-android#2208, so re-opening.

On Mon Jun 15 2015, [jbuck](https://api.github.com/users/jbuck) commented:

> **@****cadecairos** dug into this a bit and it's a bug with react-imageloader where it's not updating the state of the image after loading it. Basically it loads the image with display:none set and doesn't update that until the React re-render comes along and re-renders it.

On Mon Jun 15 2015, [cadecairos](https://api.github.com/users/cadecairos) commented:

> Digging deeper reveals that React's image component isn't firing an onLoad event. Indicates a bug in either that component or in how react-imageloader is adding the image component to the DOM 

On Tue Jun 16 2015, [cadecairos](https://api.github.com/users/cadecairos) commented:

> I can't reproduce this issue anymore, **@****jbuck** perhaps your changes in mozilla/webmaker-android#2208 made a difference somehow?

On Tue Jun 16 2015, [jbuck](https://api.github.com/users/jbuck) commented:

> But how....
> 
> The change I made should have only affected the behaviour of thumbnails that haven't been generated yet :tired_face: 

On Tue Jun 16 2015, [cadecairos](https://api.github.com/users/cadecairos) commented:

> I lied, It worked because I modified react-imageloader to use
> 
> ```
> React.createElement('img', { src: this.props.src });
> ```
> 
> instead of what it currently does (after being compiled from coffeescript)
> 
> ```
> img(merge(this.props, {
>       ref: 'image',
>       onLoad: this.handleLoad,
>       onError: this.handleError
>     }));
> ```
> 
> where img is `React.DOM.img`

On Tue Jun 16 2015, [cadecairos](https://api.github.com/users/cadecairos) commented:

> cc **@****Pomax** 

On Wed Jun 17 2015, [cadecairos](https://api.github.com/users/cadecairos) commented:

> I have zero ideas how to fix this beyond replacing react-imageloader
> 
> **@****jbuck** **@****thisandagain** **@****Pomax** **@****k88hudson** 

On Wed Jun 17 2015, [cadecairos](https://api.github.com/users/cadecairos) commented:

> I filed this upstream: https://github.com/hzdg/react-imageloader/issues/16

On Wed Jun 17 2015, [Pomax](https://api.github.com/users/Pomax) commented:

> looking at the node_modules/react-imageloader/lib/index.js, it seems like things might fail if onLoad on the image fires before the component has mounted (say, we load images _really fast_). Might be worth checking what happens on L53-54 in that react-imageloader file, to see if it returns early during a test run.

On Wed Jun 17 2015, [cadecairos](https://api.github.com/users/cadecairos) commented:

> **@****Pomax** That function doesn't even get called :/

On Wed Jun 17 2015, [cadecairos](https://api.github.com/users/cadecairos) commented:

> What are the chances that the image tag is choking trying to detect the mimetype of the src

On Fri Jun 19 2015, [thisandagain](https://api.github.com/users/thisandagain) commented:

> **@****k88hudson** is still seeing this from time-to-time in the latest build. Re-opening in the 1.0.1 milestone.

On Fri Jun 19 2015, [cadecairos](https://api.github.com/users/cadecairos) commented:

> That's unfortunate... if this isn't fixed upstream by the time we get back to it I think we should find an alternative image component.

**Comment by k88hudson** [comment]
This should be resolved by https://github.com/mozilla/webmaker-core/commit/e7cc1b976818708871ca1ec8013eea36f3b33ee1
