### ISSUE TITLE
Display 404 when loading projects that do not exist

### ISSUE THREAD

**Issue by toolness** [mozilla/webmaker-core#191]
This issue has been migrated from mozilla/webmaker-android#2230.

It was originally written by [secretrobotron](https://api.github.com/users/secretrobotron) on Mon Jun 15 2015 and had the following description:

> From a share url to a non-existent project, users are lead to an empty player. No errors, and easy to get out, but should probably just lead to the discover gallery with an error.
> 
> From mozilla/webmaker-android#2223

On Mon Jun 15 2015, [thisandagain](https://api.github.com/users/thisandagain) commented:

> Good catch. :+1: 

On Tue Jun 16 2015, [jgmac1106](https://api.github.com/users/jgmac1106) commented:

> I am running into this issue. I searched the repo to see if the issue has been posted but here are my links to a project I made:
> https://t.co/pRsVMds1pY 
> This went through Twitter's url shortner using Plume for Android
> 
> I also tested if it was the url shortner and emailed myself the shared project and got this: https://beta.webmaker.org/users/1249/projects/514
> 
> Either way I am just brought to a blank screen and do not see the project I shared. Does it need to be opened only on other Android devices with webmaker installed to see someone's projects?

On Tue Jun 16 2015, [thisandagain](https://api.github.com/users/thisandagain) commented:

> :+1: Tracking the root cause of **@****jgmac1106** 's issue here (on track to have resolved by EOW): https://github.com/mozilla/webmaker-desktop/issues/62

**Comment by thisandagain** [comment]
This should be resolved by the 404 that @xmatthewx was working on. To resolve this, we need to detect a 404 when looking up a project and display the proper error (404) state.

**Comment by k88hudson** [comment]
@xmatthewx @thisandagain is there design work for this?

**Comment by xmatthewx** [comment]
We discussed leveraging the [site's error page](https://beta.webmaker.org/#/NothingToSeeHere), rather than a 404 _within_ the project viewer. 

Nice to have: a project specific error message. Something like: 

<img width="839" alt="screenshot 2015-08-05 12 10 33" src="https://cloud.githubusercontent.com/assets/53411/9090902/16414a80-3b6b-11e5-92c6-2ed016c9848a.png">

**Comment by k88hudson** [comment]
Resolved by https://github.com/mozilla/webmaker-browser/commit/d7f414025d72e886655cefdd5ce8ec657510744c
