### ISSUE TITLE
Button label text resets with one order of events

### ISSUE THREAD

**Issue by toolness** [mozilla/webmaker-core#194]
This issue has been migrated from mozilla/webmaker-android#2241.

It was originally written by [xmatthewx](https://api.github.com/users/xmatthewx) on Mon Jun 15 2015 and had the following description:

> The label sticks in most scenarios, but I found one that repeatedly fails. 
> 
> STR
> - add a link
> - change the label and style
> - exit the link editor
> - tap set destination
> - set a destination
> - label resets to default

On Mon Jun 15 2015, [xmatthewx](https://api.github.com/users/xmatthewx) commented:

> Might be the cause behind mozilla/webmaker-android#2221 

On Tue Jun 16 2015, [thisandagain](https://api.github.com/users/thisandagain) commented:

> Thanks for tracking down this STR!

**Comment by gvn** [comment]
@Pomax do you think this will be fixed once your bulk patch lands?

**Comment by Pomax** [comment]
we can test it: #402 should be "done" at this point, so if it still does that, it's probably a distinct bug, but I'm hoping it's not..?

**Comment by gvn** [comment]
Appears to be solved by the bulk code that just landed!

**Comment by Pomax** [comment]
\o/
