### ISSUE TITLE
Device - Nexus 7 (2012)

### ISSUE THREAD

**Issue by toolness** [mozilla/webmaker-core#198]
This issue has been migrated from mozilla/webmaker-android#2255.

It was originally written by [thisandagain](https://api.github.com/users/thisandagain) on Tue Jun 16 2015 and had the following description:

> So ... we support 3 of the 5 different versions of the Nexus 7, but apparently NOT the version that everyone at MOFO has. Yay. :stuck_out_tongue_winking_eye: 
> 
> ![screen shot 2015-06-16 at 9 29 03 am](https://cloud.githubusercontent.com/assets/747641/8188343/35d2dcf2-140a-11e5-99b1-073dbf27404c.png)

On Tue Jun 16 2015, [Pomax](https://api.github.com/users/Pomax) commented:

> device info for my nexus 7, which sees no results for "webmaker beta" in the play store:
> 
> ```
> IC: 3568A-ME370T
> Model: nexus 7
> Android: 5.1.1
> Kernel: 3.1.10-gf5d7b8b
> Build: LMY47V
> ```
> 
> System up to date in the sense that there are no updates available for it according to Google.

On Mon Jul 13 2015, [omnignorant](https://api.github.com/users/omnignorant) commented:

> Adding a comment here to note that my Nexus 7 device cannot access Webmaker on the Play store: same device info as noted by **@****Pomax** above.
> 
> ```
> IC: 3568A-ME370T
> Model: nexus 7
> Android: 5.1.1
> Kernel: 3.1.10-gf5d7b8b
> Build: LMY47V
> ```

**Comment by thisandagain** [comment]
Resolved by https://github.com/mozilla/webmaker-android/pull/2370
