### ISSUE TITLE
Network - App refresh onResume

### ISSUE THREAD

**Issue by toolness** [mozilla/webmaker-core#199]
This issue has been migrated from mozilla/webmaker-android#2257.

It was originally written by [davidascher](https://api.github.com/users/davidascher) on Tue Jun 16 2015 and had the following description:

> STR:
> - open webmaker app
> - open a project, zoom in to a page
> - use task manager to swap to another app
> - use task manager to swap back to webmaker
> 
> --> Spinner shows up to do a refresh, while I don't know why it should.

On Tue Jun 16 2015, [davidascher](https://api.github.com/users/davidascher) commented:

> Same thing after device sleep / wake.

On Tue Jun 16 2015, [thisandagain](https://api.github.com/users/thisandagain) commented:

> We should be able to remove the `onPause` and `onResume` handlers as we refactor the network architecture. Related to mozilla/webmaker-android#2179 
> 
> /cc **@****k88hudson** 

On Tue Jul 14 2015, [k88hudson](https://api.github.com/users/k88hudson) commented:

> This is blocked on mozilla/webmaker-android#2179

On Tue Jul 14 2015, [ryanw-se](https://api.github.com/users/ryanw-se) commented:

> **@****k88hudson** That ticket is primarily blocked by the uplift api.js ticket, I'll make sure to have that done in the next couple of days so we can move forward with this.

On Tue Jul 14 2015, [k88hudson](https://api.github.com/users/k88hudson) commented:

> Great, thanks **@****ryanw-se**

**Comment by Pomax** [comment]
assuming fixed due to lots of followup.
