### ISSUE TITLE
Disable links on pages while in project view

### ISSUE THREAD

**Issue by toolness** [mozilla/webmaker-core#201]
This issue has been migrated from mozilla/webmaker-android#2260.

It was originally written by [flukeout](https://api.github.com/users/flukeout) on Tue Jun 16 2015 and had the following description:

> Steps to reproduce
> - Open a project that has a page with a button on it linked to another page
> - Go to map mode
> - Tap the page next to the button
>   - Page zooms in
> - Zoom back out
> - Tap the page on the button
> - You are transitioned to the destination page
> 
> This is a little bit confusing, especially on pages that have multiple buttons, which makes it hard to zoom in on that page.
> 
> Some ideas, 
> - Disable buttons when zoomed out
> - When a button is tapped in map mode, offer binary choice between zoom and navigate? 
> - ...
> - Leave as is?
> 
> **@****xmatthewx** **@****vazquez** 

On Wed Jul 01 2015, [xmatthewx](https://api.github.com/users/xmatthewx) commented:

> I think links should only be enabled while in Page view. Active buttons muddle the project view with unexpected behavior. 
> 
> This seems like an easy fix and worth doing sooner than later. 

On Fri Jul 10 2015, [xmatthewx](https://api.github.com/users/xmatthewx) commented:

> Users sometimes expect these buttons to work in the project view because we allow too much zoom: mozilla/webmaker-android#2359

**Comment by k88hudson** [comment]
Resolved by 0687eda
