### ISSUE TITLE
Add numbers to new project default titles

### ISSUE THREAD

**Issue by toolness** [mozilla/webmaker-core#205]
This issue has been migrated from mozilla/webmaker-android#2268.

It was originally written by [ioana-chiorean](https://api.github.com/users/ioana-chiorean) on Wed Jun 17 2015 and had the following description:

> Create several projects =. 
> Actual results:
> - all are name my projects
> 
> Expected result:
> - I should have My projects, My projects (2) etc 
>   -> it is consistent to other projects in mozilla ( add new search engine in firefox/fennec)
>   -> I can have a overview where I am while panning otherwise looks like infinite
> 
> ![811733264_1882518357838919385](https://cloud.githubusercontent.com/assets/1391451/8220146/737a50a4-1558-11e5-8b68-68efdef9173c.jpg)

On Thu Jun 18 2015, [xmatthewx](https://api.github.com/users/xmatthewx) commented:

> related to mozilla/webmaker-android#2183

**Comment by xmatthewx** [comment]
tracking in #185
