### ISSUE TITLE
Can't make images larger than page

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker-core#21]
I'm unable to scale an image to be larger than the page it's on. It's useful to be able to do that when I want to crop a picture (in a simple fashion).

**Comment by secretrobotron** [comment]
@gvn

**Comment by secretrobotron** [comment]
Wait, this only happened once when I created the image. It's now fine after fiddling with other elements and the rest of the app. Weird?

**Comment by thisandagain** [comment]
Tracking in #234

**Comment by flukeout** [comment]
@thisandagain I'm going to re-open this because I don't think it's related.
