### ISSUE TITLE
Beta landing page renders wrong on Firefox

### ISSUE THREAD

**Issue by toolness** [mozilla/webmaker-core#215]
This issue has been migrated from mozilla/webmaker-android#2292.

It was originally written by [flukeout](https://api.github.com/users/flukeout) on Mon Jun 22 2015 and had the following description:

> **Firefox** :fire: :x: 
> ![image](https://cloud.githubusercontent.com/assets/25212/8288960/3eb253a2-18ce-11e5-88a3-54634b88cc9e.png)
> 
> **Chrome** :ice_cream: :heavy_check_mark:
> ![image](https://cloud.githubusercontent.com/assets/25212/8288962/447c5a30-18ce-11e5-9950-b96b2e6f5c1b.png)

On Mon Jun 22 2015, [flukeout](https://api.github.com/users/flukeout) commented:

> Looks like this is because for me it shows two lines of subhead copy in Firefox and only one in Chrome, which alters the layout.
> 
> Is the copy we show browser-based, or are we doing some A/B testing and I just happen to load two different versions?

On Mon Jun 22 2015, [HPaulJohnson](https://api.github.com/users/HPaulJohnson) commented:

> **@****flukeout** - there's a landing page test running in Optimizely that's the culprit.

**Comment by mmmavis** [comment]
I'll take a look at this today!
