### ISSUE TITLE
Make sure keyboard matches locale

### ISSUE THREAD

**Issue by toolness** [mozilla/webmaker-core#218]
This issue has been migrated from mozilla/webmaker-android#2296.

It was originally written by [secretrobotron](https://api.github.com/users/secretrobotron) on Tue Jun 23 2015 and had the following description:

> For non-english locales, the keyboard that pops up should be in the appropriate language.

On Thu Jul 02 2015, [alicoding](https://api.github.com/users/alicoding) commented:

> I don't know if that's true or is the case here? I often use two languages within an English only or Thai only application, so the the language of the keyboard or app shouldn't change based on the other.

On Fri Jul 03 2015, [secretrobotron](https://api.github.com/users/secretrobotron) commented:

> That's kind of what I thought too. This was something a user complained about.
> 
> So, what's the default keyboard that pops up when you open an app? How do you change keyboards?

On Fri Jul 03 2015, [alicoding](https://api.github.com/users/alicoding) commented:

> It really depends on the keyboard app you use as well. Let say I use
> Fleksy which doesn't support Thai but I use it as my default.
> On Jul 3, 2015 8:11 AM, "Bobby Richter" notifications@github.com wrote:
> 
> > That's kind of what I thought too. This was something a user complained
> > about.
> > 
> > So, what's the default keyboard that pops up when you open an app? How do
> > you change keyboards?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/mozilla/webmaker-android/issues/2296#issuecomment-118331490
> > .

On Fri Jul 03 2015, [alicoding](https://api.github.com/users/alicoding) commented:

> I think its an OS design and we shouldn't control what language to display unless we are asking for number input or trying to get a specific input in English only then we should force them otherwise I don't think that's a good idea to do at all.

On Fri Jul 03 2015, [secretrobotron](https://api.github.com/users/secretrobotron) commented:

> OK, so basically, it's totally up to the user?
> On Jul 3, 2015 1:18 PM, "Ali Al Dallal" notifications@github.com wrote:
> 
> > It really depends on the keyboard all you use as well. Let say it I use
> > Fleksy which doesn't support Thai but I use it as my default.
> > On Jul 3, 2015 8:11 AM, "Bobby Richter" notifications@github.com wrote:
> > 
> > > That's kind of what I thought too. This was something a user complained
> > > about.
> > > 
> > > So, what's the default keyboard that pops up when you open an app? How do
> > > you change keyboards?
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > > https://github.com/mozilla/webmaker-android/issues/2296#issuecomment-118331490
> > > 
> > > .
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/mozilla/webmaker-android/issues/2296#issuecomment-118332913
> > .

On Fri Jul 03 2015, [secretrobotron](https://api.github.com/users/secretrobotron) commented:

> :+1:
> On Jul 3, 2015 1:56 PM, "Ali Al Dallal" notifications@github.com wrote:
> 
> > I think its an OS design and we shouldn't control what language to display
> > unless we are asking for number input or trying to get a specific input in
> > English only then we should force them otherwise I don't think that's a
> > good idea to do at all.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/mozilla/webmaker-android/issues/2296#issuecomment-118340015
> > .

**Comment by thisandagain** [comment]
Agreed with @alicoding 's last comment in this thread that we should obey the OS in regards to what keyboard is used (which doesn't require a change). I suggest this be closed ... @alicoding thoughts?

**Comment by alicoding** [comment]
Yep let's close this thread :)
