### ISSUE TITLE
Add color selector for button label text

### ISSUE THREAD

**Issue by toolness** [mozilla/webmaker-core#224]
This issue has been migrated from mozilla/webmaker-android#2308.

It was originally written by [secretrobotron](https://api.github.com/users/secretrobotron) on Wed Jun 24 2015 and had the following description:

> Steps to reproduce
> - Add a button
> - Use Tinker mode to change the background color
> - The button label text changes from white to black
> 
> It should stay white.. or better yet, you should be able to set the button label color.

On Mon Jun 29 2015, [xmatthewx](https://api.github.com/users/xmatthewx) commented:

> Related to: mozilla/webmaker-android#2240. Agreed. Not sure why we don't just allow people to set text color.

**Comment by thisandagain** [comment]
@xmatthewx can you provide an STR?

**Comment by xmatthewx** [comment]
STR in original comment above. 

It might be better/easier to add color selector for link color instead of auto setting color based on background color.

**Comment by xmatthewx** [comment]
refiling as https://github.com/mozilla/webmaker-core/issues/615 because this issue is a mess.
