### ISSUE TITLE
Migrate all open issues from webmaker-android into this repository

### ISSUE THREAD

**Issue by toolness** [mozilla/webmaker-core#23]
As per the daily stand today, we want to migrate [all 262 open issues from mozilla/webmaker-android](https://github.com/mozilla/webmaker-android/issues) into this repository (**mozilla/webmaker-core**) by EOD today.

We'll be using a [basic branch of toolness/learning-issue-migrator](https://github.com/toolness/learning-issue-migrator/tree/webmaker-core-migration) to do most of this for us. As such, all labels, milestones, and assignees will be copied.

**Comment by ryanwarsaw** [comment]
@toolness When will the migration start and finish?

**Comment by k88hudson** [comment]
Looks good @toolness !

**Comment by toolness** [comment]
Ok! The migration has started.

**Comment by toolness** [comment]
We've migrated through to https://github.com/mozilla/webmaker-android/issues/2108 but then triggered GitHub's abuse detection mechanism. I'll finish migrating the rest after a break.

**Comment by toolness** [comment]
Ok, after accidentally migrating 2 issues twice (and undoing them), I'm continuing the migration process. About 110 more issues to go.

**Comment by toolness** [comment]
Ok, it's done!! I'm closing this issue now.

**Comment by toolness** [comment]
Note that my script accidentally migrated 3 open PRs, but thanks to @ryanw-se we were able to undo that before too many people noticed. :eyes:

**Comment by k88hudson** [comment]
Thanks @toolness!
