### ISSUE TITLE
Change border-radius property on images to use % and increase maximum value to 50% to allow for circles.

### ISSUE THREAD

**Issue by toolness** [mozilla/webmaker-core#231]
This issue has been migrated from mozilla/webmaker-android#2316.

It was originally written by [flukeout](https://api.github.com/users/flukeout) on Wed Jun 24 2015 and had the following description:

> Currently, the border radius property caps out at 32px - which is too small a range for large images taken by the camera. Let's change that to make better, rounder images!

On Mon Jun 29 2015, [xmatthewx](https://api.github.com/users/xmatthewx) commented:

> :+1: 

On Mon Jun 29 2015, [thisandagain](https://api.github.com/users/thisandagain) commented:

> :+1: :goat:

**Comment by thisandagain** [comment]
@errietta This enhancement might be a good bug for you to hack on! :panda_face:

**Comment by errietta** [comment]
dibz

**Comment by errietta** [comment]
@thisandagain R? :panda_face:

**Comment by Pomax** [comment]
given how React deals with numbers, using percentages does not seem the right solution. Instead, we probably want to deal with it based on the original post proposed solution: 32px is too low to cap out at, so let's increase that value instead. Something like 120px, or computing the radius based on half the screen's width in pixels. The first is fairly straight forward, the latter isn't and might also have some UX implications so would probably be better as followup in a later heartbeat.

**Comment by errietta** [comment]
@Pomax i changed to 120 now, kept in variable so we can change easily.
