### ISSUE TITLE
App blocks me from moving a photo more than about 40% off the page

### ISSUE THREAD

**Issue by toolness** [mozilla/webmaker-core#234]
This issue has been migrated from mozilla/webmaker-android#2323.

It was originally written by [flukeout](https://api.github.com/users/flukeout) on Thu Jun 25 2015 and had the following description:

> Steps to reproduce
> - Take a photo and add it to a page
> - Move photo left or right to crop it
> - The app prevents me from moving the photo prematurely
> 
> It should allow me to move the photo (or other elements) until there is just a small amount of the element visible. Currently, I can only hide about 40% of a photo that is as large as the page.

On Wed Jul 01 2015, [xmatthewx](https://api.github.com/users/xmatthewx) commented:

> Seems like we were too aggressive in how we prevent things from moving off the page. We should only require that a reasonable touch target remains on the screen.

**Comment by xmatthewx** [comment]
related to #21 ??

**Comment by flukeout** [comment]
Closing because I filed it again with a fancy diagram in #435

**Comment by secretrobotron** [comment]
@flukeout did you want to close this one?
