### ISSUE TITLE
Consider offline publishing / editing

### ISSUE THREAD

**Issue by toolness** [mozilla/webmaker-core#236]
This issue has been migrated from mozilla/webmaker-android#2328.

It was originally written by [flukeout](https://api.github.com/users/flukeout) on Fri Jun 26 2015 and had the following description:

> Right now, a constant connection is required to successfully edit a project. Can we reduce the number and frequency of network requests to make the experience better?

**Comment by thisandagain** [comment]
This is being tracked in the batch API work now. /cc @Pomax

**Comment by Pomax** [comment]
yeah, let's move forward from that ticket instead.
