### ISSUE TITLE
Reduce number of steps to add an element to a project.

### ISSUE THREAD

**Issue by toolness** [mozilla/webmaker-core#238]
This issue has been migrated from mozilla/webmaker-android#2330.

It was originally written by [flukeout](https://api.github.com/users/flukeout) on Fri Jun 26 2015 and had the following description:

> Right now it takes 8 taps or so, well - way too many. Let's look at this flow and make it simpler and apply our learnings to other flows.

On Wed Jul 08 2015, [flukeout](https://api.github.com/users/flukeout) commented:

> Here's a first pass.
> 
> **Image**
> 
> ![image](https://cloud.githubusercontent.com/assets/25212/8580463/afda2db8-256f-11e5-81d3-ae9051be00af.png)
> 
> **Text**
> 
> ![image](https://cloud.githubusercontent.com/assets/25212/8580804/6561f674-2571-11e5-894b-b9e7a34c61af.png)
> 
> **Button**
> 
> ![image](https://cloud.githubusercontent.com/assets/25212/8583349/b9060f6c-2581-11e5-9e1c-ce220096ea7c.png)
> 
> cc **@****xmatthewx** 

On Wed Jul 08 2015, [xmatthewx](https://api.github.com/users/xmatthewx) commented:

> Cool. I will miss the stickers, but this is the right way to go.

On Wed Jul 08 2015, [flukeout](https://api.github.com/users/flukeout) commented:

> **@****xmatthewx** Shoot forgot about those - we can introduce them through another method?

On Wed Jul 08 2015, [xmatthewx](https://api.github.com/users/xmatthewx) commented:

> Add a third option: camera, gallery, stickers. But that'll require a spec of its own.

On Wed Jul 08 2015, [flukeout](https://api.github.com/users/flukeout) commented:

> Yeah, that's what i figured - or we could combine that with the 'web sources' or whatever.

On Wed Jul 08 2015, [xmatthewx](https://api.github.com/users/xmatthewx) commented:

> Right. We will definitely want image search on desktop since we essentially lose camera and gallery. We could explore stickers as a feature of that or a standalone thing. 

On Wed Jul 08 2015, [xmatthewx](https://api.github.com/users/xmatthewx) commented:

> image :+1:  text :+1: link :+1:

On Wed Jul 08 2015, [xmatthewx](https://api.github.com/users/xmatthewx) commented:

> **@****k88hudson** - can you give us a review of the design from a tech perspective?

**Comment by xmatthewx** [comment]
@k88hudson - this issue surface in a review of all the features/changes that haven't yet been built as most impactful to user experience (by @vazquez @LauraReynal @flukeout and myself). 

It would be great to estimate the work required to make these changes and the risk of introducing new bugs.

**Comment by Pomax** [comment]
we need to rename the jump navigation, neither "button" or "link" properly describe what it actually does (it's purely internal page navigation).

**Comment by gvn** [comment]
I think "link" makes a fair amount of sense.

**Comment by Pomax** [comment]
The reason I don't like "link" is that it behaves nothing like actual links on the web. For one, they're buttons, not links, and they don't point to URIs, they are navigational jumps that change views (not by any common link mechanism, but through deep javascript magic)

**Comment by gvn** [comment]
Yeah, we're getting through the looking glass here by basically re-inventing the web to make a "web" that is an approximation or subset of the "world wide web". That's the context in which I think "link" makes sense. Our buttons change pages, and that's all they do (right now anyway), which is what links do on the traditional WWW.

**Comment by xmatthewx** [comment]
Splitting into three tickets: photos (#565), text (#566), link (#567).

**Comment by k88hudson** [comment]
thanks @xmatthewx !
