### ISSUE TITLE
Figure out tapping and double-tapping actions.

### ISSUE THREAD

**Issue by toolness** [mozilla/webmaker-core#240]
This issue has been migrated from mozilla/webmaker-android#2332.

It was originally written by [flukeout](https://api.github.com/users/flukeout) on Fri Jun 26 2015 and had the following description:

> A lot of people are double tapping elements to edit them, let's investigate this and add if appropriate. What other elements get double tapped?

**Comment by alanmoo** [comment]
Duplicate of #639. @xmatthewx Should we leave that one open as the title is more descriptive/action oriented?

**Comment by xmatthewx** [comment]
Sure. Closing. Tracking in #639.
