### ISSUE TITLE
Add & support additional image formats

### ISSUE THREAD

**Issue by toolness** [mozilla/webmaker-core#242]
This issue has been migrated from mozilla/webmaker-android#2335.

It was originally written by [flukeout](https://api.github.com/users/flukeout) on Fri Jun 26 2015 and had the following description:

> What can we do about...
> - GIFs
> - Transparent PNGs

On Fri Jun 26 2015, [ryanw-se](https://api.github.com/users/ryanw-se) commented:

> **@****flukeout** This needs the android label added, tickets regarding this matter are mozilla/webmaker-android#2284 & mozilla/webmaker-android#2251

**Comment by xmatthewx** [comment]
Tracking PNGs #212 and GIFs #196 elsewhere.
