### ISSUE TITLE
Network - Move API calls to Android

### ISSUE THREAD

**Issue by toolness** [mozilla/webmaker-core#260]
This issue has been migrated from mozilla/webmaker-android#2354.

It was originally written by [thisandagain](https://api.github.com/users/thisandagain) on Mon Jun 29 2015 and had the following description:

> Related: mozilla/webmaker-android#1946 mozilla/webmaker-android#2005 mozilla/webmaker-android#2179
> 
> All API calls are currently handled by `./lib/api.js` which is nice and simple but has one major drawback in that API requests need to complete prior to the current webview being dismissed / destroyed. This leads to issues in which long-running API requests can not be run in the background which blocks the UI and leads to performance issues (**particularly** on 2G and 3G cell networks). In addition, having the network layer exist in JS makes it more difficult to detect and manage network state effectively.
> 
> I recommend that we attempt to port the existing `./lib/api.js` API over to Java with as minimal changes as possible as a starting point. Tracking this specific SOW in mozilla/webmaker-android#2355 
> - [ ] Port existing `./lib/api.js` to Java (#2355)
> - [ ] Add network availability detection
> - [ ] Implement global network queue

On Mon Jun 29 2015, [Pomax](https://api.github.com/users/Pomax) commented:

> As first step, let's tackle the parity refactor, so the code does the same thing it does now, except through Java rather than JS.
> - [ ] https://github.com/mozilla/webmaker-android/issues/2355 - uplift `api.js` from JS to Java

**Comment by Pomax** [comment]
Closing due to lots of work done; if we discover we missed a thing, we can file issues for each thing we discover.
