### ISSUE TITLE
Uplift api.js so that it runs through Java

### ISSUE THREAD

**Issue by toolness** [mozilla/webmaker-core#261]
This issue has been migrated from mozilla/webmaker-android#2355.

It was originally written by [Pomax](https://api.github.com/users/Pomax) on Mon Jun 29 2015 and had the following description:

> There are multiple levels of difficult we can make this, so let's start simple:
> - [ ] Create a `public static class API {}` that does the same things, with the same signatures, that `api.js` does right now.
> - [ ] Bind that class to the `window.Android` object so our webviews can work with it
> - [ ] refactor `api.js` so that instead of running its own code, it forwards all calls to `window.Android.API.sameFunctionCall(same, function, arguments)`
> 
> And make that work properly. With that, we have a good basis to start adding better controls for network error detection, callback handling across webviews, and many other things that are really quite hard right now, but much easier if they happen outside of the JS thread.
> 
> In order to make sure we stay sane, we probably want to tackle that last step in stages too:
> - [ ] 1. mirror the `api.js` interface in `API.java` but make all the functions `public boolean ....() { return true; }`, with api.js simply adding a call to `window.Android.API.whateverfn(...)`, just to see if we can even hook them up.
> - [ ]  2. keep the code we run in `api.js` but refactor each function body to be a callback, and route the callback trigger through Java. api.js: `function abcd(x,y,z) { var callback = function() { /* all the code we had before, wrapped! */ }; window.Android.API.abcd(x,y,z, callback); }`, then see if that still works
> - [ ] 3. once both of those work, we have a solid basis to start lifting the actual workhorse code from api.js to java, and we can start lifting one function at a time without disrupting anything. Small PRs for big wins!

On Mon Jun 29 2015, [toolness](https://api.github.com/users/toolness) commented:

> Woot! Just to provide a bit more context for this and mozilla/webmaker-android#2354: I spent a while trying to debug the app because it kept reporting "Looks like there might be a problem with your username or password."  It took me quite a while to figure out that this was happening because my phone's **airplane mode** was activated--which is a silly mistake for a developer to make, but I'm sure it happens to less technical users too. Being able to report a separate "Check your internet connection" error would have made the problem a lot easier to figure out, and apparently we can easily do this if we uplift api.js so it runs through Java.

On Mon Jun 29 2015, [thisandagain](https://api.github.com/users/thisandagain) commented:

> **@****Pomax** do you mind mentoring **@****ryanw-se** on this?

On Mon Jun 29 2015, [Pomax](https://api.github.com/users/Pomax) commented:

> I'd be happy to.

**Comment by Pomax** [comment]
A stub for the idea as expressed in (not quite true) code:

# JAVA SIDE: API mirror

```
    public class APIMirror {
      public APIMirror() {
        ...
      }

      @JavaScript
      public void functionFromAPIJS1(...) {
        do things async here, and when a result comes in, serialize to JSON and add to a queue
        as:

        -> queue.add("function1", JSONSerialize(resultData));

        Every time that happens, Android can call a global JS function to initiate a "doing
        the processing" on the javascript side:

        -> callGlobalOnActivePageContext(" processAPIQueue(" + JSONSerialize(queue) + "); ");
      }

      @JavaScript
      public void functionFromAPIJS2(...) {
        ... 
        -> queue.add("function2", JSONSerialize(resultData));
        -> callGlobalOnActivePageContext(" processAPIQueue(" + JSONSerialize(queue) + "); ");
      }
    }
```

# JAVA SIDE: platform class

```
    public class Platform {
      APIMirror api = new APIMirror();
      ...
      @JavaScript
      APIMirror getAPI() {
        return api;
      }
      ...
    }
```

# JAVASCRIPT SIDE: api.js

```
    var javaApi = window.platform.getAPI();
    var apiqueue = require('./lib/apiqueue.js');
    module.exports = {
      function1: function(..., callback) {
        javaApi.functionFromAPIJS1(...);
        apiqueue.push("function1", callback)
      },

      function2: function(..., callback) {
        javaApi.functionFromAPIJS2(this,arguments)
        apiqueue.push("function2", callback)
      },

      ...
    };
```

# JAVASCRIPT SIDE: apiqueue.js

```
    var handlers = {};
    module.exports = {
      push: function(type, handler) {
        if(!handlers[type]) {
          handlers[type] = [];
        }
        handlers[type].push(handler);
      }
    };
```

# JAVASCRIPT SIDE: special handler global function that android can trigger

```
    var apiqueue = require('./lib/apiqueue');

    function processAPIQueue(jsonPayload) {
      var data = JSON.parse(jsonPayload);
      data.forEach(function(item) {
        var type = item.type;
        var data = item.data;
        // get all callbacks for this type
        var callbacks = apiqueue[type];
        callbacks.forEach(function(callback) {
          // try to send off the callback for handling
          try {
            callback(data);
            // and then invalidate that specific callback
          } catch (e) { 
            ...
          }
        });
      });
    }
```
