### ISSUE TITLE
Scrolling in element editor is difficult

### ISSUE THREAD

**Issue by toolness** [mozilla/webmaker-core#265]
This issue has been migrated from mozilla/webmaker-android#2362.

It was originally written by [xmatthewx](https://api.github.com/users/xmatthewx) on Mon Jun 29 2015 and had the following description:

> It's difficult to scroll vertically in the element editor because a gesture that begins on a slider isn't read as a scroll even if it's vertical. Slider sometimes jumps.
> 
> Is it possible to constrain the range or angle of gestures read as an attempt to use the slider?

On Tue Jun 30 2015, [flukeout](https://api.github.com/users/flukeout) commented:

> :+1: running into this too

On Wed Jul 01 2015, [LauraReynal](https://api.github.com/users/LauraReynal) commented:

> :+1: seen this too !

**Comment by xmatthewx** [comment]
tracking in #692
