### ISSUE TITLE
Update documentation to include the use of webmaker-core

### ISSUE THREAD

**Issue by toolness** [mozilla/webmaker-core#276]
This issue has been migrated from mozilla/webmaker-android#2392.

It was originally written by [ryanw-se](https://api.github.com/users/ryanw-se) on Mon Jul 06 2015 and had the following description:

> I get a error when running `npm run build`, it says "webmaker-core isn't installed" but the documentation is rather vague about the process on how to install webmaker-core.

On Mon Jul 06 2015, [xmatthewx](https://api.github.com/users/xmatthewx) commented:

> https://github.com/mozilla/webmaker-core/

On Mon Jul 06 2015, [ryanw-se](https://api.github.com/users/ryanw-se) commented:

> **@****xmatthewx** Thanks, it works now. That documentation should definitely be put in the webmaker-android repository as well, or mentioned to prevent confusion!

**Comment by gvn** [comment]
Documentation regarding core has been added to webmaker-android README.
