### ISSUE TITLE
Able to set title longer than maximum

### ISSUE THREAD

**Issue by toolness** [mozilla/webmaker-core#278]
This issue has been migrated from mozilla/webmaker-android#2394.

It was originally written by [secretrobotron](https://api.github.com/users/secretrobotron) on Wed Jul 08 2015 and had the following description:

> 1. Go to project settings
> 2. Type in super long title
> 3. Press back button
> 
> Title should be set to something lengthy now. Go back to settings to check.
> 
> cc **@****flukeout** **@****cadecairos** (does this affect the DB?)

On Wed Jul 08 2015, [secretrobotron](https://api.github.com/users/secretrobotron) commented:

> cc **@****xmatthewx** anybody working on bugs?

On Wed Jul 08 2015, [xmatthewx](https://api.github.com/users/xmatthewx) commented:

> Does it just get truncated? Or does everything break? We don't have any hands tackling bugs this week.

On Wed Jul 08 2015, [cadecairos](https://api.github.com/users/cadecairos) commented:

> it won't take down the db,  since the title column is defined with varchar without a length specifier (synonymous with the text datatype). Also, we didn't add any joi validation for title , so it's basically just client side validation right now. 
> 
> I think if we're limiting length client side we want to do the same server-side, since it's trivial to intercept and modify requests with a proxy. 

On Thu Jul 09 2015, [secretrobotron](https://api.github.com/users/secretrobotron) commented:

> Doesn't get truncated, and doesn't _seem_ to break anything. Just weird because we have a limit and it's not enforced.

On Thu Jul 09 2015, [flukeout](https://api.github.com/users/flukeout) commented:

> Let's nuke the limit as long as well handle the long names well in the UI. The name only seems to appear in the make and discover views for the time being anyway.

On Thu Jul 09 2015, [xmatthewx](https://api.github.com/users/xmatthewx) commented:

> Let's set a generous limit. 140 characters? 256? Otherwise, someone will drop War & Peace in there just because they can. 

On Thu Jul 09 2015, [cadecairos](https://api.github.com/users/cadecairos) commented:

> my thoughts exactly. can we file a bug on api.wmo to add validation to that param? clientside validation is easy to step around

**Comment by thisandagain** [comment]
@errietta Would you be interested in looking at this bug?

**Comment by errietta** [comment]
@thisandagain  yeah! what should the limit actually be?

**Comment by ryanwarsaw** [comment]
I pushed PR #17 a couple of weeks back to fix this issue, shortly after it was discussed the problem would be solved on the API side of things instead. Are we doubling back on that idea and going back to a hard coded value?

**Comment by thisandagain** [comment]
I think we need both. The UI should be bound to the same limit as the API. @cadecairos could you point @errietta at the validation rules?

**Comment by errietta** [comment]
@thisandagain Arrrr?

**Comment by errietta** [comment]
@Pomax  R?

**Comment by Pomax** [comment]
@errietta where is the PR linkback? I don't see an outstanding PR for this issue...

**Comment by errietta** [comment]
@Pomax https://github.com/errietta/webmaker-core/commit/72036ec5f39bcbe19f4c1488e07a3150f8b7039e it's linked above

**Comment by errietta** [comment]
@Pomax do'h forgot to actually PR. https://github.com/mozilla/webmaker-core/pull/530

**Comment by Pomax** [comment]
crosslinking to https://github.com/mozilla/webmaker-core/issues/505, since there's was discussion about which length to actually use: let's work the fix for that into this PR since it touches the exact same code - given that the database allows up to 256 characters, let's up the limit from 25 to 256 in our code too, and just take out the props override: max length should simply always be 256.

**Comment by errietta** [comment]
@Pomax do we keep min length?

**Comment by gvn** [comment]
Resolved by #528
