### ISSUE TITLE
Add `npm run build` to gradle

### ISSUE THREAD

**Issue by toolness** [mozilla/webmaker-core#281]
This issue has been migrated from mozilla/webmaker-android#2397.

It was originally written by [gvn](https://api.github.com/users/gvn) on Thu Jul 09 2015 and had the following description:

> Right now you have to run `npm run build` before compiling in Android Studio to ensure you have the latest version of the core compiled as well (most likely npm linked for local dev).
> 
> We should remove this extra step by just programatically running `npm run build` as part of the AS compilation process...I'm assuming this is a gradle thing.

On Thu Jul 09 2015, [gvn](https://api.github.com/users/gvn) commented:

> **@****ryanw-se** this might be a good one for you if you're interested!

On Mon Jul 13 2015, [ryanw-se](https://api.github.com/users/ryanw-se) commented:

> **@****gvn** I believe something like this was implemented a while back, it must have broken. Anyways, I can definitely try to take a look over the week and see what broke if there is a previous implementation.

On Mon Jul 13 2015, [gvn](https://api.github.com/users/gvn) commented:

> I wonder if it will work now that I aliased `npm start` to `npm run build`. My Android device is charging, but I can test that out soon...

On Mon Jul 13 2015, [ryanw-se](https://api.github.com/users/ryanw-se) commented:

> **@****gvn** If you test it and it works let me know, otherwise I can take a look at it sometime this week.

On Mon Jul 13 2015, [gvn](https://api.github.com/users/gvn) commented:

> K. Thx!

**Comment by errietta** [comment]
closed per 14:02 < ryanw-se> Can someone please close tickets, https://github.com/mozilla/webmaker-core/issues/281,   https://github.com/mozilla/webmaker-core/issues/182, https://github.com/mozilla/webmaker-core/issues/365
14:02 < ryanw-se> All of them contain fixes that were landed a short while ago, except for the style guide git hash, that was landed a few months 
                  ago and got reopened when they migrated tickets
