### ISSUE TITLE
SSL Certificate Error

### ISSUE THREAD

**Issue by toolness** [mozilla/webmaker-core#283]
This issue has been migrated from mozilla/webmaker-android#2400.

It was originally written by [ioana-chiorean](https://api.github.com/users/ioana-chiorean) on Fri Jul 10 2015 and had the following description:

> Error while opening the app:
> 
> <img src="https://cloud.githubusercontent.com/assets/1391451/8618752/bcb817e2-2719-11e5-9b87-6c51d76e1433.jpg" width="300">

**Comment by xmatthewx** [comment]
Can not duplicate
