### ISSUE TITLE
Update placeholder text on sign-in to include email

### ISSUE THREAD

**Issue by toolness** [mozilla/webmaker-core#284]
This issue has been migrated from mozilla/webmaker-android#2401.

It was originally written by [xmatthewx](https://api.github.com/users/xmatthewx) on Fri Jul 10 2015 and had the following description:

> Sign-in now accepts Username or Email. Update placeholder text accordingly. 

On Fri Jul 10 2015, [cadecairos](https://api.github.com/users/cadecairos) commented:

> When did app sign in start accepting emails?

On Fri Jul 10 2015, [xmatthewx](https://api.github.com/users/xmatthewx) commented:

> Unsure. Just tried it and it worked.

**Comment by ryanwarsaw** [comment]
I would like to take a shot at fixing this.

**Comment by xmatthewx** [comment]
This is done.
