### ISSUE TITLE
Display project title in header

### ISSUE THREAD

**Issue by toolness** [mozilla/webmaker-core#285]
This issue has been migrated from mozilla/webmaker-android#2402.

It was originally written by [xmatthewx](https://api.github.com/users/xmatthewx) on Fri Jul 10 2015 and had the following description:

> Android header should display project title in the project viewer and editor.

On Mon Jul 13 2015, [ryanw-se](https://api.github.com/users/ryanw-se) commented:

> With our current architecture I don't think this is possible, the current way allows us to send data from Android across the JS bridge, we'd have to reverse that and create a way to send data from JS to the Android side of things to properly implement this and other title tickets.

**Comment by xmatthewx** [comment]
@flukeout - take a look at the header as previously designed against the current build. let's update the design.

**Comment by ryanwarsaw** [comment]
@xmatthewx This functionality was added in the following PR, https://github.com/mozilla/webmaker-android/pull/2442. It allows us to set the title in any view, including project views. Once landed, this functionality will need to be incorporated in webmaker-core.
