### ISSUE TITLE
Localize Google Play listing

### ISSUE THREAD

**Issue by toolness** [mozilla/webmaker-core#289]
This issue has been migrated from mozilla/webmaker-android#2407.

It was originally written by [secretrobotron](https://api.github.com/users/secretrobotron) on Tue Jul 14 2015 and had the following description:

> Looks like the Play Store was translated, but according to our localization teams, it's not quite right.
> - How did it happen? Are we paying for it?
> - How can we change it? Would like to give our localizers access to it.
> 
> /cc **@****fauzanalfi** **@****kelimuttu** **@****maktrix** **@****panaggio** **@****peiying2** **@****bellayet**
> 
> See https://github.com/mozilla/webmaker-launch/issues/47#issuecomment-120825046 for specifics.

On Tue Jul 14 2015, [peiying2](https://api.github.com/users/peiying2) commented:

> according to Google Play website:
> https://www.google.co.id/intl/id/mobile/play/ - Google Play remains in English.  Although there is no Bengali in the language dropdown menu (bottom right corner of the screen), it seems the convention if you switch to another language.  
> 
> However if the text is Google Play Apps (Books, Games, Music, etc), the "product" name is translated.  In this case, the word "Apps"  would be translated: https://play.google.com/store?hl=id
> 
> Where does the Google Play Store phrase appear? Or does it say Google Play Apps?  Regardless, from the official site, it looks like Google Play remains in English, the rest can be translated.

**Comment by thisandagain** [comment]
How this was localized is a real mystery to me given how few people have access from MOCO. I'm reaching out to our contacts within Firefox release engineering to see if we can get an answer.

**Comment by thisandagain** [comment]
Looks like a feature of the Google Play store is that they auto translate into the user's locale (similar to Google Chrome):
http://android.stackexchange.com/questions/26809/is-there-a-way-to-turn-off-translation-in-google-play

:frowning:

**Comment by thisandagain** [comment]
In order to localize these, we just need a listing for the "Short Description" and "Long Description". Unfortunately, Bangla is not supported in Google Play.

<img width="865" alt="screen shot 2015-07-20 at 1 37 17 pm" src="https://cloud.githubusercontent.com/assets/747641/8786763/fb29fe78-2ee4-11e5-928b-4410c700207f.png">

@secretrobotron

**Comment by secretrobotron** [comment]
cc @fauzanalfi @kelimuttu

**Comment by secretrobotron** [comment]
@thisandagain: https://github.com/mozilla/webmaker-android/pull/2415

**Comment by kelimuttu** [comment]
Okay, so the mystery has clear now. We have to translate the exact string as the screenshot above right @secretrobotron ? Or do we need to wait after you finalized it on transifex?

**Comment by secretrobotron** [comment]
@kelimuttu i'll upload it to transifex ASAP and report back.

**Comment by secretrobotron** [comment]
@kelimuttu done: https://www.transifex.com/projects/p/webmaker/resource/google-play/

**Comment by secretrobotron** [comment]
##### Translated
- [x] Brazil
- [x] Indonesia

##### Reviewed
- [x] Brazil
- [x] Indonesia

##### Published
- [x] Brazil
- [x] Indonesia

##### QA'd
- [x] Brazil
- [x] Indonesia

**Comment by thisandagain** [comment]
All set with updates here. @secretrobotron good to close?

**Comment by secretrobotron** [comment]
@thisandagain i'd just like those teams to QA them quickly and then we're good.

**Comment by secretrobotron** [comment]
:boom: done.
