### ISSUE TITLE
Add swipe indicator buttons [player]

### ISSUE THREAD

**Issue by k88hudson** [mozilla/webmaker-core#292]
Designs here: https://github.com/mozilla/webmaker-browser/issues/154.

We need to add the swipe indicator buttons in the zoomed in swipable page view in play mode.

This is part of a group of issues related to the desktop player: https://github.com/mozilla/webmaker-browser/issues/154

**Comment by gvn** [comment]
- [x] Refine design for d-pad buttons (https://github.com/mozilla/webmaker-core/pull/325)
- [x] Integrate into `webmaker-browser` (https://github.com/mozilla/webmaker-browser/pull/173)
