### ISSUE TITLE
In webmaker-android, "npm run build" doesn't work on windows

### ISSUE THREAD

**Issue by toolness** [mozilla/webmaker-core#297]
The problem is similar to https://github.com/mozilla/webmaker-browser/issues/151. Basically, due to `npm explore` behaving entirely differently and weirdly on Windows, `npm run build` just launches an interactive session fo `cmd.exe` that sits there and waits for the user to type commands. Exiting the interactive session causes `npm run build` to continue, but without doing the actual task that `npm explore` was originally initiated for (e.g. running `npm install` in a subproject's directory).

**Comment by xmatthewx** [comment]
@toolness - is someone working on this that we should assign?

**Comment by toolness** [comment]
Oh, I've already fixed it in https://github.com/mozilla/webmaker-android/pull/2410, it's just waiting for  review from @Pomax!
