### ISSUE TITLE
[player] Temporarily disable page-to-page swipe nav

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-core#300]
A bug/regression has made swipe to page in page view crappy. Users don't seem to use it much based on in person testing. Since we will introduce an icon and tap for page to page nav, let's disable swipe until we have time to properly fix.

**Comment by k88hudson** [comment]
@gvn can you also disable pinch zoom while you're add it? It shouldn't be possible to zoom while in page mode
