### ISSUE TITLE
Add link to old webmaker tools in footer of webmaker.org

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker-core#303]
beta.webmaker.org (soon to be webmaker.org) needs a link to old tools that points at teach.mozilla.org/tools.
- Should we just include a link in the existing footer that says "Other Webmaker Tools"?
- Or a more noticeable, differently-coloured footer that says "Looking for other Webmaker tools? Check out teach.mozilla.org/tools"

cc @xmatthewx @hannahkane @kevzawacki

(cross posted at https://github.com/mozilla/webmaker-browser/issues/170)

**Comment by KevZawacki** [comment]
Copy-wise I like: "Looking for other Webmaker tools? Check out teach.mozilla.org/tools." 

But for brand purposes, would suggest we tweak to: "Looking for Mozilla's Thimble and X-Ray Goggles tools? Check out teach.mozilla.org/tools."

**Comment by hannahkane** [comment]
+1 to @kevzawacki's brandtastic copy.

**Comment by HPaulJohnson** [comment]
+1 to @KevZawacki suggestion

**Comment by mmmavis** [comment]
could I get some design help from @vazquez / @xmatthewx on how this notice should look like?

**Comment by vazquez** [comment]
@mmmavis No problem :) Could I actually take this issue over? It's a nice coding break for me :)

**Comment by vazquez** [comment]
@KevZawacki What about dropping the "tools"?

Looking for Mozilla's Thimble and X-Ray Goggles? Check out teach.mozilla.org/tools.

**Comment by xmatthewx** [comment]
Great. Thanks @vazquez. Let's try two versions: a simple footer link like the others, and a notice down below. I'm a bit worried about pea soup with all the different elements floating around down there.

**Comment by KevZawacki** [comment]
+1 @vazquez, let's drop "tools."

**Comment by vazquez** [comment]
I have 3 options. Click on any of them to see the options full screen.

##### Inline 'Tools' Link

Using colour to accentuate the link from the rest.

![screenshot 2015-07-16 11 17 14](https://cloud.githubusercontent.com/assets/1119821/8727184/67dd8a76-2bac-11e5-9f2d-1ff820404ef2.png)

---

##### Tools Link with Bubble

Using a bubble to differentiate link. The only problem with this approach is the word. What one word could we put in this box? cc @KevZawacki 

![screenshot 2015-07-16 11 17 51](https://cloud.githubusercontent.com/assets/1119821/8727205/7eb1c186-2bac-11e5-9934-861f36565878.png)

---

##### Full length sentence

Using colour again to differentiate.

![screenshot 2015-07-16 11 18 14](https://cloud.githubusercontent.com/assets/1119821/8727252/b3d5eb9e-2bac-11e5-8200-54ff6e8c6ab1.png)

R? @xmatthewx @secretrobotron

**Comment by secretrobotron** [comment]
I like the bubble, but the full sentence has more relevant info for people. Only problem is that it's hard to spot (maybe because of the font colour?)

**Comment by KevZawacki** [comment]
I like the full sentence. 
Re: the bubble, I think it'll be difficult to communicate "find our legacy Webmaker tools here" in just a word or two.

**Comment by vazquez** [comment]
We can make it blue, the green was taken from the original Webmaker colour palette.

![screenshot 2015-07-16 11 55 06](https://cloud.githubusercontent.com/assets/1119821/8728146/8b1d0a02-2bb1-11e5-908d-ee6b324629df.png)

We can make it standard grey.

![screenshot 2015-07-16 11 53 52](https://cloud.githubusercontent.com/assets/1119821/8728138/847f68e8-2bb1-11e5-9757-4303051595bd.png)

Or a combo of both

![screenshot 2015-07-16 11 57 06](https://cloud.githubusercontent.com/assets/1119821/8728206/d1020a54-2bb1-11e5-936a-5c0bd2046eda.png)

**Comment by secretrobotron** [comment]
The last one makes the most sense to me. @xmatthewx ?

**Comment by HPaulJohnson** [comment]
+1 to the last one

**Comment by xmatthewx** [comment]
Going against the tide here. The full sentence breaks any sense of hierarchy in the footer. This and extraneous words make everything a bit harder to read. 

Let's try a modification on @vazquez's bubble. Use the tool names in a single bubble for maximum recognizability in minimum amount of space. (ignore my dashes)

Legal - Privacy - Donate - Contact - Twitter -  `Thimble & X-ray Goggles`

**Comment by vazquez** [comment]
This looks a lot better in my opinion:

![screenshot 2015-07-16 14 17 12](https://cloud.githubusercontent.com/assets/1119821/8731449/696fbc24-2bc5-11e5-9a27-2e9896c0f947.png)

I was pair designing with Jordan, and he mentioned taking off the slogan for a cleaner footer. An idea:

![screenshot 2015-07-16 14 18 43](https://cloud.githubusercontent.com/assets/1119821/8731482/a6143678-2bc5-11e5-8079-1c7e3d189809.png)

**Comment by secretrobotron** [comment]
:+1:

**Comment by xmatthewx** [comment]
I dig it. :+1: Slogan is strong above and expendable in the footer.

**Comment by secretrobotron** [comment]
@HPaulJohnson @KevZawacki ?

**Comment by HPaulJohnson** [comment]
works for me. ship it.

**Comment by vazquez** [comment]
Will begin coding it :floppy_disk:

**Comment by KevZawacki** [comment]
+1!

**Comment by mmmavis** [comment]
Awesome! @vazquez ping me if you need someone to review your PR :wink:

**Comment by vazquez** [comment]
Thanks @mmmavis Just assigned you :) https://github.com/mozilla/webmaker-browser/pull/176

**Comment by secretrobotron** [comment]
:fireworks:
