### ISSUE TITLE
Add GA tracking to browser player

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-core#313]

**Comment by gvn** [comment]
Can you elaborate on what we're trying to track here?

**Comment by gvn** [comment]
Can you elaborate on what we're trying to track here?

**Comment by xmatthewx** [comment]
I don't think we need anything complicated. 

Minimal:
- [ ] project views
- [ ] "open app" button

Maximal: 
- [ ] project "page" views or page nav events

**Comment by gvn** [comment]
@xmatthewx Ok, I was hoping after we re-scoped the sprint we weren't going to add more tickets. Can we put this as a "nice to have" or is it critical pre-snippet?

**Comment by xmatthewx** [comment]
Agreed. Keep your focus on the player. Feel free to assign to another pair hands if you see an opportunity.

**Comment by xmatthewx** [comment]
cc @thisandagain @adamlofting

**Comment by thisandagain** [comment]
We can get pretty decent coverage by simply implementing the GA polyfill in the `platform.js` file. I'll take this.

**Comment by xmatthewx** [comment]
WIP https://github.com/mozilla/webmaker-browser/pull/207

**Comment by k88hudson** [comment]
Resolved
