### ISSUE TITLE
Prep login/signup for new Terms agreement

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-core#316]
- Add "Mozilla Learning Networks" to bottom of signup/login pages
- Add age verification (see: https://accounts.firefox.com/signup)
- Clean up layout to ensure users can toggle easily between sign-up/sign-in

@vazquez - let's discuss details before you dive in

**Comment by k88hudson** [comment]
@xmatthewx who's on the hook to implement this?

**Comment by xmatthewx** [comment]
Nobody until conversation with legal, marketing, and teach team is finalized. I've let everyone know this could be a challenge to land, particularly with localization.

**Comment by xmatthewx** [comment]
Removing assignment from @vazquez while we wait for clarified requirements.

**Comment by xmatthewx** [comment]
tracking in #446
