### ISSUE TITLE
UI - Open in Webmaker banner

### ISSUE THREAD

**Issue by vazquez** [mozilla/webmaker-core#322]
Discussion is happening in https://github.com/mozilla/webmaker-browser/issues/62.

We need to design a generic "Open in Webmaker" notice and button when someone views a Webmaker project in the browser. 

_Scenario:_ Bobby texts Laura a link to her Webmaker project. Laura taps link. Laura will be directed to a web-browser player. The web-browser player will offer a slightly obtrusive notice asking Laura to "Open in Webmaker".
- If Laura has Webmaker App installed, the App will open when she taps the CTA.
- If Laura doesn't have Webmaker App installed, Android directs her to the Play Store.

**Comment by vazquez** [comment]
### Benchmarks

I took a look at how others are doing it now.

#### Instagram

Subtle bar on top. Non-dismissable.

![screenshot_2015-07-17-12-29-35](https://cloud.githubusercontent.com/assets/1119821/8754829/47a95ac6-2c94-11e5-9365-fb26411bdfeb.png)

---

#### Google Drive

Material Design modal. Dismissable.

![screenshot_2015-07-17-12-32-50](https://cloud.githubusercontent.com/assets/1119821/8754837/4dda9586-2c94-11e5-97b6-5dd02732657d.png)

---

#### Dropbox

Big CTA and notice. Dismissable.

![screenshot_2015-07-17-12-35-30](https://cloud.githubusercontent.com/assets/1119821/8754852/5d703e7e-2c94-11e5-9fc8-9e60a57734c1.png)

---

#### Pinterest

Interesting use of blue. Dischordant, but I think intentional. Copy works well. Non-dismissable.

![screenshot_2015-07-17-11-55-25](https://cloud.githubusercontent.com/assets/1119821/8754862/67cbed14-2c94-11e5-859a-413f1b99dc79.png)

**Comment by vazquez** [comment]
### Design

I have a couple of options, one more subtle than the other. Let me know what you think @xmatthewx 

![open app notice 2](https://cloud.githubusercontent.com/assets/1119821/8756152/0e96721e-2c9e-11e5-8c72-56c1b5b69fd7.png)

![open app notice 1](https://cloud.githubusercontent.com/assets/1119821/8756151/0e8bf01e-2c9e-11e5-9908-f5afbe8691cf.png)

**Comment by thisandagain** [comment]
:+1: on option B from my perspective. Thanks @vazquez !

**Comment by xmatthewx** [comment]
We should test a few copy alternatives and carefully localize this since it will impact conversions. @KevZawacki @secretrobotron 

@vazquez - let's look at this on big landscape screens and then hand it over to build.

**Comment by xmatthewx** [comment]
@vazquez @k88hudson 

If we don't have device detection, which I don't think we will for launch, this notice on desktop/tablet will be pretty annoying. Can we add a dismiss button on wide screens? 

Also, does the notice float over content or reduce the view size? Floating without dismiss could be a problem since we will launch initially with a Page viewer only, not a project view as in the comp.  

![tablet 9 landscape](https://cloud.githubusercontent.com/assets/1119821/8786050/ed221bd4-2ef9-11e5-8198-214e98dd37de.png)

**Comment by vazquez** [comment]
I think adding a dismiss button is no problem. What do you think @k88hudson?

I will update the comp to reflect page view, my bad.

**Comment by k88hudson** [comment]
Sure, go for it

**Comment by vazquez** [comment]
Design fixes have been addressed and updated in #359. Closing this issue.
