### ISSUE TITLE
Reported zoom problems

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker-core#331]
> Zoom (-) to view the maker did vanish project (Nexus 5). Unlimited view of the environment / edit project
> 
> To zoom out on the slides, the function of centralizing the slide does not work properly, only the slight movement. +1

Sounds like there are problems with zooming being locked to the middle of projects in play mode.

From https://etherpad.mozilla.org/webmaker-app-teste-fisl
cc @panaggio

**Comment by thisandagain** [comment]
This is prior to @k88hudson 's re-write of the zoom controls. Closing.
