### ISSUE TITLE
Can mistakenly "lock" zoom/pan

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker-core#332]
1. Pick a project with a bunch of pages (e.g. https://beta.webmaker.org/#/project?user=111027&project=1971).
2. Make sure you're not in zoomed-in mode.
3. Pinch-zoom out as far as you can (or at least make stuff pretty small).
4. Without letting go of your pinch-zoom, wiggle your hand around the screen to pan wildly.

Expected: unfettered wiggling
Actual: Unable to zoom/pan anymore. Need to double-tap a page or go back.

Note: These are only steps to reproduce consistently. It's possible to run into this bug without panning "wildly".

**Comment by thisandagain** [comment]
This was prior to @k88hudson 's re-write of the zoom controls. Closing.
