### ISSUE TITLE
Tinker mode slider view opens with old values

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker-core#334]
Found this while using tinker mode to change background colour of a button.
1. Open tinker mode.
2. Choose a colour in "pencil" view.
3. Go to "slider" view.

Expected: sliders to be set in accordance with currently selected colour.
Actual: sliders have values that were valid when tinker mode first opened.

**Comment by k88hudson** [comment]
I suspect this will be resolved/significantly changed after pomax's bulk patch lands, so i'm going to wait til that happens

**Comment by k88hudson** [comment]
This was resolved by the bulk patch
