### ISSUE TITLE
Can't add new pages to a project

### ISSUE THREAD

**Issue by gvn** [mozilla/webmaker-core#339]
**Repro Steps:**
1. Create project or edit existing project
2. Hit a "+" tile

**Expected:** A new page is added.
**Actual:** Nothing happens (console: `Uncaught TypeError: Cannot read property 'x' of undefined`)

**Comment by Pomax** [comment]
confirmed, seeing the same. Bisect will hopefully tell us which commit this went wrong in.

**Comment by gvn** [comment]
@Pomax is there a good article/doc on using bisect to find what commit introduced a regression? I've not used it before.

**Comment by Pomax** [comment]
probably in the git book, but it's a really simple procedure:

```
# be on your bad commit
> git bisect start
> git bisect bad
> git checkout some-commit-from-the-past
# test the code from this commit. if it's also busted in the same way:
> git bisect bad
# or, if it's just fine:
> git bisect good
```

The moment you have a pair of bad + good, git will automatically start jumping to new commits inside the bad/good range, and you then test to see if they have the problem you're trying to find or not. If they do, `git bisect bad`, if they don't `git bisect good`, and git will keep narrowing the possible range of commits that could be responsible based on your good/bad evaluation.

Eventually, you'll have a range that is basically {good}->{unknown}->{bad}, and when you claim bad or good on the last unknown commmit, git now knows where things started to go wrong and will tell you exactly which commit introduced the error you're trying to find.

You can find the offending commit out of a set of 1000 commits in about 10 checks at most this way, which is super helpful

**Comment by gvn** [comment]
Awesome, I'll add that to my toolbelt!
