### ISSUE TITLE
Button label resets to "Button link" after setting page destination

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker-core#349]
1. Add button
2. Change button label
3. Change button destination

Expected: Button retains label
Actual: Button label changes back to "Button link"

From https://etherpad.mozilla.org/webmaker-app-teste-fisl
cc @panaggio

**Comment by xmatthewx** [comment]
Might only happen with a certain order of events: https://github.com/mozilla/webmaker-core/issues/194

**Comment by secretrobotron** [comment]
Oh, almost certainly a dupe.

**Comment by gvn** [comment]
Possibly related to #372

**Comment by gvn** [comment]
I'm about 99% sure this is related to the caching issues @k88hudson is about to fix.

https://github.com/mozilla/api.webmaker.org/issues/134

**Comment by gvn** [comment]
This appears to be resolved on latest `develop`.
