### ISSUE TITLE
App not available for Galaxy Y

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker-core#350]
Can support for Galaxy Y be enabled?

cc @thisandagain

**Comment by thisandagain** [comment]
Which OS version?

**Comment by secretrobotron** [comment]
From https://etherpad.mozilla.org/webmaker-app-teste-fisl
cc @panaggio

**Comment by secretrobotron** [comment]
@panaggio able to find out?

**Comment by thisandagain** [comment]
The reason I ask is that I believe that phone is likely running Android 2.X which would be a `wontfix`.

**Comment by xmatthewx** [comment]
wontfix
