### ISSUE TITLE
Build - Open in Webmaker banner

### ISSUE THREAD

**Issue by vazquez** [mozilla/webmaker-core#359]
The design has been finalized and discussed with @k88hudson. Design issue is in #322.

We need to design a generic "Open in Webmaker" notice and button when someone views a Webmaker project in the browser.

Scenario: Bobby texts Laura a link to her Webmaker project. Laura taps link. Laura will be directed to a web-browser player. The web-browser player will offer a slightly obtrusive notice asking Laura to "Open in Webmaker".
- If Laura has Webmaker App installed, the App will open when she taps the CTA.
- If Laura doesn't have Webmaker App installed, Android directs her to the Play Store.
#### Final UI

![open app notice](https://cloud.githubusercontent.com/assets/1119821/8803897/7d41af48-2f97-11e5-9d53-1ed0d72e2120.png)

![tablet 9 landscape](https://cloud.githubusercontent.com/assets/1119821/8803898/7fe11748-2f97-11e5-8101-8ab0ac579dd0.png)
#### Red Lines

Available in the Sketch file as well.

![open app notice red lines](https://cloud.githubusercontent.com/assets/1119821/8803908/8972908e-2f97-11e5-8d45-d830b7621f52.png)

![tablet 9 landscape red lines](https://cloud.githubusercontent.com/assets/1119821/8803909/8af27d3e-2f97-11e5-9116-bfa1f14ff27c.png)
#### Google Drive

Sketch file available on Google Drive under **`webmaker-android/ Version 2.0/ Webmaker-Player-UI-2015-07-07.sketch`**

Close icon is available under **`webmaker-android/ Version 2.0 / icons / icon-close-notice-small.svg`** and **`icon-close-notice-large.svg`**

**Comment by xmatthewx** [comment]
Please see questions in https://github.com/mozilla/webmaker-core/issues/322#issuecomment-123036255 before proceeding with build.

**Comment by KevZawacki** [comment]
Per @xmatthewx's suggestion of trying different copy (https://github.com/mozilla/webmaker-core/issues/322): 

1) (colloquial) Try the Webmaker app! We think you'll like it better.
2) (performance) Try the Webmaker app for an even better webmaking experience
3) (value) Download the Webmaker app — it's fun and free

**Comment by k88hudson** [comment]
Resolved by https://github.com/mozilla/webmaker-browser/commit/9105b2c4024a2bf6d79b79ec67f34e5912773aa7
