### ISSUE TITLE
Release Engineering: Integrate NPM into grade build process

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker-core#365]
`npm run build` should be triggered prior to each build as to avoid developers / contributors needing to run the command manually.

**Comment by errietta** [comment]
closed per 14:02 < ryanw-se> Can someone please close tickets, #281, #182, #365
14:02 < ryanw-se> All of them contain fixes that were landed a short while ago, except for the style guide git hash, that was landed a few months
ago and got reopened when they migrated tickets
