### ISSUE TITLE
Start using semver per spec @ semver.org

### ISSUE THREAD

**Issue by gvn** [mozilla/webmaker-core#371]
We're using patch bumps where we should probably be using minor bumps (ie: adding functionality in a backwards-compatible manner).

EG: `1.0.2` should probably be `1.2.0` instead.

We're going to hit a hotfix situation sooner or later, which would be a patch bump...

Thoughts: @Pomax @thisandagain @k88hudson ?

**Comment by gvn** [comment]
Also, related: Are we going to start tagging `webmaker-android` and `webmaker-browser`? We could potentially tag core with our "official" release numbers (eg: 1.2.0) and then those platforms are just considered to be at whatever version of core they're using.

**Comment by gvn** [comment]
Related: #370

**Comment by thisandagain** [comment]
:+1:

**Comment by thisandagain** [comment]
Renamed milestones to reflect semver convention.

**Comment by gvn** [comment]
This is pretty well covered by our new release process draft and our recent versioning choices.
