### ISSUE TITLE
Deep linked API endpoint mismatch error case not handled in Android

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-core#376]
Current Android URLs include the path "project" instead of "player" and don't load in the browser. Browser URLs cannot be opened in Android.

Android Share:
- https://beta.webmaker.org/#/project?user=446905&project=4072

Browser Viewer:
- https://beta.webmaker.org/#/player?user=446905&project=4072

**Comment by xmatthewx** [comment]
For example, links on https://www.facebook.com/MozillaIndonesia don't properly render projects. 

cc @secretrobotron @gvn @k88hudson

**Comment by secretrobotron** [comment]
:+1: yes please.

**Comment by xmatthewx** [comment]
On the flip side, a browser-based URL with `player` path can't utilize the open app feature. The URL fails in Android without `project` path.

**Comment by k88hudson** [comment]
I think what is probably happening is that you're trying to access a project on the production api server (https://beta.webmaker.org/#/project?user=446905&project=4072) in an app that is configured with the staging api server.

Although this is a development edge-case, we should probably send along some data about what API endpoint the link is referring to, and show a message if the app/the link don't match

**Comment by gvn** [comment]
I think this will be resolved by https://github.com/mozilla/webmaker-browser/pull/204

**Comment by thisandagain** [comment]
@k88hudson has landed a patch for this. Needs to be deployed.

**Comment by k88hudson** [comment]
@thisandagain sure, sounds good

**Comment by k88hudson** [comment]
@thisandagain I've deployed to production, should be building now
