### ISSUE TITLE
Persist option to hide the "Get webmaker app" cta

### ISSUE THREAD

**Issue by k88hudson** [mozilla/webmaker-core#378]
We should consider hidding the cta for a period of time when people dismiss it via a cookie or localstorage.

Thoughts @xmatthewx @gvn @vazquez?

**Comment by gvn** [comment]
Another option should be "Hide Forever" IMO. There are people who will never get the app because they don't have Android, and this is quite annoying to them. Also, we should respect people who just want to use a browser instead of the native app. We're **Web**maker after all! :wink:

**Comment by xmatthewx** [comment]
Let's dismiss it and keep it hidden for a period of time. (2 months?) I believe that was always the plan, though we temporarily lost the dismiss button given limited UI real estate. 

Correct me if I'm mistaken @vazquez

**Comment by vazquez** [comment]
I agree @xmatthewx. We hadn't formalized the plan, but now we have! :smiley:
