### ISSUE TITLE
De-optimizely

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-core#380]
ALL the H1s have been replaced on beta.webmaker.org. Know anything about this @secretrobotron @alicoding ?

<img width="838" alt="screenshot 2015-07-22 09 45 40" src="https://cloud.githubusercontent.com/assets/53411/8826835/32d9b58e-3057-11e5-902c-ca103cb458d6.png">
<img width="842" alt="screenshot 2015-07-22 09 45 32" src="https://cloud.githubusercontent.com/assets/53411/8826836/32e57bf8-3057-11e5-9f81-60cfea79316c.png">

**Comment by secretrobotron** [comment]
Again? Paul and I tested this last night and it was fine.

@hpauljohnson can you pause the test again? Let's put it on staging server
instead to figure out what's wrong.

**Comment by HPaulJohnson** [comment]
Paused. 

However, I did quickly test everything again this morning before pausing (across FF, Chrome and Safari) and had no issues?

**Comment by secretrobotron** [comment]
We figured out a fix for this. @HPaulJohnson is going to make a new optimizely test with an "exact match" url (set to "simple match" right now, which captures every page, not just splash).

**Comment by thisandagain** [comment]
@HPaulJohnson Update?

**Comment by HPaulJohnson** [comment]
@secretrobotron and I tested the fix (noted above). Still need to setup a new round of tests leading up to marketing launch, which I'll do early this week.

**Comment by thisandagain** [comment]
Great! Thanks.

**Comment by HPaulJohnson** [comment]
New tests are now running. Please let me know if any further issues are experienced. Otherwise, think you can close this issue.

**Comment by thisandagain** [comment]
Wonderful! Thanks @HPaulJohnson ... LGTM.
