### ISSUE TITLE
QA Feedback - Safari iOS Player

### ISSUE THREAD

**Issue by vazquez** [mozilla/webmaker-core#388]
**OS and version**  Apple iPhone 6+ iOS 8.4
**Browser and version**  iOS Safari

**Which project are you testing?** 
- [x] How-to Draw: https://beta.webmaker.org/#/player?user=446905&project=4072
- [ ] Pokemon: https://beta.webmaker.org/#/player?user=426154&project=2926
- [ ] Bikes:  https://beta.webmaker.org/#/player?user=277436&project=2413
- [ ] Sketchbook: https://beta.webmaker.org/#/player?user=438321&project=2369

**Page**
- [ ] page is visible and centered :red_circle: 
- [ ] page elements appear with layout as expected :red_circle: 
- [x] elements are cropped and don’t extend beyond page edge

**Page navigation**
- [ ] neighboring pages are visible with minimal opacity :red_circle: 
- [x] navigation arrows are positioned correctly and point toward neighboring pages 
- [x] tap an arrow to navigate to a neighboring page
- [ ] the view transitions smoothly, then shows correct page, neighbors, and arrows :red_circle: 

**Button links**
- [x] find a page with button. tap it to navigate to another page
- [ ] page transitions smoothly with correct page, neighbors, and arrows :red_circle: 

**Header**
- [x] project title and author appears aligned left, truncated with ellipsis (...) if necessary
- [x] tap the Webmaker logo to visit the website

**Get the app**
- [x] "open app" notice appears
- [x] tap button to load play store page
- [ ] text is localized properly. I wasn't able to change the locale in Safari iOS. :/

Issues encountered:
- Major issues encountered with Safari. Page loads initially like this: 
  ![img_1923](https://cloud.githubusercontent.com/assets/1119821/8833317/d32d3e24-307b-11e5-97b5-4433e5e72828.PNG)

**Comment by xmatthewx** [comment]
@vazquez - you mentioned chrome a couple times above. Is that a copy-pasta error?

**Comment by vazquez** [comment]
Fixed! Thanks @xmatthewx
