### ISSUE TITLE
Incorrect Page layout on iOS

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-core#407]
Appears on 
- iOS Safari https://github.com/mozilla/webmaker-core/issues/388
- iOS Chrome https://github.com/mozilla/webmaker-core/issues/387
- OSX Safari (maybe related) https://github.com/mozilla/webmaker-core/issues/385

![img_1923](https://cloud.githubusercontent.com/assets/1119821/8833317/d32d3e24-307b-11e5-97b5-4433e5e72828.PNG)

**Comment by thisandagain** [comment]
Relates to #440

**Comment by gvn** [comment]
Tested on iOS Chrome + Safari and not seeing any of the layout issues. @xmatthewx can you still repro?

**Comment by xmatthewx** [comment]
@vazquez - please confirm if this is resolved.

**Comment by vazquez** [comment]
This is resolved!! 

![img_2031](https://cloud.githubusercontent.com/assets/1119821/9086268/77601a90-3b51-11e5-97ca-08bf813baf8b.jpg)
