### ISSUE TITLE
Incorrect layout of pages on Safari Mac

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-core#408]
Page and page neighbors all occupy the same position in the view. Page is small and does not fill the available space. QA details in #385

![screenshot 2015-07-22 12 28 42](https://cloud.githubusercontent.com/assets/1119821/8831651/be0cba4c-3071-11e5-9638-e4498cb5781e.png)

![screenshot 2015-07-22 12 28 27](https://cloud.githubusercontent.com/assets/1119821/8831469/78a3e346-3070-11e5-9f0b-cfa53ad13dd7.png).

**Comment by thisandagain** [comment]
Relates to #440

**Comment by gvn** [comment]
This appears to be fixed. Can you still repro @xmatthewx ?

**Comment by xmatthewx** [comment]
Looks good on my end. @vazquez reported it originally. I'll reassign to him to reconfirm or close.

**Comment by vazquez** [comment]
Yep, this is fixed as well. Closing
