### ISSUE TITLE
Odd "Open App" behavior in browser on Android 

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-core#409]
Firefox Beta 40 & Chrome 42
Android 5.0.2

STR:
- open https://webmaker-desktop-staging.herokuapp.com/#/player?user=1&project=1
- tap "open app"
- App opens (nightly) with error "project not found" [1]
- nav to Firefox
- Firefox displays the play store [2]

Note:
- [1] App can't handle URL with "player" instead of "project"
- [2] Redirect to play store shouldn't happen if app successfully launches

**Comment by thisandagain** [comment]
Tracking in #376
