### ISSUE TITLE
Include CC-by-SA in browser-based player

### ISSUE THREAD

**Issue by vazquez** [mozilla/webmaker-core#414]
[design issue was filed in https://github.com/mozilla/webmaker-browser/issues/114]
#### Requirements

We need to display a CC license when people view a project.

The CC license needs to display the following:
1. Name of the project
2. by username
3. CC License with a link to the **[creativecommons.org license](http://creativecommons.org/licenses/by-sa/4.0/)**

This CC license will display on mobile browser and web browser.
#### Design (Mobile Web)

![mobile - page view dark](https://cloud.githubusercontent.com/assets/1119821/9364923/c51b9486-467c-11e5-9c1b-7a598bbf52f6.png)
###### When the user taps on the CC icon, a modal appears:

![mobile - page view cc reveal](https://cloud.githubusercontent.com/assets/1119821/9364929/c87a11de-467c-11e5-9f56-33806d034a05.png)

---
#### Design (Web Browser)

![desktop - page view dark](https://cloud.githubusercontent.com/assets/1119821/9364934/ce35a070-467c-11e5-9714-624d4c6e7d6e.png)
###### When the user hovers on the CC icon, a modal appears:

![desktop - page view dark reveal](https://cloud.githubusercontent.com/assets/1119821/9364939/d1f76806-467c-11e5-8954-81a2849997a4.png)

---
#### Red Lines

Red Lines are meant to be used just as a guide to help the coding of these objects.

![mobile - page view dark red lines](https://cloud.githubusercontent.com/assets/1119821/9364970/e6a22e3a-467c-11e5-8993-f0f8acd454d4.png)  

![mobile - page view dark cc red lines](https://cloud.githubusercontent.com/assets/1119821/9364971/e8e8b9fc-467c-11e5-9095-eadff6ec5811.png)
#### Sketch file

Sketch file is available on Google Drive under **`webmaker-android > Version 2.0 > Webmaker-Player-UI-2015-07-27.sketch`**

The CC icon is available on Google Drive under **`webmaker-android > Version 2.0 > icons > cc-icon.svg`**

**Comment by vazquez** [comment]
Don't take on this issue yet, slight change of plans.

**Comment by vazquez** [comment]
~~This issue is now unblocked and good to take.~~ 

Issue is blocked, please do not assign until further notice.

**Comment by thisandagain** [comment]
@vazquez What's the blocker here? Legal review?

**Comment by vazquez** [comment]
The UI needs to be resolved in the Dark UI, as the CC logo goes hand in hand with the visual treatment. 

https://github.com/mozilla/webmaker-core/issues/418

**Comment by vazquez** [comment]
Notes from working with @cassiemc 
- Bottom left placement.
- Can we link to to original project?
- Work with title placement, "by" line

**Comment by xmatthewx** [comment]
> Can we link to to original project?

This will introduce more complexity. Let's get a basic CC in place first.

**Comment by vazquez** [comment]
:+1:

**Comment by vazquez** [comment]
Updated the designs above with the new UI work.

R? @cassiemc and @xmatthewx

**Comment by cassiemc** [comment]
R+ from me! Nice work @vazquez

**Comment by xmatthewx** [comment]
Excellent. @vazquez - mind filing a clean implementation issue and closing this? milestone 1.4

**Comment by vazquez** [comment]
Done!
