### ISSUE TITLE
Android App - Edit Project - Tapping an already-selected page shouldn't zoom it in.

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-core#421]
**Steps to reproduce**
- Open one of your own projects
- Tap any page to select it
- Tap it again
- **What happens** -  The view zooms in, and a small zoom out icon appears near the bottom of the view
- **What should happen** - Nothing!

We should really fix this quick, because it presents the page in a similar way to the "Page Edit" mode, without any of those capabilities.

**Comment by xmatthewx** [comment]
@k88hudson - can you help triage this? Let's discuss the work and risk involved and whether we can tackle it this week.

**Comment by Pomax** [comment]
this should be super quick to put in, since all the information needed to see if a page is already selected is already available and set correctly.

**Comment by Pomax** [comment]
PR up, but I do find that with this now turned off, I instinctively try to double tap pages to edit them (which doesn't work of course)

**Comment by xmatthewx** [comment]
Interesting considering #445
