### ISSUE TITLE
Android App - Edit Project - Image - Maximum image size is too small when image is first added (and related bug)

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-core#422]
**Steps to reproduce**
- Add an image
- Change it's source to be a camera photo
- When you go back to the page, the photo is almost as large as the page
- Now, try to pinch-scale it
- **What happens** - as soon you as you start scaling it, the image jumps to about 80% of it's original size, and you're not able to make it larger
- **What should happen** - the image should be freely scalable, to many times it's original size.

**Also** - if you leave the page and come back, you're able to make the image larger again.

**Comment by xmatthewx** [comment]
Is this resolved by @k88hudson's recent work on image size? Or related to it?
