### ISSUE TITLE
Problem signing up: invalid payload: lang

### ISSUE THREAD

**Issue by davidascher** [mozilla/webmaker-core#423]
Using nightly from mzl.la/webmaker-nightly, downloaded today, on Nexus 5.

![screenshot_2015-07-27-13-41-13](https://cloud.githubusercontent.com/assets/51278/8918096/cdab667c-346a-11e5-877a-db54de02e9d8.png)

**Comment by thisandagain** [comment]
@alicoding @k88hudson Any ideas?

**Comment by alicoding** [comment]
It looks like the server is not up-to-date here. Either id.webmaker.org is an older version of the app is not the latest because we have updated the payload to expect lang field there. It could also mean that the app is not sending the lang over.

Is this the latest nightly?

**Comment by thisandagain** [comment]
This is a release build for Google Play (http://mzl.la/webmaker-release). Do we need to push an update to id and login to production prior to release? If so, that needs to be documented.

/cc @jbuck @cadecairos

**Comment by alicoding** [comment]
My bad. Yeah @cadecairos made an update to id.webmaker.org so this needs to be match now.

**Comment by jbuck** [comment]
This is currently only broken on id.w.o staging and Webmaker nightly. The current patch in place needs to be redone, since any older client will fail to sign-up, since it's not sending the currently required lang attribute.

**Comment by thisandagain** [comment]
Patch is question is here (lang _must_ be optional as to support existing clients):
https://github.com/mozilla/id.webmaker.org/commit/171b7d38ad891fd044e250e1315407f3165cbf31
