### ISSUE TITLE
Android App - Edit Project - Text Element - Right-edge of text is cut off when text is set to Pacifico and Italics

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-core#424]
**Steps to reproduce**
- Add some text
- Change the font to Pacifico
- Change the style to Italics
- Observe the right edge of the text in both the Edit Element page preview and the Page itself
  - The right edge is slightly clipped.

![image](https://cloud.githubusercontent.com/assets/25212/8918149/20ac104c-346b-11e5-8c37-e048d0cfdfde.png)

**Comment by xmatthewx** [comment]
Interesting. Also, I love the overlay of transparent script by this font.
