### ISSUE TITLE
Android App - Project Editor - When you toggle between Play & Edit many times, it's hard to get back to the Make view.

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-core#428]
**Steps to reproduce**
- Open one of your own projects
- Toggle between Play and Edit a few times
- Now, attempt to go back to the Make view
- You'll probably try to do that via the "Back Arrow" in the header
- **Expectation** - When I hit the back arrow in the project editor, I go back to the Make view
- **What happens** - Ever time you hit the back arrow you just back in the history of your Play and Edit states, so you jump back and forth between the two, undoing the view history you were in slowly, then finally you get back to Make.

I know we're planning to Change this interaction, but it's worth calling out.

**Comment by xmatthewx** [comment]
Should be addressed by https://github.com/mozilla/webmaker-core/issues/37
