### ISSUE TITLE
Android App - Image Element - Unable to move an image more than 50% off of a page.

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-core#435]
**Steps to reproduce**
- Add an image
- Scale it up so it's roughly the size of the page
- Try to move it off of the page so that only the very edge of the image is visible
- You cant - movement is blocked as soon as you have about 50% of the image off of the page
- **Expected behaviour** - I should be able to move the image most of the way off the page, and be blocked only when I"m about to move it off the page entirely.

![image](https://cloud.githubusercontent.com/assets/25212/8963440/f98e81f0-35d4-11e5-94c0-0edd5302d81d.png)

**Comment by secretrobotron** [comment]
@thisandagain @xmatthewx seems like an easy fix for a benefit of easier content creation. Added to milestone just before snippet, but could be something we address in workweek after release.

**Comment by flukeout** [comment]
Otherwise.. how can we make more cool stuff like this..

![image](https://cloud.githubusercontent.com/assets/25212/8966548/ceb5f3ca-35e6-11e5-96c2-3e0cbade634d.png)

**Comment by k88hudson** [comment]
resolved by https://github.com/k88hudson/webmaker-core/commit/d6b8cdde789a67ffe189042806f1e151a80dc746

**Comment by flukeout** [comment]
ALL HAIL THE MIGHTY @k88hudson 
:crown: : :woman: 
:bow: :bow: :bow: :bow: :bow: :bow: :bow:

**Comment by xmatthewx** [comment]
:clap:        :clap:         :clap:

**Comment by k88hudson** [comment]
@flukeout we may need to adjust the threshold a bit to prevent things that are non-square from going off screen, but the bounds do respect the actual size of the element now
