### ISSUE TITLE
Update Terms of Service

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker-core#442]
Need to update TOS to reflect latest updates from legal.

/cc @HPaulJohnson

**Comment by xmatthewx** [comment]
Text: https://drive.google.com/a/mozilla.com/file/d/0B_MJiF6wUoWPaWotV2Y3RzM3V0xQZEtQMzNCbVE5OVpRYlhJ/view?usp=sharing

**Comment by xmatthewx** [comment]
closed by https://github.com/mozilla/webmaker-browser/pull/209
