### ISSUE TITLE
UX - age verification

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-core#446]
Design an age gate for Webmaker accounts. 
- https://accounts.firefox.com/signup
- http://skinnywhitegirl.com/blog/designing-for-coppa/1033/
- https://www.ftc.gov/tips-advice/business-center/guidance/complying-coppa-frequently-asked-questions

planning: https://github.com/MozillaFoundation/plan/issues/525

**Comment by xmatthewx** [comment]
### Current Firefox account form

<img width="362" alt="firefox-accounts-signup" src="https://cloud.githubusercontent.com/assets/53411/9095759/12b9ca74-3b87-11e5-9dd9-ae3aacec4400.png">

### Lesson learned

The Firefox accounts team learned that you shouldn't make people in their 20s feel old. Twitter storm! https://github.com/mozilla/fxa-content-server/issues/1085

<img width="750" alt="screenshot 2015-08-05 16 46 16" src="https://cloud.githubusercontent.com/assets/53411/9097430/91b6a19e-3b91-11e5-96e1-355a5e009b79.png">

### Tumblr does a nice 2-step

FF Accounts plans to A/B test something like this. https://github.com/mozilla/fxa-content-server/issues/2108

<img width="750" alt="firefox-accounts-signup" src="https://cloud.githubusercontent.com/assets/68213/6231057/3af98fc6-b692-11e4-8b6e-124c0348b9b6.gif">

**Comment by xmatthewx** [comment]
### Current UI and an Iteration

<img width="825" alt="screenshot 2015-08-05 16 57 58" src="https://cloud.githubusercontent.com/assets/53411/9097715/26d7d36e-3b93-11e5-9a05-0e1f6962649a.png">

### Two-step with verification

Second step would slide in like Tumblr above. 
- Single view with a single form. 
- Nothing is stored or submitted until step two is complete. 

<img width="809" alt="screenshot 2015-08-05 17 08 55" src="https://cloud.githubusercontent.com/assets/53411/9097917/ab839958-3b94-11e5-964c-31b410c5d85c.png">

**Comment by xmatthewx** [comment]
@vazquez - put a critical eye on the UX I've proposed. After, we can adjust UI and then share the design with legal for a review.

**Comment by cassiemc** [comment]
@xmatthewx can you add your designs to redpen please?

**Comment by vazquez** [comment]
### UX Ideation 1
- Username, email, password on first screen
- Using radio buttons to check for age on the second screen

![screenshot 2015-08-06 12 36 13](https://cloud.githubusercontent.com/assets/1119821/9117423/0d1ea092-3c38-11e5-931d-1e3479ec5aae.png)

**Comment by vazquez** [comment]
### UX Ideation 2
- Username and email on first screen
- Password and radio button age check on second screen

![screenshot 2015-08-06 12 41 50](https://cloud.githubusercontent.com/assets/1119821/9117489/84dbd8de-3c38-11e5-9d6b-02d4e06960c2.png)

**Comment by vazquez** [comment]
### UX Ideation 3
- Username and email on first screen
- Password and text-field age check on second screen

![screenshot 2015-08-06 12 43 40](https://cloud.githubusercontent.com/assets/1119821/9117522/dd62ba5e-3c38-11e5-9d4b-f3ea8a503ba0.png)

**Comment by cassiemc** [comment]
@vazquez 1 makes more sense to me than 2 (grouping username and password), but I prefer the input field of 3. I think you meant to put an age rather than a year, though. What does the 'fail' screen look like?

**Comment by cassiemc** [comment]
Was going to comment on @xmatthewx's designs that the Next and Join buttons seemed backward, though I understand why you'd put 'join' on the first screen to make it clear what you're signing up for. Maybe just weird to have 'next' on the second screen. Any reason why you couldn't make a title for the page that said 'Join' – since user orientation is one of the problems you're trying to fix? (and on the 'sign in' page, a big "Sign in" title – it's one of the fixes @alicoding and I talked about for desktop login but never got to) cc @vazquez

**Comment by vazquez** [comment]
@cassiemc -

_Re the text input for age:_ One of the things that @xmatthewx and I were talking about is giving a more passive date range indicator. As a privacy minded individual, one would be more likely to give out a date range rather than the exact year. This also makes the selection one tap away versus 6 taps if we use textfield. I agree that the textfield is more visually coherent, but I have a feeling that the radio buttons are the least frustrating path. Thoughts welcome.

_Re the Join Webmaker text:_ Yeah you're right. It feels weird to have the Next on the second screen. Tumblr shows a Next, but it still feels odd. I will work on this.

**Comment by vazquez** [comment]
This screen achieves better user orientation.
- Added big title at the top of the screen.
- Moved sign in link to the bottom of CTA. I will post benchmarks as to how this area is expected to have a sign in link.

<img width="299" alt="screenshot 2015-08-06 14 32 49" src="https://cloud.githubusercontent.com/assets/1119821/9120057/2fe625b8-3c48-11e5-8ffe-e9dc6467b7bd.png">

**Comment by cassiemc** [comment]
I thought it was the grouping with older ages that 30ish people were struggling with as per Madhava and RFeeley? Also, weren't we not allowed to ask for year someone was born? 

Like the new title+orientation better!

**Comment by vazquez** [comment]
@cassiemc - Ah I see what you mean now! That's my bad, I shouldn't have written "How old are you?", but instead "What year were you born?"

**Comment by vazquez** [comment]
### UX Ideation 4

![screenshot 2015-08-06 15 22 47](https://cloud.githubusercontent.com/assets/1119821/9121262/2e95fd58-3c4f-11e5-8f86-f2295f5af1a3.png)

**Comment by vazquez** [comment]
#### Ready for Legal Review

![screenshot 2015-08-07 11 18 50](https://cloud.githubusercontent.com/assets/1119821/9139115/1cb13f24-3cf6-11e5-96c4-f4afe7dc744d.png)

**Comment by vazquez** [comment]
### Draft for Review

<img width="1188" alt="screenshot 2015-08-07 13 33 23" src="https://cloud.githubusercontent.com/assets/1119821/9141745/e9fdde08-3d08-11e5-9cbd-40b35cd1176a.png">

**Comment by xmatthewx** [comment]
I received feedback from legal review. We're good with a small revision to button strings.
- 1st button : "Next" or "Start" or ??
- 2nd button : "Join Webmaker"

I worry that "Next" suggests a long process and will reduce conversions. But currently, if a user stops between steps they might wonder whether their info has been submitted or not. It hasn't, but it's ambiguous.

**Comment by vazquez** [comment]
I :eyes: the point.

Some ideas in addition to yours:
- Get started
- Start Creating Stories
- Ready, Set, Go!
- Start Exploring

**Comment by cassiemc** [comment]
- one more step...
- almost there...
- pick a username

etc.

**Comment by vazquez** [comment]
Updating UI. @xmatthewx and I had a conversation

One thing we learned from @thisandagain's work with Scratch/DIY work is that having non-standard elements reduces conversions. More informal words could open the door to some confusion. Even though Next or Start might not be ideal, at least those words might convert better.

#### Updating UI

![screenshot 2015-08-20 12 42 43](https://cloud.githubusercontent.com/assets/1119821/9389420/fe1323aa-4738-11e5-9727-446c07f2c99a.png)

**Comment by xmatthewx** [comment]
R+ !!

Let's annotate for build. Notes:
- No data should be sent or stored until step 2 is complete
- Build as a single view that replaces the form between steps one and two. System back should return from step 2 to 1. 
- Open the "not shared" tip on load. Close on field focus. 
- Anything else?

**Comment by xmatthewx** [comment]
For dev notes: 
- analytics on 2 steps will be important so that we know the impact of the age gate and can optimize
