### ISSUE TITLE
Add Open Graph tags to projects in browser viewer

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-core#453]
Add tags for better sharing. Include thumbnails. 

Originally discussed here: 
https://github.com/mozilla/webmaker-browser/issues/82

**Comment by thisandagain** [comment]
@errietta Would you be interested in hacking on this?

**Comment by errietta** [comment]
dibs

**Comment by errietta** [comment]
So, reading the linked issue, what was the final agreement? https://github.com/mozilla/webmaker-browser/issues/82#issuecomment-113592558 that?
cc @Pomax @k88hudson

**Comment by Pomax** [comment]
excellent question. @xmatthewx closed the issue, so I suspect he has the most complete information on that

**Comment by xmatthewx** [comment]
title: `project title` by `username`
image: `project thumbnail`

Agree with @Pomax that the project thumb is better than Webmaker logo, though logo is good fallback if thumb fails for some reason.

**Comment by Pomax** [comment]
OpenGraph allows multiple thumbs, so we can do project first, logo second, and then in places like Facebook people can cycle through the available OG images to post with the one they like best, with the project-relevant thumbnail as the initial (and thus default) image?

**Comment by xmatthewx** [comment]
perfect :+1:

**Comment by errietta** [comment]
@xmatthewx @k88hudson 

Matthew asked me to do a write up of what I want to do and run it by engineers before doing code :stuck_out_tongue: 

So this is what I'm thinking we should do.
We can get the user name and title by querying '/users/{user}/projects/{project}. This allows us to find the username (in project.author.username) and the project name in project.title.
To add open graph, we'll have to find some way to add additional meta tags src/html/index.html. I was thinking if there was a react module we could give a js object to and it'd convert it to opengraph meta tags for us that'd be ideal, or we could write one.

The other question is, where does the project thumbnail come from? Is it supposed to be generated on its own at some point? I don't see a way to set it within the app..
The project api call returns a thumbnail object but it's empty for my app.

**Comment by k88hudson** [comment]
Hey @errietta, this sounds good :) You should be able to get the thumbnail from the response in `/users/{user}/projects/{project}`; it is generated automatically when a project is created.

As for the react part, something like this might work https://github.com/nfl/react-helmet

**Comment by errietta** [comment]
@k88hudson is facebook actually able to parse the meta tags generated with react-helmet? I tried this on my build of the app, and although I could see meta tags generated with firefox dev tools, facebook didn't seem to pick them up. Can it understand meta tags generated on runtime with javascript?

**Comment by errietta** [comment]
I guess https://github.com/nfl/react-helmet#server-usage may help..

**Comment by Pomax** [comment]
no, the metadata needs to exist as the page is loaded in, for facebook to pick them up, so we can't really generate them "after the fact"

**Comment by xmatthewx** [comment]
Does that mean we can only include generic info that applies to all projects? :worried:

**Comment by errietta** [comment]
Unless we can costumise it on the server side.. haven't done enough digging
there yet, do you guys think that's doable?

**Comment by errietta** [comment]
https://github.com/mozilla/webmaker-browser/pull/219 is something that works, but is quite ugly..

**Comment by xmatthewx** [comment]
Looks like this is merged. Can we close this? Any related issues to file?

**Comment by errietta** [comment]
yes it's fine to close

**Comment by xmatthewx** [comment]
@k88hudson might have one follow up ticket

**Comment by k88hudson** [comment]
@xmatthewx i was wrong, we're all good!

**Comment by xmatthewx** [comment]
Yay. Thanks @errietta. Excited to see this put to use! :rocket:

**Comment by errietta** [comment]
:grinning:
