### ISSUE TITLE
Implement Dark UI on web-based Player

### ISSUE THREAD

**Issue by vazquez** [mozilla/webmaker-core#460]
**What:** We are changing the visual language of the web-based Player.
**Why:** More visual prominence increases page's focus on the page.
Design issue filed in #418 
## UI Changes

These changes affect web-based player for now.
1. In Player view, the background is now `#444444`
2.  Neighbours are now `10%` opacity instead of `7%`
3. Author (i.e. "by lukepacholski") has a `50%` opacity. Project title still displays at `100%` opacity.
4. The nubs have a different visual treatment. They are smaller and `#FFF` with a `70%` opacity. They also display a box-shadow.
5. The nubs display to the next to the page in focus.

![desktop - page view dark](https://cloud.githubusercontent.com/assets/1119821/9087343/0cabb3ce-3b58-11e5-94d8-1e2bb8cc4590.png)

---

The same changes apply to mobile view as well. However, there is one significant change in this new iteration of mobile view:
1. The page size has diminished to make room for nubs (specifically the left and right nubs). We have sacrificed page real estate but we feel this frames the page very nicely.

![mobile - page view dark](https://cloud.githubusercontent.com/assets/1119821/9087771/afbbb95e-3b5a-11e5-81c5-d0e03e3cc900.png)  

---

**Note:** Disregard the CC icon at the top right, that is out of scope for this issue.
#### Design Files and Resources
- Sketch file available here: https://drive.google.com/a/mozillafoundation.org/file/d/0ByIoeeW0a3R_VWtTZXFOY1kyZjg/view
- New nub icons available here: https://drive.google.com/open?id=0ByIoeeW0a3R_X1hzX1dqOUJaR2c

**Comment by xmatthewx** [comment]
closed by https://github.com/mozilla/webmaker-core/pull/509
