### ISSUE TITLE
Introduce Discovery section

### ISSUE THREAD

**Issue by vazquez** [mozilla/webmaker-core#462]
When the app loads, it sends the user to the Discovery section of the app. Upon first glance this can be overwhelming and confusing. @LauraReynal suggested to add a line or two of introductory content to make this transition easier.

**Comment by lauradereynal** [comment]
Im not sure that people are so confused by Webmaker and by the discovery gallery once they start scrolling, but the whole section does seem a little cold. I was thinking of a short catchy sentence to set the mood: 
Random ideas: 
- Discover stories from people all around the world (international)
- The best projects are featured below, Make your own !
- check out awesome projects from the community (community)

thoughts ?

**Comment by vazquez** [comment]
I like "Discover stories from people all around the world." I will run with that for now :) Thanks so much Laura!

**Comment by xmatthewx** [comment]
A few approaches to solve this problem:
- a welcome screen
- an element you can dismiss at the top of discover
- a "Welcome to Webmaker" project with an awesome thumbnail featured at the top of Discover

Which form solves our problem the best? Which is easiest to design and build?

**Comment by vazquez** [comment]
What about these two approaches?

#### Option 1: Inline Message
- Passive
- Could be easily ignored (con and pro)
- Some initial real-estate is lost (albeit small)

![discover view share 404 copy 4](https://cloud.githubusercontent.com/assets/1119821/9203541/ccd31594-4025-11e5-8a0e-87cfba56c56f.png)

---

#### Option 2: Introductory Screen
- Active
- Opportunity for playful microcopy
- Nice welcome to app
- Blocks view until user taps on button

![discover view copy 2](https://cloud.githubusercontent.com/assets/1119821/9203602/1cc2916a-4026-11e5-93fa-4182c6418476.png)

@LauraReynal @xmatthewx

**Comment by lauradereynal** [comment]
It would be interesting to try both, but for now I would go for option 1 to see what it changes.

**Comment by vazquez** [comment]
Talked to @xmatthewx, we will go for Option 1 (the simple message) for now.
- "Welcome to webmaker" as the H1

**Comment by vazquez** [comment]
Assigning to @xmatthewx to see if we should continue with Option 1.

**Comment by vazquez** [comment]
A new idea from @xmatthewx @cassiemc and I to introduce Discovery view AND Make view.
- On first load, screen fades in.
- On subsequent loads, screen will not show.
- This acts as a mini-FTU.
- We are using a new font (Sharpie) because Fira is not so welcoming in this context. We can get away with this for now by exporting as image for each locale (4). This is not so future proof, however. We might want to investigate some options here.

This is MVP. Further iterations to this could show some personality by animating in a little creature/mascot. Maybe the creature would wave at you and say "Have fun!" before the screen dismisses completely.

#### Option 1

![intro 1](https://cloud.githubusercontent.com/assets/1119821/9358228/e417f0c4-4658-11e5-904f-d2807c518338.png)

#### Option 2

![intro 1 copy](https://cloud.githubusercontent.com/assets/1119821/9358235/f28c178e-4658-11e5-9323-c2b3f512cab1.png)

#### Option 3

![intro 2](https://cloud.githubusercontent.com/assets/1119821/9334050/c493d178-459a-11e5-97ae-8bc3bd151c5d.png)

**Comment by lauradereynal** [comment]
Love this idea @vazquez It's brilliant
I think I have a preference towards colored gradient (navy blue?) as opposed to the white gradient, because it feels warmer and welcoming. 

Thanks for trying this :)

**Comment by cassiemc** [comment]
I don't have a strong opinion about the light vs. navy blues but do prefer the blues to the white. Originally I'd thought more contrast with the top bar would help the user understand where the buttons are (navy blue), but there is something nice about that medium blue feeling like a continuation of the top bar.

@vazquez and I did talk about probably needing another long-term solution regarding the font b/c: localization.

**Comment by vazquez** [comment]
Working on getting a more harmonious alignment. The text is now centered with the CTA underneath.

#### Blue Option

![intro 1 copy 3](https://cloud.githubusercontent.com/assets/1119821/9361053/b2f5794e-4667-11e5-94ae-ca4b81cfbc87.png)

#### Plum Option

![intro 1 copy](https://cloud.githubusercontent.com/assets/1119821/9361054/b2f63398-4667-11e5-8b1b-9014b1684151.png)

**Comment by vazquez** [comment]
I see your point cassiemc. The normal blue does lend itself more to the established UI. I also see the Plum as allowing the FTU message to be delivered more directly; I see the contrast as a healthy quality in this context.

**Comment by xmatthewx** [comment]
Nicely done. Alignment is looking better. I like the blues too. The contrast of the darker works well and also feels like a temporary mask over the content below. 

@lovegushwa might have some advice on handwritten fonts that support many languages/character sets. I wonder if we could localize the font in addition to the strings. @alicoding ?

**Comment by alicoding** [comment]
There are many nice font the way you have in the picture that's for sure but we could find some. Localizing font or switching is not really ideal though

**Comment by vazquez** [comment]
I already spoke to @lovegushwa during our dbuds session.

http://www.google.com/get/noto/ would be a good substitute for languages that are non-Latin based. Jordan has already used the font pairing between Fira and Noto in other Webmaker print material.

**Comment by vazquez** [comment]
I've reached out to @secretrobotron to help me coordinate in getting the text string translated.

https://github.com/mozilla/webmaker-launch/issues/100
https://github.com/mozilla/webmaker-launch/issues/101
https://github.com/mozilla/webmaker-launch/issues/102

**Comment by vazquez** [comment]
Some good progress!

![screenshot 2015-08-21 11 00 23](https://cloud.githubusercontent.com/assets/1119821/9411433/ed626910-47f3-11e5-8bc5-b23a7542efba.png)

**Comment by xmatthewx** [comment]
Good? I'd call it great. Any lingering concerns?

Let's file an implementation ticket. I'm curious whether we can localize font choice.

**Comment by secretrobotron** [comment]
@vazquez, can you drop the appropriate mock into each of those webmaker-launch tickets? Good to get review from those people since there are copy & paste errors sometimes (esp w/ Bangla).

_Done_
