### ISSUE TITLE
Create a Project button in Discovery view

### ISSUE THREAD

**Issue by vazquez** [mozilla/webmaker-core#463]
When the app loads, it sends the user to the Discovery view. There currently is no action to create a project. The user must navigate to the "Make" section of the app to access the creation button.  

I want to explore moving the button up one level and placing it on the Discovery view and test if this is a positive change for engagement.

**Comment by xmatthewx** [comment]
@LauraReynal - does this seem like a problem from your tests?

If so, is this a FTU problem? Or should we consider this in tandem with an update to the Android header? (`+` in the top corner?)

**Comment by lauradereynal** [comment]
I did not notice anything specific, users generally find the way to create pretty easily. 
However, I think @vazquez idea is great and we could test it if we have time !

**Comment by xmatthewx** [comment]
Closing this. Analytics don't show a significant portion of sessions leading to new projects.
