### ISSUE TITLE
Debug options aren't showing

### ISSUE THREAD

**Issue by ryanwarsaw** [mozilla/webmaker-core#468]
In debug builds, buttons to access things like the Style Guide, are supposed to appear at the bottom of the page in the make tab. These aren't appearing anymore, even though I'm building a project from Android Studio.

**Comment by Pomax** [comment]
@gvn @k88hudson would you know what might be going on there?

**Comment by gvn** [comment]
Not sure, but I've noticed this as well. I wonder if it's from the gradle refactor? cc @thisandagain

**Comment by gvn** [comment]
This should be fixed now. We had some display logic reversed...
