### ISSUE TITLE
Navigating pages in play mode is extremely frustrating

### ISSUE THREAD

**Issue by ryanwarsaw** [mozilla/webmaker-core#471]
There are half gray circles on each side of the screen that allow you to navigate up, down and left to right while in play mode. These are extremely tiny, very hard to use and are right up against your screen. Even more challenging if your using a phone case that borders the phone.

The bottom navigation arrow is way to close to the home button, I accidentally hit the home button on many occasions when I intended to go down to the next page. Swiping definitely feels normal and all places where I've tried to swipe, you haven't been able to.

**Comment by Pomax** [comment]
This is being redesigned. @vazquez @xmatthewx did we have an issue open that addresses this already?

**Comment by xmatthewx** [comment]
This is altered a bit in the new dark UI theme, though I'm not sure it addresses these concerns.

**Comment by vazquez** [comment]
Luke and I talked about tinkering with the tap targets of the arrows. Once Dark UI lands, we can make adjustments to the target size as we test it and play with the updated interface.

**Comment by ryanwarsaw** [comment]
Dupe of #1013
