### ISSUE TITLE
Add a way to directly edit HTML, CSS and possibly JS?

### ISSUE THREAD

**Issue by ryanwarsaw** [mozilla/webmaker-core#474]
If you look at the reviews for Webmaker a lot of people would like to directly edit things like the HTML and CSS and possibly even JS of their project. I think this would be a good idea, as people coming from other things Mozilla has created, like Thimble would expect at least some way of customizing their sites code.

**Comment by Pomax** [comment]
this is part of the long term plan. Closing this as "already covered by the battle plan": not closing this as "wontfix" =D

**Comment by ryanwarsaw** [comment]
Good to hear this is planned, I didn't see this mentioned anywhere so I figured it would be worth making a ticket for.
