### ISSUE TITLE
Options don't save unless you exit the page

### ISSUE THREAD

**Issue by ryanwarsaw** [mozilla/webmaker-core#478]
When I edit something, like the color or text of a button and lock my phone, unlock my phone and reopen the app from running processes, all of my edits revert back to default. My text isn't saved, my color isn't saved, nothing is saved. When you select an option, it should be saved. It shouldn't require you to leave the page in order to save these options.

**Comment by Pomax** [comment]
can you check whether this is still the case, we landed some code a few days ago that should have fixed that behaviour

**Comment by ryanwarsaw** [comment]
Will do.
