### ISSUE TITLE
Can't change font size

### ISSUE THREAD

**Issue by ryanwarsaw** [mozilla/webmaker-core#480]
I am not able to change the size of the font, when creating text for a page in my website. I should be able to change the size of the text.

**Comment by Pomax** [comment]
since you can scale the text, we did not add in explicit controls for "setting font size", perhaps that needs revisiting (tinker mode?)

**Comment by ryanwarsaw** [comment]
I wasn't even aware it was possible to scale the text, naturally I look for a dial to set the font size.

**Comment by xmatthewx** [comment]
We haven't seen this as a problem with user tests, though we can keep an eye out for it.
