### ISSUE TITLE
Ability to change background color & orientation

### ISSUE THREAD

**Issue by ryanwarsaw** [mozilla/webmaker-core#484]
It would be nice if you could change the background color of a page in your website. Currently your stuck with a whitish grayish background color. Your also stuck to portrait format, it would be nice if you could change this to be landscape as well.

**Comment by Pomax** [comment]
The app won't let you author or playback in landscape mode (all the design is based on portrait layouts) so this will require a significant amount of work if we decide we want this functionality.

**Comment by xmatthewx** [comment]
Background was in the plan #63, though the design would need an update to sync with the app's evolution. 

Orientation would introduce lots of complexity, both for users and for development. Some constraints (twitter's character count, instagram's proportions, a haiku's line lengths) help more than they hurt.

**Comment by lauradereynal** [comment]
What is the status for this ticket ? 

2 new users asked for this feature today

**Comment by xmatthewx** [comment]
We have updated UI, but need to weigh this against other features in the pipeline. I'm going to close this and track in #63.
