### ISSUE TITLE
Ability to set a custom project ID, as an alternative to numbers in links

### ISSUE THREAD

**Issue by ryanwarsaw** [mozilla/webmaker-core#486]
It would be cool if you could share links that looked more user friendly. Currently you're given a URL with user and project numbers, that you can't really identify what it is unless clicked on. My thoughts were to put a project id option in the project settings, that must be unique and will serve as an alternative to the numbers (used by default if you haven't provided a ID).

If I have user "ryanw-se" and a project called "squirrel-scramble", I should get a share URL like so, "https://beta.webmaker.org/users/ryanw-se/projects/squirrel-scramble". Multiple users could also have the ID squirrel scramble, but I can only have one of them.

**Comment by Pomax** [comment]
one thing to bear in mind though is that project names are not required to be unique, not even for a single user account (if you make two projects "my project", you can totally do that. Only the project id is required to be unique) so if you have multiple projects with the same name automatic vanity urls become a lot more tricky

**Comment by ryanwarsaw** [comment]
Going to rewrite this issue in a more articulate way, and also expand the track to all user/project related URLs.
