### ISSUE TITLE
Question: A/B test within app ??

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-core#489]
Are we able to use Optimizely within Webmaker? (Build in a default, queue up test if network is available.) Or is the notion plain crazy? It would be useful to avoid a major hit in conversion from our age gate on sign-up.

**Comment by adamlofting** [comment]
It's technically possible, but I think when @thisandagain tested it we found it added a lot of extra network traffic which we're trying to avoid if possible. https://github.com/mozilla/webmaker-android/issues/1601

As a fallback, we'll be able to compare sign-up rates pre and post age-gate [in GA](https://www.google.com/analytics/web/?hl=en#report/app-content-event-events/a49796218w86059054p97402987/%3Fexplorer-table.plotKeys%3D[]%26_r.drilldown%3Danalytics.eventCategory%3ALogin%2Canalytics.eventAction%3ASign%20Up%2Canalytics.eventLabel%3ASign%20Up%20Success/)

**Comment by xmatthewx** [comment]
Thanks. We could also test granular details in MLN sign-up flow, and bring the big winners into Android.
