### ISSUE TITLE
Remove Beta label from logo

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-core#493]
When the moment arrives, we'll remove the beta label from Webmaker. This needs to happen in the play store and in the app itself. 

@vazquez - can you link appropriate asset here? 

https://support.google.com/googleplay/android-developer/answer/1078870?hl=en

**Comment by vazquez** [comment]
Icon Accessible Here: https://drive.google.com/a/mozillafoundation.org/file/d/0ByIoeeW0a3R_RE9mb1lSNWg2VVU/view

**Comment by xmatthewx** [comment]
@KevZawacki @k88hudson - logo file above for use in app and in play store when moment arrives to remove the Beta label.

**Comment by xmatthewx** [comment]
Reassigning to @thisandagain given our current play store access

**Comment by thisandagain** [comment]
Done!
