### ISSUE TITLE
Build process

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-core#498]
discuss play store, pre-flight, build script, etc with @thisandagain

**Comment by xmatthewx** [comment]
@k88hudson - do you have all the info you need to continue with nightlies and future releases?

**Comment by k88hudson** [comment]
I think so, it would be helpful to have some notes from @thisandagain though if possible

**Comment by k88hudson** [comment]
Ok, @thisandagain is going to add to the wiki

**Comment by thisandagain** [comment]
Added to the wiki here:
https://github.com/mozilla/webmaker-core/wiki/Release-Process
