### ISSUE TITLE
Error messages should disappear when fixing name/pw

### ISSUE THREAD

**Issue by Pomax** [mozilla/webmaker-core#504]
The "There was a problem with your username or password" error that users get when trying to `sign in` with a bad user/pass combination does not disappear when a user changes their username or password values, persisting throughout the view until "sign in" is clicked.

**Comment by xmatthewx** [comment]
In most cases, error messages should appear onblur (#186), disappear when problem has been resolved.

**Comment by xmatthewx** [comment]
see #580 for related bits
