### ISSUE TITLE
I can save project titles that are longer than 25 bytes

### ISSUE THREAD

**Issue by Pomax** [mozilla/webmaker-core#507]
What exactly is the purpose of the character count if I can title a project with what is visually supposed to be an error? This is a confusing signal to me as user. Did I do something wrong? It looks like I did, but it doesn't matter? Why is the app yelling at me in red while still letting me go on?

**Comment by Pomax** [comment]
related to https://github.com/mozilla/webmaker-core/issues/508

**Comment by xmatthewx** [comment]
might be resolved.
