### ISSUE TITLE
having the app open for a while can crash android

### ISSUE THREAD

**Issue by Pomax** [mozilla/webmaker-core#510]
Not sure if this is due to debug build things, or whether the regular app also does this ...

**Comment by ryanwarsaw** [comment]
Can you check the system processes and see if this is a RAM leak? (It sounds like one).

**Comment by xmatthewx** [comment]
@Pomax - would you call this bug critical?

**Comment by Pomax** [comment]
if it's for debug only: no. If it also happens for the real app, then it might be

**Comment by thisandagain** [comment]
Testing now. I agree with @ryanw-se that it sounds like a memory leak.

**Comment by thisandagain** [comment]
Update: memory seems stable. I'm seeing a few leaks in the JS layer, but nothing major and nothing that occurs in the background / without user interaction.

**Comment by thisandagain** [comment]
Update: :laughing: that was quick. Got it to crash on the Walton Primo GF3 right after the last update. What's interesting is that it corresponded with Android Studio locking up. `adb logcat` doesn't reveal anything interesting:

``` bash
W/ActivityManager(  757): getRunningAppProcesses: caller 10081 does not hold REAL_GET_TASKS; limiting output
E/WifiStateMachine(  757): WifiStateMachine CMD_START_SCAN source -2 txSuccessRate=0.00 rxSuccessRate=0.00 targetRoamBSSID=ac:4b:c8:03:05:46 RSSI=-50
E/WifiStateMachine(  757): WifiStateMachine CMD_START_SCAN source -2 txSuccessRate=0.00 rxSuccessRate=0.00 targetRoamBSSID=ac:4b:c8:03:05:46 RSSI=-55
W/ActivityManager(  757): getRunningAppProcesses: caller 10081 does not hold REAL_GET_TASKS; limiting output
E/WifiStateMachine(  757): WifiStateMachine CMD_START_SCAN source -2 txSuccessRate=0.00 rxSuccessRate=0.00 targetRoamBSSID=ac:4b:c8:03:05:46 RSSI=-50
W/ActivityManager(  757): getRunningAppProcesses: caller 10081 does not hold REAL_GET_TASKS; limiting output
E/WifiStateMachine(  757): WifiStateMachine CMD_START_SCAN source -2 txSuccessRate=0.00 rxSuccessRate=0.00 targetRoamBSSID=ac:4b:c8:03:05:46 RSSI=-52
E/WifiStateMachine(  757): WifiStateMachine CMD_START_SCAN source -2 txSuccessRate=0.00 rxSuccessRate=0.00 targetRoamBSSID=ac:4b:c8:03:05:46 RSSI=-50
W/ActivityManager(  757): getRunningAppProcesses: caller 10081 does not hold REAL_GET_TASKS; limiting output
E/WifiStateMachine(  757): WifiStateMachine CMD_START_SCAN source -2 txSuccessRate=0.00 rxSuccessRate=0.00 targetRoamBSSID=ac:4b:c8:03:05:46 RSSI=-49
```

**Comment by thisandagain** [comment]
Ok. I haven't been able to replicate on `release`. I believe this may be related specifically to ADB / Android Studio. Needs further investigation but not a blocker for 1.2.0.

**Comment by Pomax** [comment]
could be all the debug injections never getting cleaned out...?

**Comment by ryanwarsaw** [comment]
I ended up discovering what was causing this, you can read more here https://github.com/ryanw-se/android-url-router/issues/13. Looking to get a fix out by 1.6 or at the latest, beta 1.7.

**Comment by ryanwarsaw** [comment]
Starting work on this today! :train:

**Comment by xmatthewx** [comment]
tracking this work in #780. correct? closing.
