### ISSUE TITLE
Tutorial Mode

### ISSUE THREAD

**Issue by ryanwarsaw** [mozilla/webmaker-core#511]
I noticed in a lot of the tickets I filed, there were features available to change most things, but I didn't know about them or how to use them. It would be neat to see something that can walk you through different features for a function, possibly a help menu that covers things like buttons, etc?

**Comment by xmatthewx** [comment]
How about a demo project? We could pre-populate new accounts with a demo project that includes content that describes what you can do. @flukeout @vazquez

**Comment by flukeout** [comment]
Would this be the kinds of things that we'll cover in the first time use popups? We did have an rough mockup of a tutorial project already.

We could have the tutorial project be the first and only thing you can open when you start maybe, and once you leave it you'll have access to the full discover and make modes.

**Comment by xmatthewx** [comment]
We could, or we could skip the FTU intro screens and give people two options on launch: try it out and see what other people made. Try it out would load an iteration on your demo project. cc @vazquez

**Comment by ryanwarsaw** [comment]
Now that we have FTU models, this isn't that big of an issue (Closing).
