### ISSUE TITLE
password reset via email directs to id.wmo, which then directs to webmaker://login?mode=sign-in

### ISSUE THREAD

**Issue by Pomax** [mozilla/webmaker-core#513]
That URL does not work on desktop. And never will. Is there a way for id.wmo to detect whether or not that URL even makes sense and not redirect if we're on desktop @cadecairos @jbuck?

**Comment by cadecairos** [comment]
Is there a reliable way to detect if the browser is running on android?

**Comment by cadecairos** [comment]
should we move this issue to id.webmaker.org?

**Comment by Pomax** [comment]
might make more sense there, yeah.

**Comment by Pomax** [comment]
filed as https://github.com/mozilla/id.webmaker.org/issues/359
