### ISSUE TITLE
"Error loading projects" error on first visit to Make page with new account.

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-core#518]
**Steps to reproduce**
- Install latest nightly app 
- Create a new account
- Go to Make view
- I see the following error...

![image](https://cloud.githubusercontent.com/assets/25212/9238084/7ee2f2ac-4104-11e5-8221-ab5d2154dbb2.png)

Eventually it goes away - but I can make it show again if i pull-to-refresh that page.

**Comment by xmatthewx** [comment]
Might be due to staging vs prod database. cc @k88hudson @Pomax

**Comment by flukeout** [comment]
Note - this account doesn't have any projects associated with it, so it's not like it's trying to load projects that actually exist.

**Comment by Pomax** [comment]
whether there are any projects or not doesn't really matter, since it's contacting the database for "all projects associated with a userid"... I did not see this happen yesterday when doing the whole "making new user accounts".

**Comment by k88hudson** [comment]
Ok, this is happening because after first creating a user account, the new user id is not yet in the api.webmaker.org database (since no projects have been created yet), so the response is `404 User not found`

**Comment by thisandagain** [comment]
Resolved in #531
