### ISSUE TITLE
Button appears differently between page and edit element page preview.

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-core#519]
**Steps to reproduce**
- Add a button
- Look at it
- Edit the button
- Look at the preview of the button
- The preview is missing the lighter edge on the top of the button 
- The preview has a drop shadow that the page on the button doesn't have

**Comment by xmatthewx** [comment]
New style introduced by @vazquez in https://github.com/mozilla/webmaker-core/commit/947e41a67e362b5e56e1b01b2dd63ffdeb092873

**Comment by xmatthewx** [comment]
:dancer: :dancers:
