### ISSUE TITLE
When I add an element to a page, it's not auto-selected.

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-core#520]
Just-added elements should be selected so that they can be acted upon more quickly!

**Comment by xmatthewx** [comment]
Very important since selected state reveals edit UI.

**Comment by xmatthewx** [comment]
Or maybe they're selected without indicator: https://github.com/mozilla/webmaker-core/issues/543

**Comment by flukeout** [comment]
@xmatthewx you're correct - this is a dupe of #543, closing.
