### ISSUE TITLE
Back button in page view doesn't return me to the aerial/map view.

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-core#523]
The back arrow in the header on the Page view acts as a "previous view" button instead of a "zoom out" button, which is what it was designed to be.

**Steps to reproduce**
- Create a project with two pages
- Add a button on one page that links to the other page
- Click "follow link" on the button to go to the second page
- You'll go to the second page
- Tap the "Back" icon in the header
- You will return to the previous page with the button

...but you should return to the map view.

**Comment by Pomax** [comment]
hm, why should you go back to the map view? You were on a page before, that's where you should be going based on your page navigation?

**Comment by flukeout** [comment]
Because there is no other way to get to the map view and that's what the back arrow was designed to bring you back to. 

I don't mind some way to navigate back to previews views, we could spec that out, but it would have to be in addition to a way to zoom back out.

**Comment by Pomax** [comment]
the reason it takes you back to the previous page is that we literally tell the WebView system to "go back one step in the views history", so if we need it to go to project, bypassing part of the history, that is actually a significant change that I suspect we can't land before snippet.

**Comment by xmatthewx** [comment]
We need a comprehensive review of the header, nav, and back button given how the app has evolved since the original spec and the challenges of working with the android header. Tracking here: https://github.com/mozilla/webmaker-core/issues/46
