### ISSUE TITLE
Button disappears with this one special trick

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-core#524]
Steps to reproduce
- Add a button
- Set the button's destination to the same page you're currently on
- Tap "Follow Link" on the button
- You go to the same page but...

THE BUTTON IS GONE!

It's actually there if you leave and come back to the page.

**Comment by Pomax** [comment]
hm, "follow link" might be a view change, which means we're leaving the page without having technically saved it or cached its content. Does it make sense to let people hit "follow link" while you're editing the content of the page, rather than in play more only? /cc @gvn @vazquez @xmatthewx

**Comment by xmatthewx** [comment]
Origin page should be locked and not available for set destination.

**Comment by xmatthewx** [comment]
Fixed by https://github.com/mozilla/webmaker-core/pull/544
