### ISSUE TITLE
Set Link destination URL edition

### ISSUE THREAD

**Issue by toolness** [mozilla/webmaker-core#53]
This issue has been migrated from mozilla/webmaker-android#1671.

It was originally written by [xmatthewx](https://api.github.com/users/xmatthewx) on Wed May 06 2015 and had the following description:

> Tinker mode for links includes the option to set a URL. 
> 1. In link element editor, user taps 'set destination'
> 2. In map page picker, user taps 'tinker bolt'
> 3. Dialog appears, offering to set destination:
>    - page in another project
>    - web url
> 4. User taps web url
> 5. View appears with field to set destination. View includes some helpful info about URLs and links.
> 6. User taps checkmark
> 7. Return to element editor
> 
> WIP UI in mozilla/webmaker-android#1549 

On Wed May 06 2015, [xmatthewx](https://api.github.com/users/xmatthewx) commented:

> Nice to have: include a way to access browser's bookmarks or top sites. **@****flukeout** will see if there's any good precedent for this on Android. Likely out of scope for v1. 

On Thu May 07 2015, [xmatthewx](https://api.github.com/users/xmatthewx) commented:

> Context: User taps `set destination` in the link editor and then `tinker` :zap:  in the page picker. See mozilla/webmaker-android#1670 more info.
> ## Tinker Mode
> - User taps :zap: 
> - Dialog appears. User can:
>   - link to page in another project (#1672)
>   - link to URL
>   - tap outside dialog to dismiss
>   - tap android back to dismiss
> 
> ![button power link](https://cloud.githubusercontent.com/assets/1119821/7505408/04a5093e-f407-11e4-9f31-ee07b0355844.png)
> ## Set URL
> - User taps Web in dialog
> - Show URL settings view
> - User enters URL
>   - If invalid, tap checkmark reveals helpful notice (TBD)
>   - If valid, tap checkmark confirms
> - Go to element editor
> 
> ![button link to web](https://cloud.githubusercontent.com/assets/1119821/7638033/134831c0-fa40-11e4-9201-c8f613187e8e.png)

On Thu May 14 2015, [xmatthewx](https://api.github.com/users/xmatthewx) commented:

> Note: header should match tinker colors. If that's not possible, we will need to revisit how we identify that a view is a tinker view.

**Comment by xmatthewx** [comment]
@vazquez - let's revisit this, considering https://github.com/mozilla/webmaker-core/issues/567. I'm wondering if the order of events should be: 
- tap add link
- see modal for context
- choose Page or URL
- set destination

While a like the tinker bolt on the set destination view, we can make this more clear.

**Comment by vazquez** [comment]
A more refined UX based on @xmatthewx's comment.

![set link destination refined ux](https://cloud.githubusercontent.com/assets/1119821/9664815/33a347d2-523a-11e5-9b8b-673bce30e59d.png)

**Comment by xmatthewx** [comment]
Great. The modal should offer a page in _this_ project first. Let's leave off "another project" until we're ready to implement that. New copy:

> Link your button to another page or to a destination on the web. 
> - Page
> - Web URL

**Comment by vazquez** [comment]
Final R? @xmatthewx. Ready for implementation ticket?

![set link destination refined ux](https://cloud.githubusercontent.com/assets/1119821/9739598/8b9e5bd8-561e-11e5-8aec-c008fae67b68.png)

**Comment by xmatthewx** [comment]
R+

This should be implemented in tandem with the reduce steps https://github.com/mozilla/webmaker-core/issues/567 ticket. Let's file a new ticket and flag @k88hudson.

**Comment by vazquez** [comment]
Created new ticket (#643), flagged @k88hudson.
