### ISSUE TITLE
Ryan's QA List

### ISSUE THREAD

**Issue by vazquez** [mozilla/webmaker-core#536]
In order to close this bug, go through the follow scripts:

[Button Element](https://github.com/mozilla/webmaker-core/issues/401)
[Text Element](https://github.com/mozilla/webmaker-core/issues/400)

File any bugs as separate tickets, just remember to assign the QA label to the issue so it can get triaged accordingly.

Other tasks that you could tackle are in the [wiki](https://github.com/mozilla/webmaker-core/wiki/QA-Script-Sample-Issues) .

Thanks for helping out Ryan!

![](http://media.giphy.com/media/12nuDeDV4xU3yE/giphy.gif)

**Comment by vazquez** [comment]
@ryanw-se This is your QA list!

**Comment by xmatthewx** [comment]
:ship: has sailed :)
