### ISSUE TITLE
Set destinations position above or below the button, relative to its position

### ISSUE THREAD

**Issue by ryanwarsaw** [mozilla/webmaker-core#538]
When I put the button really close to the bottom of the page, the set destination button is cut off and I am not able to set the position of the button. If I am close to the bottom of the page, set destination should be on top of the button, so I can clearly see it and tap on it.

**Comment by xmatthewx** [comment]
:+1:  This is something we will need to do if we don't change the way these buttons and helper buttons function.

**Comment by ryanwarsaw** [comment]
Fixed in latest `1.6.2` staging builds.
