### ISSUE TITLE
No set title confirmation button

### ISSUE THREAD

**Issue by ryanwarsaw** [mozilla/webmaker-core#539]
When you change the title of your project, from the default text "My Project", a keyboard pops up and you type what you want in. There is no button on the screen that says "Done" or "Save", so logically you just close the keyboard out and exit the screen assuming it'll save your title.

We should reassure the user that their typing was saved and they should know so by having a button confirmation that they can press, it would also close the keyboard.

**Comment by xmatthewx** [comment]
@ryanw-se -  In our app, we intend to display the title in the header, which would reassure you that your edit was a success (#285). In Google's Material Design, settings are updated with a simple exit of the view.
