### ISSUE TITLE
Project Settings page throws script errors

### ISSUE THREAD

**Issue by cadecairos** [mozilla/webmaker-core#542]
```
Uncaught ReferenceError: Could not find Intl message: badTitle
ReactCompositeComponent.js?cd59*****:723 Uncaught TypeError: Cannot read property '_currentElement' of null
```

STR: 
1. Open a project from the Make tab
2. press the three dots button, select settings

Expected: Settings tab should load
Actual: blank page, frozen app. Must force close to fix it. console errors above.

**Comment by xmatthewx** [comment]
Is this just on develop/staging? Related to style guide button? If not, sounds critical. @k88hudson @thisandagain

**Comment by cadecairos** [comment]
I just downloaded the nightly  from mzl.la/webmaker-nightly

**Comment by thisandagain** [comment]
Confirmed in RC. Needs to be resolved prior to ship. @k88hudson can you take this?

**Comment by k88hudson** [comment]
When testing current master, I can't reproduce this; I am pretty sure this is a result of a proper rebuild not being run (so new locale files weren't generated) since `badTitle` was added very recently. Thoughts @thisandagain?

**Comment by thisandagain** [comment]
I just did another fresh install / build. Perhaps some kind of merge issue? Hmm.

**Comment by thisandagain** [comment]
Confirmed as a build issue. Closing.
