### ISSUE TITLE
New elements are selected, but don't have selection box

### ISSUE THREAD

**Issue by cadecairos** [mozilla/webmaker-core#543]
STR:
1. Create a new element!

If you look close, you'll see that the buttons indicate the element is selected, but the blue dotted selection box doesn't show until you interact with the element.

Not sure how critical this is, since it's just a visual bug.

@thisandagain / @xmatthewx

**Comment by xmatthewx** [comment]
Interesting. That's better than not selected at all as previously reported: https://github.com/mozilla/webmaker-core/issues/520

**Comment by cadecairos** [comment]
![screenshot from 2015-08-14 15-37-39](https://cloud.githubusercontent.com/assets/438003/9282441/6d39c12e-429a-11e5-9186-9dce1fc02a18.png)

Screenshot right after adding the text - the buttons at the bottom indicate the element is indeed selected, but it's not visibly showing it.

**Comment by k88hudson** [comment]
Resolved by https://github.com/k88hudson/webmaker-core/commit/f0673a1119ad9156311ccdc28d26685b40e5ee37
