### ISSUE TITLE
Can't make a remix

### ISSUE THREAD

**Issue by gvn** [mozilla/webmaker-core#547]
Repro (using nightly: http://mzl.la/webmaker-nightly):
- Create a new account
- Open "First Aider Guide" from Discover tab
- Hit kebab and hit "Remix"
- Hit "Ok got it"
- Hit back until you get back to Discover view
- Hit Make tab

Expected: See remixed project in list
Actual: Empty project list

**Comment by thisandagain** [comment]
If you pull to refresh what is the result?

**Comment by gvn** [comment]
If I follow the STR only (IE: have no projects and a totally fresh acct) then I don't see anything after a pull to refresh.

**Comment by jbuck** [comment]
@gvn I believe https://github.com/mozilla/api.webmaker.org/pull/163 will fix this

**Comment by jbuck** [comment]
@gvn and @k88hudson report that this is now fixed on staging, so pushing it up to production!

**Comment by k88hudson** [comment]
thanks @jbuck

**Comment by gvn** [comment]
Yes thank you!
