### ISSUE TITLE
Add Text background color option

### ISSUE THREAD

**Issue by toolness** [mozilla/webmaker-core#55]
This issue has been migrated from mozilla/webmaker-android#1674.

It was originally written by [xmatthewx](https://api.github.com/users/xmatthewx) on Wed May 06 2015 and had the following description:

> Text on photos is tricky. I think we should add an option for background color on text. It will greatly increase what you can make with this app while we don't have shapes and stickers. 
> 
> Requirements:
> - ~~toggle on/off~~ palette with none option
> - standard tinker
> 
> Thoughts?
> 
> cc **@****thisandagain** **@****flukeout** **@****vazquez** 

On Wed May 06 2015, [flukeout](https://api.github.com/users/flukeout) commented:

> +1 on this idea, and the color bar that **@****vazquez** spec'd already has it:
> ![image](https://cloud.githubusercontent.com/assets/25212/7500435/80330a12-f3e2-11e4-82b2-aad66946ee9a.png)

On Wed May 06 2015, [thisandagain](https://api.github.com/users/thisandagain) commented:

> :+1: Sounds like a good idea but we need to remove features from the critical path to v1 right now. Moving to backlog.

**Comment by xmatthewx** [comment]
@alanmoo - this essentially the same thing as what you just landed. Different element, different attribute, same logic.

**Comment by alanmoo** [comment]
Great. I was thinking it was more of a text outline but if it's a solid field, this _should_ be quick.

**Comment by alanmoo** [comment]
@vazquez I'll put this below text color, but above background color?

**Comment by vazquez** [comment]
That's exactly right :hand:

**Comment by xmatthewx** [comment]
Ah. I see the source of confusion.\* To clarify: this will set `background-color` on the the p text element. The UI control should be labeled "Background" ... it will come after "Color" and before "Text Style" in the editor. 
- Screenshot at top was just to show that we already had a component for setting color. Border is not relevant here.

**Comment by alanmoo** [comment]
Just so we're consistent on i18n, I want to point out that I added "Text Color" in #696, as I felt it was confusing to have something plainly labeled "Color" (even though that's the CSS style we're targeting). Should I change that to "Color" or use "Text Color" here? (I'd vote keeping "text for clarity" but I don't care too much either way).

**Comment by xmatthewx** [comment]
@alanmoo - interesting thoughts. Let's stick with what we have for now since user tests haven't revealed a problem with that. I think the context is strong since you've just tapped to edit the text element.

**Comment by vazquez** [comment]
:+1:

**Comment by alanmoo** [comment]
Ok, I'll add in "Color" to the `en-US.yaml` file as a separate entry (it was hard coded in the markup previously). Should I change the label in #696 back to "Color" as well, instead of "Text Color" @xmatthewx?

**Comment by xmatthewx** [comment]
Yes, that'd be good.

**Comment by alanmoo** [comment]
@xmatthewx I created the PR, though I notice you asked for "Background" as the UI control, where it was "Background Color" in the link editor. Right now the PR has "Background Color", again for consistency. Thoughts?

**Comment by vazquez** [comment]
Let's go for:

`Color`: Label for modifying text colour.
`Background`: Label for modifying background colour.

**Comment by alanmoo** [comment]
Great. Just to tie this in with #611, what should the default colors be for text? Right now I have
![text colors](https://cloud.githubusercontent.com/assets/1682681/10370515/401ea75c-6dad-11e5-96fe-d60c9436c974.png)

**Comment by vazquez** [comment]
Those values are right on the money for text strings. Text can have a transparent background (which is essentially no background).
