### ISSUE TITLE
Can't edit middle of text, without being forwarded to the last character

### ISSUE THREAD

**Issue by ryanwarsaw** [mozilla/webmaker-core#550]
If you have a title that you want to edit, say you want to remove some a capital letter from the middle of your title, you can't do so without deleting the title to that point and re typing it. I should be able to tap where I want my cursor to start and simply replace that one character.

**Comment by Pomax** [comment]
If I tap a text, then tap it again to put the cursor somewhere in the middle (standard Android interaction model), I can edit/insert just fine. Can you list the steps you're following that makes the text get wiped entirely?

**Comment by ryanwarsaw** [comment]
Unable to replicate this in latest `1.6.2` staging build.
