### ISSUE TITLE
Link from Player to App broken in FF

### ISSUE THREAD

**Issue by adamlofting** [mozilla/webmaker-core#554]
Looking at this project in FF Release Channel (40.0)

<img width="1436" alt="screenshot 2015-08-18 13 27 44" src="https://cloud.githubusercontent.com/assets/1901816/9329868/18006652-45ad-11e5-8099-869fabc1f48c.png">

I get the message: 'Use the Webmaker App! We think you'll like it better.' and a button 'Open app'.

Two issues for me:
1. If you arrived on this project without knowing what Webmaker is, that CTA doesn't make much sense.
2. Clicking 'Open App' attempts to follow a deeplink which doesn't work on a Desktop browser

<img width="1367" alt="screenshot 2015-08-18 13 27 55" src="https://cloud.githubusercontent.com/assets/1901816/9329881/341ebc9e-45ad-11e5-95ad-d6fe862cc9a7.png">

**Comment by xmatthewx** [comment]
@k88hudson - mind taking a look at this?

**Comment by k88hudson** [comment]
Resolved
