### ISSUE TITLE
Thumbnails not generated

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-core#556]
Can others confirm this? cc @secretrobotron @k88hudson 

STR - new thumb
- create a new project
- add content on first page
- exit page, see it update in project view
- exit project
- refresh Make view
- no thumb
- delete and reinstall app
- login and got Make view
- no thumb

STR - updated thumb
- edit a project
- add or edit content on page that generated previous thumb
- exit page, see it update in project view
- exit project
- refresh Make view
- thumb remains the same

**Comment by cadecairos** [comment]
Could be that the server cache isn't being busted when a thumbnail created

**Comment by xmatthewx** [comment]
Ok. I'm calling this critical. Let's team up to figure this out. cc @Pomax @gvn

**Comment by gvn** [comment]
Confirmed. Worse, the project just _disappeared_ for me after I pulled to refresh.

STR:
1. download fresh copy of app from Play store
2. create a new account
3. create a new project
4. add content on first page
5. exit page, see it update in project view
6. exit project (i see a generic thumbnail here)
7. refresh Make view

**Comment by Pomax** [comment]
fresh install
- sign in
- create new project
- add text and image element on page 1
- back to project, page shows updated
- back to makes list, project is listed
- no thumbnail is visible

unlike @gvn, however:
- refresh makes list 
- project still shows up
- still no thumbnail

@cadecairos is there a way for us to see whether cache-invalidating-routes are being called on production?

**Comment by vazquez** [comment]
Confirmed. But with a slight variance.

STR:
1. create a new project
2. add content on first page
3. exit page, I never saw it update in project view. Waited ~30seconds 
4. exit project. I see the content show up in the thumbnail
5. refresh Make view

**Comment by cadecairos** [comment]
I know what the problem is.

The bulk API request handler isn't triggering any thumbnail updates.

**Comment by xmatthewx** [comment]
resolved: https://github.com/mozilla/api.webmaker.org/issues/165
