### ISSUE TITLE
Login error - invalid payload : password

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-core#559]
Comment in google play: 

> Seems interesting,  but can't  create an account "invalid payload : password"  isn't even an user-level error.

Any thoughts @jbuck @ashleygwilliams @cadecairos ?

**Comment by cadecairos** [comment]
A few possibilities here: they're entering a password that triggers validation to fail, which the app isn't anticipating (I.E. doesn't enforce all password policy rules client-side) or, just inadequate handling of poor/invalid passwords to begin with?

we should try to enter different kinds of passwords to see what could trigger this.

**Comment by Pomax** [comment]
Password validation in core:

```
...
password: {
  test: function (input) {
    input = input || '';
    return owasp.test(input).strong;
  },
  message: 'Your password must be at least 8 characters and contain at least 1 number and 1 letter'
},
...
```

In which the validation error message seems to have absolutely nothing to do with the actual validation that's taking place... O_o

**Comment by k88hudson** [comment]
This looks like it might be a case of someone trying to create a password that is too common -- as far as i can remember, this is the only thing we don't validate the same way on the client side.

If that is indeed the problem, we could probably return a more descriptive error message from id.wm.org

**Comment by Pomax** [comment]
for DRY guarantees, is there a way for us to use "the same code" on both id.wmo and wm-core for password validation?

**Comment by cadecairos** [comment]
we basically do, with the exception of not shipping a 10,000 item array of weak passwords.

https://github.com/nowsecure/owasp-password-strength-test
https://github.com/cadecairos/passtest

**Comment by cadecairos** [comment]
(shipping to client devices)

**Comment by Pomax** [comment]
The client app is currently a whisker under 30MB. Packing in the word list might actually be just fine, it only adds on 100kb from the looks of the code you linked.

**Comment by k88hudson** [comment]
I think it's a better idea to leave the password list on the server and improve the error message to be more descriptive than add the list to the client.

**Comment by cadecairos** [comment]
True, but it still leaves us with the id.wmo front-end not wanting to load a 103KB (minified!) JSON array of words

**Comment by Pomax** [comment]
in that case better error reporting is probably the better approach, yeah.

**Comment by xmatthewx** [comment]
Option A "That password is too common. Try something else." 
Option B "Try a different password."

**Comment by k88hudson** [comment]
Option A sounds way better to me

**Comment by cadecairos** [comment]
[The error reporting should be fine](https://github.com/mozilla/id.webmaker.org/blob/develop/web/server.js#L479-L488), I think we just need to handle things better client-side

**Comment by k88hudson** [comment]
Ok, so I tested a password on the list and it does indeed say `Password not strong enough`.

I'm unable to reproduce. Is it possible they're using an old build?

**Comment by xmatthewx** [comment]
Device: jfltexx
App version: 1.2.0

**Comment by xmatthewx** [comment]
I asked the user to email us at help@ so we can investigate. Let's hold off on this unless we hear from them or see it with other users.

**Comment by k88hudson** [comment]
thanks @xmatthewx!

@ashleygwilliams reported seeing the ability to bypass client-side validation on slow connections, it's worth looking into that as well

**Comment by k88hudson** [comment]
I noticed while testing this:
- I am able to create passwords that don't have both letters and numbers, as long as they are over 8 characters; also,
- if I get an error back from the server (such as "Password not strong enough") it doesn't actually go away after fixing it.

**Comment by xmatthewx** [comment]
error messages should disappear while fixing: #504

**Comment by k88hudson** [comment]
@xmatthewx the issue i thought might be causing the issue is in fact already returning the right error message, so i'm unable to reproduce this. has anyone else been able to do so?

**Comment by xmatthewx** [comment]
We didn't receive a follow up email. In fact, I can no longer find the original comment in google play. Let's assume it was resolved unless we hear otherwise.
