### ISSUE TITLE
Add apk key to the vault 

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-core#563]

**Comment by xmatthewx** [comment]
Did this happen @k88hudson?

**Comment by k88hudson** [comment]
No not yet, I was waiting on a USB key. Can do when I get back next week 

— K

**Comment by xmatthewx** [comment]
nudge nudge @k88hudson :clock1130:  :zzz: :hammer: :grin:

**Comment by xmatthewx** [comment]
@vazquez - can you serve as USB key courier? @k88hudson has the key. Angela has a physical vault.

**Comment by gvn** [comment]
Sounds like this needs to be in the next milestone...

**Comment by vazquez** [comment]
Yes, I haven't seen Angela since December 21st

**Comment by gvn** [comment]
It's now in our 1Password shared vault.

**Comment by gvn** [comment]
Resolved via https://github.com/MozillaFoundation/mofo-devops/issues/149
