### ISSUE TITLE
Reduce steps to add a photo

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-core#565]
Scenario: user adds a new photo to a page

UX below reduces the steps, skipping the placeholder image and proceeding directly to the source selector. Once selected, image lands on page, selected. 

![image](https://cloud.githubusercontent.com/assets/53411/9364151/e6976efe-4678-11e5-86fb-93675004a5bb.png)

**Comment by k88hudson** [comment]
Done!
