### ISSUE TITLE
Reduce steps to add a button element

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-core#567]
Scenario: user adds a new link to a page

UX below reduces the steps, going directly to the destination selector. After setting a destination, user proceeds to element editor. 

![image](https://cloud.githubusercontent.com/assets/53411/9364301/a920e6ee-4679-11e5-870a-d84286a46f98.png)

Future changes to the destination would behave the same: confirmation of destination leads to the element editor. Exiting the editor returns to page.

**Comment by k88hudson** [comment]
Dupe of #643

**Comment by xmatthewx** [comment]
cc @gvn

**Comment by xmatthewx** [comment]
nevermind. this is supplanted by #646.
