### ISSUE TITLE
No Thumbnail generated for my project

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-core#571]
I made it yesterday and still no preview thumbnail. It has content on the starting page, so that's not the issue...

![image](https://cloud.githubusercontent.com/assets/25212/9370391/dbbd0122-4684-11e5-857e-706cd8d7dfff.png)

**Comment by xmatthewx** [comment]
There was a bug that has been fixed. You will need to edit the page to trigger a new thumbnail. And then refresh Make view. Did that work? 

We are looking into automating this fix for other users.

**Comment by cadecairos** [comment]
you should have a thumbnail now on that project

![](https://dgu16gle6my6q.cloudfront.net/mobile-center-cropped/small/webmaker-desktop/aHR0cHM6Ly9iZXRhLndlYm1ha2VyLm9yZy8jL3RodW1ibmFpbD91c2VyPTUxNTQ2JnByb2plY3Q9MTA4MDYmcGFnZT0yOTMxMiZ0PTE0NDAwODU4MDgyMjk=)
