### ISSUE TITLE
Recently Featured project shows up halfway down the Discover View list - should be first?

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-core#572]
The "Art on a Wall" project was just featured now, yet it shows up halfway down the Discover view list? What is the sorting method for this list? Should newest projects show up at the top? The project was first created yesterday.

**Comment by xmatthewx** [comment]
I don't think we have a custom sort order, but we should either add that or a `feature date`. For now, we could adjust date created to optimize. cc @secretrobotron

**Comment by xmatthewx** [comment]
tracking in #592
