### ISSUE TITLE
First-time kebab (more actions menu)

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-core#575]
Share and remix are important actions currently hidden within the more actions kebab. 

FTU in project viewer
- "Share or remix this project"
- Show after delay? After first exit from page to project? 

FTU in project editor
- "Share this project"
- Show after delay? After adding two elements? After exit from page to project?

[təˈmeɪtoʊ təˈmɑːtəʊ](https://www.google.com/trends/explore#q=kebab%2C%20cabob%2C%20kebob%2C%20kabab&cmpt=q&tz=Etc%2FGMT%2B4)

**Comment by vazquez** [comment]
Proposal to have the text show as: 

`Make your own version of this - hit ‘Remix!’`

##### Rationale

My reasoning is that Remix is what truly is a barrier. Users don't understand what Remix is. The arrow is enough to give the user curiosity and, in the process, they can discover Share. Remix, however, requires a little bit more information.

##### Parameters
- FTU would appear on the users' 2nd project lifetime view. I think the first Project view experience they have should just focus on the content, not on the UI. In their 2nd project view, they will have context of what viewing a project is about – we can introduce Share and Remix then.

![play page remix ftu](https://cloud.githubusercontent.com/assets/1119821/9417618/c41cb65a-481b-11e5-824e-dc052adad770.png)

**Comment by xmatthewx** [comment]
Great. Looks great. My comment above got fudged up, now fixed. Let's design a 2nd version of this for project editor that focuses on share.

**Comment by vazquez** [comment]
#### Project Editor Share FTU

##### Parameters
- Modal would show up after user has created their 2nd page with content. My rationale is that one would be more likely to share a project that has more than 1 page.

![tile map view ftu](https://cloud.githubusercontent.com/assets/1119821/9441250/e4b97596-4a42-11e5-8d41-b451fb9ffa30.png)

**Comment by xmatthewx** [comment]
R+

**Comment by xmatthewx** [comment]
@vazquez - ready for translation and annotation?

**Comment by vazquez** [comment]
I want to wait until we do Tech Review on the other FTU issue (#583) to see what approach we're going to take (load image per locale or load 2 new font familiies and custom position)

**Comment by vazquez** [comment]
Created implementation tickets #630 and #631
