### ISSUE TITLE
Implement Discovery view FTU

### ISSUE THREAD

**Issue by vazquez** [mozilla/webmaker-core#583]
In an effort to reduce frustration when landing on the Discovery View, we are introducing a Discovery View FTU.
#### Notes & Requirements
- FTU should display once only, after used has created their account.
- Localization of this message is key. Let's talk about how we can achieve this. Should we load two new fonts (Sharpie font for English, Portuguese, Indonesian && Google Noto for Bengali)? Or should we make these modals images and swap them based on locale?
##### Text Strings

English: Explore stories around the world ... or make your own!
Brazilian Portuguese: Explore histórias ao redor do mundo ... ou faça a sua !
Indonesian: Temukan cerita dari seluruh dunia ... atau buatlah ceritamu sendiri!
Bengali: আপনার চারপাশের দুনিয়ার গল্পগুলো আবিষ্কার করুন ... অথবা নিজেই তৈরী করুন!
###### English

![intro english 1x](https://cloud.githubusercontent.com/assets/1119821/9442685/243a12a4-4a4b-11e5-88ae-a6b833c53f8c.png)

---
###### Brazilian Portuguese

![intro brazilian portuguese 1x](https://cloud.githubusercontent.com/assets/1119821/9442699/3801dace-4a4b-11e5-8033-85d99e8f0c73.png)

---
###### Indonesian

![intro indonesian 1x](https://cloud.githubusercontent.com/assets/1119821/9442719/4d6ddeee-4a4b-11e5-8e8d-642596a396da.png)

---
###### Bengali

![intro bengali 1x](https://cloud.githubusercontent.com/assets/1119821/9442725/5b99a5fc-4a4b-11e5-925a-2afdaa5e6cac.png)

**Comment by xmatthewx** [comment]
Let's confirm that an ellipses makes sense in all languages.

**Comment by vazquez** [comment]
We've reached out to community members. They have proofread this for grammar and general sense :+1:

**Comment by gvn** [comment]
This looks do-able from an engineering perspective. :+1:

**Comment by gvn** [comment]
@vazquez If this is ready to build can you point me to the Sketch file?

**Comment by vazquez** [comment]
Definitely! Sorry for nor sharing earlier. 

https://drive.google.com/a/mozilla.com/file/d/0ByIoeeW0a3R_bFJXa242RllFQ0U/view?usp=sharing

**Comment by vazquez** [comment]
Sharpie font available here: https://www.dropbox.com/s/z69u1p7q1i1syq4/Lamson-Sharpie.ttf?dl=0

**Comment by vazquez** [comment]
Gogle Noto font available here: http://www.google.com/get/noto/#sans-beng

**Comment by gvn** [comment]
@vazquez Where did the Sharpie font come from? We'll need the other formats of it and be sure that it's licensed for embedding... :pencil2:

**Comment by vazquez** [comment]
@gvn Ah my bad. This is the whole folder with all the fonts and webfont specifications. 

https://dl.dropboxusercontent.com/u/43783651/Lamson-Sharpie-Typeface.zip

The zip file contains the following formats:
- EOT
- OTF
- TTF
- SVG
- WOFF

**Comment by gvn** [comment]
Perfect, thanks!

**Comment by xmatthewx** [comment]
@gvn - is it worth giving an ID to each FTU experience and then tracking what's been seen by a user in the DB? We could add other prompts in the future. cc @k88hudson

**Comment by gvn** [comment]
I think that's a great idea if we don't already have analytics that cover the various events that trigger FTU.
