### ISSUE TITLE
Transitions between linked pages broken if you act quickly (?)

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker-core#586]
Not sure how to phrase this one properly. Can make the browser player act really jumpy and improperly though:
1. Check out https://beta.webmaker.org/#/project?user=452666&project=5218
2. Click on button on first page.
3. Click on button on second page.
4. Click on button on third page.
5. Quickly click on first page button again.

Eventually, this will cause some strange transitions for me — like jumping between 1 & 3.

Here's a video of me having a whole bunch of trouble with those buttons: https://dl.dropboxusercontent.com/u/7054348/webmaker-buttons-bug.mov

Generally, trying to quickly click on buttons makes problems. Unable to click buttons again, flickering between pages, etc. Maybe something to do with the page transition not completing.

**Comment by xmatthewx** [comment]
Just saw something interesting: 
1. photo of a cat has a button
2. i click button
3. cat page animates to the left
4. new page with button animates in to the center
5. i quickly click the button
6. browser thinks the cat is still in the center. applies click on that target. >>> I saw the image float for a split second as if I started to drag it across the page. It seems like the animation rendering happens more quickly than the browser realizes.

Solution?: During animation, we disable clicks and maybe reduce opacity. After animation finishes we enable again.

**Comment by xmatthewx** [comment]
I think it's a animation start end timing thing. If clicks are less than a second apart, they don't work. See: 
https://github.com/mozilla/webmaker-core/issues/610

**Comment by gvn** [comment]
Yeah, I'm pretty sure we're going to have to prevent clicks during transitions to solve this. I'll take a look.

**Comment by secretrobotron** [comment]
@gvn alternatively, jump to end of transition?

**Comment by gvn** [comment]
Well, you kind of already are "jumping"...it's just a matter of letting things finish.
