### ISSUE TITLE
Rename "Settings" to Project Details

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-core#594]

**Comment by xmatthewx** [comment]
At least in the more actions menu

**Comment by ryanwarsaw** [comment]
I'd love to take this, seems pretty straight forward.

**Comment by xmatthewx** [comment]
thanks @ryanw-se! Don't worry about the header. I just hope to drive more people toward creating a title via the more actions menu.

**Comment by xmatthewx** [comment]
@secretrobotron - I'd like to update the `Settings` to `Project details` in the more actions menu to make it more welcoming. Can we get this translated? 

@ryanw-se - interested in learning about transifex?

**Comment by lauradereynal** [comment]
This came back today with users. 
It's quite confusing. What is the status?

**Comment by secretrobotron** [comment]
@LauraReynal @xmatthewx you should be able to tweak (and submit pull request) to https://github.com/mozilla/webmaker-android/blob/develop/app/src/main/res/values-en/strings.xml (which you should just be able to do straight from github).

@alicoding once a change is made to that file, it'll show up automatically on Transifex, right?

**Comment by alicoding** [comment]
@secretrobotron we did not set up auto push to Transifex for this resource file. We need to do it manually here https://www.transifex.com/webmaker/webmaker/webmaker-stringsxml/
