### ISSUE TITLE
More user friendly error messages when building the android app

### ISSUE THREAD

**Issue by ryanwarsaw** [mozilla/webmaker-core#596]
Apparently when you try to build the app, you need to run npm install first so the dest folder exists, but you really don't know to do that unless you experiment around with it, because the error doesn't reflect that, the error should be mitigated and replaced with a user friendly message instead.

**Comment by ryanwarsaw** [comment]
Mental note: You have to run `npm run build` at least once in order to successfully compile the app, I thought I fixed this in the build script but apparently not, I think it has to do with production vs staging builds, will need to investigate this further in the future.

**Comment by xmatthewx** [comment]
cc @alanmoo

**Comment by gvn** [comment]
I did a PR adding `npm start` (which runs `npm run build`) as a postinstall. @ryanw-se Do you think this will help make things easier?

We do have the fact you need to run some npm commands documented [here](https://github.com/mozilla/webmaker-android#clone--install-dependencies), but let me know if there's any way we can clarify the instructions!

**Comment by gvn** [comment]
PR is here:
https://github.com/mozilla/webmaker-android/pull/2447

**Comment by xmatthewx** [comment]
@ryanw-se review @gvn's PR when you have a moment .

**Comment by gvn** [comment]
It's actually already merged...gonna close this ticket.
