### ISSUE TITLE
Buttons are wrong size/position/font in browser

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker-core#598]
I'm seeing a lot of larger-than-intended buttons in projects through desktop Chrome/Firefox. There is discrepancy between desktop and android there. Made a sample project to check it out:

Browser: https://beta.webmaker.org/#/project?user=454339&project=17959
Android: https://beta.webmaker.org/users/454339/projects/17959

**Comment by gvn** [comment]
I think this will be resolved by https://github.com/mozilla/webmaker-browser/pull/225

**Comment by alanmoo** [comment]
Also see #735, but yeah I think that should take care of it.

**Comment by gvn** [comment]
I also realized that custom fonts weren't being pulled into `project.html` when I was updating React, so that new patch should actually fix it.

**Comment by gvn** [comment]
Ok, I realized that there's a CSS conflict causing this. Projects are inheriting some style from another `btn` class used in the "website" portion of webmaker.org.
