### ISSUE TITLE
Implement new login/signup UI

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-core#599]
@vazquez - let's separate this from age verification. Add annotations here. No need to change mocks for age verification. 

Note: on login view - let's add "username or email" to first field's label. Both currently work for login.

**Comment by vazquez** [comment]
![new ui login annotations](https://cloud.githubusercontent.com/assets/1119821/9477356/e78da26c-4b3f-11e5-8b0c-85c37b5621ca.png)

**Comment by vazquez** [comment]
@xmatthewx Am I missing anything above? :arrow_up:

**Comment by xmatthewx** [comment]
Looks good. What's the height of the fields? Let's remove the side notes since they pertain to age gate.

**Comment by xmatthewx** [comment]
Thanks for the speedy post. If you run out of design tasks, maybe you want to try your hand at building this?

**Comment by vazquez** [comment]
I'm up for the challenge :guitar:

**Comment by vazquez** [comment]
![giphy 10 12 38 am](https://cloud.githubusercontent.com/assets/1119821/9528422/5f5f5a96-4cc2-11e5-96d3-49006986c980.gif)

**Comment by vazquez** [comment]
Follow-up ticket #607 to allow users to sign-in with username or email.
