### ISSUE TITLE
Migrate issues

### ISSUE THREAD

**Issue by gvn** [mozilla/webmaker-core#6]
Migrate all the issues from `webmaker-android` and `webmaker-browser` to this repo. Put `android` and `browser` tags on migrated issues respectively.

**Comment by gvn** [comment]
After issues are migrated let's shut down issue tracking for `webmaker-android` and `webmaker-browser`. This way all new issues can be filed in one place. Even though we have 2 (eventually 3) platforms we're essentially building 1 app.

**Comment by gvn** [comment]
This idea was proposed by @k88hudson and I think it's a great suggestion. 

@xmatthewx @simonwex and @secretrobotron what are your thoughts?

**Comment by gvn** [comment]
It does occur to me that there will be issues that make sense to live in `webmaker-browser` (which will become `webmaker.org`) since it's going to be more than just a wrapper for the Webmaker app. We might want to leave issue tracking open for it, but still close tracking in `webmaker-android` (and eventually `webmaker-ios`).

**Comment by k88hudson** [comment]
Copied from duplicate issue

> Now that we have a lot of shared code between core, browser, and android, I would recommending centralizing issues in webmaker-core (or somewhere else -- i don't care exactly where, just that it's in one place).
> 
> The vast majority of people filing issues on webmaker-core, webmaker-browser, and webmaker-android have no idea about the underlying architecture such that they will know what counts as a "core" issue, an "android" issue, etc. We'll have to spend a lot of time moving issues around and keeping track of milestones and assignment lists in three repos for very little benefit.
> 
> Centralizing issues in one place has the following advantages:
> 
> Issues can be managed, sorted, and search under a single milestone
> Issues can still be organized by platform for convenience with tags ('android' and 'browser' labels)
> Everyone has better visibility into everyone else's work
> Centralized triage for contributors, bugs filed, etc.
> Of course, after closing issues on the other repos, we'll want to link from the readme to https://github.com/mozilla/webmaker-core/issues

**Comment by toolness** [comment]
This (or at least part of it) is being done in #23.

**Comment by xmatthewx** [comment]
:+1: to centralized issues. When commenting on PR requests, please make a habit of linking back to the conversation in core so that those discussion remain visible. You can never have too many links. :link: :boom:

**Comment by gvn** [comment]
Yeah, we usually do "Closes BUG_URL/NUMBER" which creates a linkage from PR to original issue.
