### ISSUE TITLE
project view: Set origin of pinch to centre of touches

### ISSUE THREAD

**Issue by toolness** [mozilla/webmaker-core#60]
This issue has been migrated from mozilla/webmaker-android#1697.

It was originally written by [k88hudson](https://api.github.com/users/k88hudson) on Thu May 07 2015 and had the following description:

> Right now the origin is always `center`. We'd like to be able to center in the center of the pinch gesture.

On Wed May 13 2015, [xmatthewx](https://api.github.com/users/xmatthewx) commented:

> In addition to origin, our pinch seems amplified. 
> 
> Google maps seems to have a 1:1 ratio between pinch gesture and view scale. Streets stay relatively aligned with your fingers. Our zoom seems to be 1:1.5 between gesture and view. Pages scale more than my gesture. It's amplified. 

On Tue May 19 2015, [k88hudson](https://api.github.com/users/k88hudson) commented:

> I might need a bit of help on the translations/dilations formulas for this one, but i'll give it a go.

On Thu May 28 2015, [thisandagain](https://api.github.com/users/thisandagain) commented:

> Needed to roll back this patch due to mozilla/webmaker-android#2009 

On Wed Jun 03 2015, [k88hudson](https://api.github.com/users/k88hudson) commented:

> As we discussed, Pomax is going to try a different implementation in the next heartbeat

**Comment by k88hudson** [comment]
Resolved by https://github.com/k88hudson/webmaker-core/commit/cfb87966c0105973a5ee35b517b6647aa996f4ec
