### ISSUE TITLE
Add new URL structure to sharing code

### ISSUE THREAD

**Issue by k88hudson** [mozilla/webmaker-core#600]
We have a social-media friendly url for projects now (thanks @errietta!). We need to update the client in webmaker-core to point to this new url structure instead.

See https://github.com/mozilla/webmaker-browser/commit/bc7c94d59c5b73cefffc97d1813d04f71d89e863

**Comment by xmatthewx** [comment]
yay! thanks @errietta!!

**Comment by k88hudson** [comment]
My bad! this was already done a while ago :stuck_out_tongue_winking_eye:
