### ISSUE TITLE
Allow users to sign in with username or email

### ISSUE THREAD

**Issue by vazquez** [mozilla/webmaker-core#607]
As a follow-up ticket to #603, we want to allow users to sign in using their username or their email.

@k88hudson mentioned that we would need some logic to support this.

The `en-us.yaml` file already has the `username_email` key ready for use.

![sign in copy](https://cloud.githubusercontent.com/assets/1119821/9528187/4d321724-4cc1-11e5-9913-0b3a6adfce84.png)

**Comment by xmatthewx** [comment]
I have tested login using email rather than username on the app. It worked. I believe we added this a month or so ago, but the form label was not updated. @vazquez - give it a try to confirm.

**Comment by vazquez** [comment]
Confirmed! You are able to sign in with username or email already.

**Comment by k88hudson** [comment]
Oops! sorry about that @vazquez

**Comment by vazquez** [comment]
No worries at all Kate! Easy fix :)
