### ISSUE TITLE
Browser player - Button only works after second click.

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-core#610]
Steps to reproduce:
- Open this project https://beta.webmaker.org/#/project?user=476627&project=18490
- Click **Start** to navigate to the adjacent page
- Navigate back to the previous page with the left arrow icon
- Click **Start** 
  - Nothing happens
- Click **Start** again
  - The button works as expected

**Comment by xmatthewx** [comment]
I see this problem, but only if my two clicks are less than a second apart. I bet this is an animation start end timing problem. 

I'm going to close this but add a note from https://github.com/mozilla/webmaker-core/issues/586 to here.
