### ISSUE TITLE
Buttons should look super super chill

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-core#611]
When the button is white, it loses the top edge bevel, which makes it look flat
![image](https://cloud.githubusercontent.com/assets/25212/9553812/64eb25f8-4d76-11e5-9683-067d4eaa4f87.png)

@vazquez What do you think? We can...
- Leave as is
- Instead of a white highlight at top we add a slight darker shadow on the bottom (which would work on every color except on totally black buttons)
  - Add this special darker bottom border only on white buttons
- Not allow white as a button color (just a very slight gray)

**Comment by vazquez** [comment]
I vote for not allowing white as a button color. Having different shadows for different buttons can lead to confusion.

**Comment by alanmoo** [comment]
@vazquez Would you say then the best way to solve this ticket would be to offer a different set of default colors in the button background color picker?

**Comment by vazquez** [comment]
I agree @alanmoo. When looking at Webmaker projects, I have never seen anyone use white as a button. I would feel comfortable in removing white and adding a different colour. What do you think @xmatthewx @flukeout?

The button colour I propose adding is purple and blue.

![image](https://cloud.githubusercontent.com/assets/1119821/10368590/0b463e7c-6da4-11e5-95f1-1d88cb4a76cf.png)

**Comment by alanmoo** [comment]
So those should be the default colors? Right now I have 
![link colors](https://cloud.githubusercontent.com/assets/1682681/10370554/78fbd86a-6dad-11e5-8c40-5c279815cd1d.png)

(Cross reference #55)

**Comment by vazquez** [comment]
Yes, let's remove the transparent option for both Color and Background; they are not used in buttons at all.

Let's add `#9FD0E0` (aqua) and `#8173E4` (purple)

![screenshot 2015-10-08 11 25 52](https://cloud.githubusercontent.com/assets/1119821/10371003/5caae014-6daf-11e5-96b2-7c053f35a44a.png)

**Comment by alanmoo** [comment]
After a conversation with @vazquez, colors for links are
![link colors](https://cloud.githubusercontent.com/assets/1682681/10372261/f3dea4ac-6db4-11e5-8edd-e39bad677499.png)

**Comment by vazquez** [comment]
Boom! :facepunch:

**Comment by alanmoo** [comment]
Obviously white is still an allowed color using Tinker, but it's not an immediate choice. If the user really wants to do white, they should probably be able to, right?

**Comment by gvn** [comment]
@vazquez – Would it make sense to name/standardize these colors and add them to the style guide? Or is this more of a one-off color picker?

**Comment by flukeout** [comment]
Good stuff guys - I would suggest having a dark grey or black as one of the "color" options though. I don't see a lot of the color options working against those backgrounds - most buttons on the web seem to have white or black text (at varying opacities).

Thoughts? 

Radical idea - Maybe even just 3 whites and 3 blacks at varying darknesses / opacities in a kind of gradient?

**Comment by vazquez** [comment]
@alanmoo Yes, if they want it they can access it in Tinker Mode.

**Comment by vazquez** [comment]
@flukeout I hear you, what about this?

cc @alanmoo `#484B50`

![image](https://cloud.githubusercontent.com/assets/1119821/10372607/967c1df6-6db6-11e5-93f2-65910b18ce05.png)

**Comment by vazquez** [comment]
@gvn On the case! I will create another issue with updated colours

**Comment by flukeout** [comment]
@vazquez yeah, big improvement IMO!

@adamlofting At some point it would be cool to run a query against all published projects and see what the most common button text / background combinations are. Do we have such a capacity?

**Comment by adamlofting** [comment]
> @adamlofting At some point it would be cool to run a query against all published projects and see what the most common button text / background combinations are. Do we have such a capacity?

I've not yet spent any time in the raw project data for Webmaker, but that would a great thing to explore. @secretrobotron do you have access to run this kind of query? It depends on how the project data is stored and what we can search against versus where we might need to build some indexes etc.

**Comment by xmatthewx** [comment]
A few updates: 
- we should keep the option for `none` as a background color. 
- when none is selected, there should be no highlight or shadow.
- we should also have white

Labels for two color pallets should be:
- Text Color
- Button Color

etc. let's discuss...

**Comment by ryanwarsaw** [comment]
I'm a bit confused as to why we are removing transparency... it might not be very popular but shouldn't we focus more on adding new features and less on removing them?

Someone might find a creative way to use transparency, especially with buttons, even more so as we implement more features in the future.

**Comment by alanmoo** [comment]
@ryanw-se whatever we choose, it wouldn't go away completely. Transparent would still be an option in Tinker mode; this is just about default colors.

**Comment by ryanwarsaw** [comment]
@alanmoo :+1:

**Comment by vazquez** [comment]
@xmatthewx -

> - we should keep the option for none as a background color.
> - when none is selected, there should be no highlight or shadow.

Do you want to keep `none` as the background colour because you're looking to mimic links?

**Comment by xmatthewx** [comment]
Yes @vazquez and we've seen people use them to create integrated nav buttons as well. We could limit this to people who use transparency tinker mode if you think there's a good reason. But even in that case, we need to drop any highlight/shadow effect.

**Comment by alanmoo** [comment]
@vazquez @xmatthewx We are talking about within the set of default colors, right?

In addition, I'm trying to think about what approach we can take with this bevel (which is actually an inset box-shadow applied to all buttons right now). One thought is that the box-shadow's opacity could be reduced as the background opacity is reduced. This way we avoid weirdness around low opacities, as it will smoothly disappear.

This still doesn't solve the issue of white buttons looking flat, but I'm not sure there is anything to do about that.

There's a lot of conversation going on here, but I just want to summarize what we're trying to decide:
- [ ] Default text color of links (primarily: colors or shades of gray?)
- [ ] Default background colors of links (primarily: should transparent/white be one?)
- [ ] Behavior of box shadow

Anything else?

**Comment by xmatthewx** [comment]
Thanks @alanmoo for the wrangling. That's a fair summary. If we'd benefit from splitting this into separate issues, feel free. Your call. 
- Opacity on box-shadow seems like a reasonable, clean solution.
- I won't lose any sleep over flat buttons. None at all. 
- A limited palette of options is okay, since it will encourage people to tinker.
- Let's definitely keep none :no_entry_sign: as a background option. Gives users a broader range to make weird things.
- I'm cool with white, black, gray for text color. Any other color will likely clash with most background colors. What say you @vazquez ?

:ice_cream: :icecream:

**Comment by alanmoo** [comment]
I would say that none is more useful than white as a background color default option, would you agree @xmatthewx?

**Comment by vazquez** [comment]
Rockstar status @alanmoo.

I would like to have 6 colours for text colour. So, I propose this:

![image](https://cloud.githubusercontent.com/assets/1119821/10612729/0d6a436c-7720-11e5-86a0-f0a7cf94e21e.png)

The colour values, in order, are the following:

`#FAFAFA` `@heatherGrey` `@slate` `@darkSlate` `#161616` `@blue`

**Comment by flukeout** [comment]
@vazquez Want to challenge the text color set a bit ricardo, I don't think the two light grays will look good against the background colors we're offering. I think what we really need is black, white and an opacity slider for the text label. Then you can lighten the label without worrying that it might not look nice against the background.

**Exhibit A**
- Left side is solid colors set against orange
- Right side is black / white adjusted via opacity

![image](https://cloud.githubusercontent.com/assets/25212/10614017/ddbbbe4c-770c-11e5-8a8e-ed6af40f0003.png)

We can still do opacity via tinker on colors, but it feels cumbersome. 

Thoughts?

**Comment by vazquez** [comment]
@flukeout - To clarify, is this what you're suggesting?

![image](https://cloud.githubusercontent.com/assets/1119821/10614303/790dc2ea-7727-11e5-9abe-d6d5e8ba0323.png)

**Comment by flukeout** [comment]
@vazquez Yeah, that combo of options! Not sure how tinker would play with this so maybe we'd want opacity on the line below? We could set it to 60% or 80% default opacity, which should make most combos look nice.

In any case, we should mock up whatever colors / default we choose against the various backgrounds.

**Comment by alanmoo** [comment]
I'm not sure an opacity text slider is useful, at least not using the standard web behavior for text opacity- as that gets reduced, the text would become less and less legible.

**Comment by vazquez** [comment]
That's what I'm thinking too. Quick demo: http://codepen.io/rvazquez/pen/OyzxyR

**Comment by flukeout** [comment]
@alanmoo When text is against a background color (like on a button) it's much faster to get a pleasing effect by lowering the opacity on solid white or black text than trying to pick a specific color that works well.

But I think I get what you mean - is it about using a style or property that isn't commonly related with "just text" (like font-family or font-weight?)

**Comment by vazquez** [comment]
With @flukeout's proposal, the edit screen would change as per below. @xmatthewx - I will let you give the final yay or nay.

![button options copy 3](https://cloud.githubusercontent.com/assets/1119821/10614809/398a39de-772a-11e5-94ab-717ec3eac357.png)

The following option is still a possibility, but we would have to explore if we can bind both opacity sliders (the one in the element edit and the one in Tinker mode):

![image](https://cloud.githubusercontent.com/assets/1119821/10614303/790dc2ea-7727-11e5-9abe-d6d5e8ba0323.png)

**Comment by xmatthewx** [comment]
We need to split this into to two tickets. @vazquez will lead the way. One ticket, get the simple fix done. One ticket for aspiration.

**Comment by vazquez** [comment]
Filed new ticket for text and button colours in #719. ~~Closing this one.~~

**Comment by vazquez** [comment]
@alanmoo -
- Follow @xmatthewx's comment to get this ticket done https://github.com/mozilla/webmaker-core/issues/611#issuecomment-149606427
- Regarding text colour and button colour, head over to #719

:cow: :star:

**Comment by xmatthewx** [comment]
Timeout. Let's hit pause on all engineering until we can provide a clear spec. We have lost our way in an issue that was debatably not even a problem to begin with.

**Comment by xmatthewx** [comment]
Closing this. We will fix implementation in https://github.com/mozilla/webmaker-core/issues/720 and then can explore design dreamery in #719.
