### ISSUE TITLE
Add color selector for button label text

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-core#615]
When users create a link button, allow them to select the text color in addition to the background color. (Currently, color is auto set to black or white. It's buggy)

**Comment by alanmoo** [comment]
I assume this would be an additional row below the "Background color" selection, correct? @vazquez? 

Related (and this may be another ticket or something) but it strikes me that scrolling down the page loses sight of the button you're trying to decorate- has there been any discussion about keeping the button visible and just having the controls below it scroll underneath the preview?

**Comment by vazquez** [comment]
@alanmoo 

**Re Q1:**

Yes, it would be an additional row :)

**Re Q2:**

That's exactly how we initially envisioned the UI! We haven't implemented it due to tech debt, but it would be _amazing_ to implement this UI handling.

**Comment by xmatthewx** [comment]
Cool. I filed improvements to element editor, include a fixed preview window here: https://github.com/mozilla/webmaker-core/issues/692

**Comment by alanmoo** [comment]
Is it correct to say that with this, text won't automatically change colors based on the background anymore?

**Comment by xmatthewx** [comment]
Yes, please. The auto color doesn't work correctly for all colors.

**Comment by alanmoo** [comment]
Ok. For now I'll make the default set the same as for the background, but my guess is we might want to change that in the future

**Comment by xmatthewx** [comment]
Ah yes. By default let's make text white. That will work reasonably well for most colors.
