### ISSUE TITLE
Dark UI -> Browser

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-core#616]
Dark UI landed in Android, but I'm not seeing it in browser viewer. Maybe this landed on staging and needs a nudge to production? cc @gvn @k88hudson

**Comment by k88hudson** [comment]
Ah, sorry! You're right. I will push that when I get home 

— K

**Comment by xmatthewx** [comment]
Tomorrow morning is fine. Yer the best!

**Comment by k88hudson** [comment]
All done!
