### ISSUE TITLE
Enable easier bug reporting for end users

### ISSUE THREAD

**Issue by gvn** [mozilla/webmaker-core#620]
We should set up a way for people to report bugs from the app, even if it's just an email link.

**Comment by xmatthewx** [comment]
:+1:  

@vazquez - let's identify the best place to put a `Help` link to help@ email address.

**Comment by vazquez** [comment]
#### 3 Options

---

##### 1. Show it in Profile

This is the top-most hierarchy in the app. No one will miss it this way.

![make view beta copy](https://cloud.githubusercontent.com/assets/1119821/9632307/67fba93e-5154-11e5-90f3-15124f19567e.png)

---

##### 2. Show it in Project Editing More Actions

My assumption is that people editing might have more questions than people viewing. Regardless, we could extend this to the Play More Action menu as well.

![tile map view tile selected](https://cloud.githubusercontent.com/assets/1119821/9632336/91c43326-5154-11e5-81fe-32483aef925c.png)

---

##### 3. Show it in Project Settings

This is the most buried option of the 3, so it is not my favourite. An option nonetheless. I still need to work on the UI for this.

![project settings 2 copy](https://cloud.githubusercontent.com/assets/1119821/9632337/97134c9a-5154-11e5-82ee-1a58816425ce.png)

---

@xmatthewx @gvn What do you think?

**Comment by cassiemc** [comment]
"Give feedback" seems different from 'get help'

**Comment by lauradereynal** [comment]
ccing myself as per discussion with Ricardo
1. Get help on whatever you need ==> Desk.com
2. File bugs ==> This is very "Mozilla" I never saw that on other products
3. Give general feedback ==> prompted questions from us such as a survey or else. 

I think @gvn referred to 2. No ? 

@secretrobotron what do you think  ?

**Comment by vazquez** [comment]
Notes from critique:
- Get Help vs Give Feedback
  - They are mutually exclusive, should we have both?
  - "How can we help?" "Give us feedback"
- Even though we have Google Play Store for feedback, maybe the user wants their feedback to be private. It is still worth it to place a feedback AND help link on the app.
- On a more general note, it would be great to follow the steps of Wordpress, Freshbooks, Layervault, Slack, etc. and have the team answer support tickets! :yellow_heart: The great thing is that we already have the infrastructure set up with desk.com.

**Comment by gvn** [comment]
Sorry, "bug reporting" is **very** dev-centric language. What I mean is an easy way for users to give feedback (something that would probably _become_ a bug on GitHub).

Right now it seems like we are depending on users giving negative reviews instead of reaching out directly, which is obviously not ideal!

**Comment by secretrobotron** [comment]
:+1: to streamlining path to support tickets. Great to have more of those.

> prompted questions from us such as a survey or else

That's a cool idea too, @LauraReynal. Because users are on a phone, maybe we have a small FAQ with button that says, "no, i have a real unanswered question", which creates a support ticket through desk.

**Comment by xmatthewx** [comment]
This is great. 
- Highly visible button  ~~next to~~ above log-out :+1: 
- Button labeled "Need Help?" or "Questions? Feedback?" :+1: 
- Loads a simple FAQ page :+1: 
- FAQ page includes email link with CTA: Other Questions? Feedback? Problems? :+1: 
- Email goes to desk for triage :+1:  
- We reply to user and maybe file bug in github :+1:

**Comment by vazquez** [comment]
As per my conversation with @xmatthewx 

The string `Need help` is enough of an invitation for feedback. Users are already utilizing Google Play and `help@webmaker.org` to leave feedback and ask for help.

For first iteration, a single button that initiates an email to `help@webmaker.org` will be sufficient. Further iterations may include the simple FAQ page.

**Comment by ryanwarsaw** [comment]
I feel like we should focus on streamlining the process with a form or something that is easy to access, doesn't require remembering (or copying) a email address and allows us to specify information to be provided in the help request.

If we have a form, we can also collect information such as the device type, the version of the app, identify any crash reports sent by the user to GA, etc. I'm a bit skeptical that people are going follow through the process of sending a email help request and even then, with the proper information in order for us to help them.

**Comment by xmatthewx** [comment]
I hear your concerns @ryanw-se. Implementing with a mailto link is the quickest path to connect users with our support Desk account. We can iterate later based on what that minimal solution teaches us.

**Comment by vazquez** [comment]
R? @xmatthewx 

![make view beta copy](https://cloud.githubusercontent.com/assets/1119821/9743265/610bde12-5633-11e5-8afd-1d98c858ae95.png)
