### ISSUE TITLE
Placeholders in login are off center

### ISSUE THREAD

**Issue by vazquez** [mozilla/webmaker-core#624]
Something Android-y happened that is causing the placeholder fields to be unaligned vertically.

![2015-09-02 08 27 31](https://cloud.githubusercontent.com/assets/1119821/9631256/b1023c58-514d-11e5-9251-8436170b28f3.png)

**Comment by vazquez** [comment]
I realized that the culprit was me developing on Firefox, hehe :grin: 

Android is webkit, and as such they use `::input-placeholder` instead of `placeholder`, which moz uses.

@k88hudson Should I bother keeping both declarations? Or is `::input-placeholder` enough since that is all we need?

**Comment by vazquez** [comment]
Nevermind, answered my own question :+1:

**Comment by k88hudson** [comment]
:+1:

**Comment by vazquez** [comment]
oops! Closing again
