### ISSUE TITLE
Implement Play View Remix FTU

### ISSUE THREAD

**Issue by vazquez** [mozilla/webmaker-core#630]
#### Parameters
- FTU will appear on the users' 2nd project lifetime view. I think the first Project view experience they have should just focus on the content, not on the UI. In their 2nd project view, they will have context of what viewing a project is about – we can introduce Remix then.
#### Design

![play page remix ftu](https://cloud.githubusercontent.com/assets/1119821/9417618/c41cb65a-481b-11e5-824e-dc052adad770.png)
##### Text String

`Make your own version of this - hit ‘Remix!’`
#### Asset

Asset available: https://drive.google.com/open?id=0ByIoeeW0a3R_bFJXa242RllFQ0U

**Comment by vazquez** [comment]
![](http://media.giphy.com/media/bxQKzvlXsCXpm/giphy.gif)

**Comment by gvn** [comment]
:pizza: :pizza: :pizza: :pizza: :pizza: :pizza: :pizza: :pizza: :pizza: :pizza:
