### ISSUE TITLE
Setting a destination for the button is confusing 

### ISSUE THREAD

**Issue by lauradereynal** [mozilla/webmaker-core#632]
The process to set a destination is confusing to users.
- Click on add a button 
- Click on select a destination 
- you will see your project zommed out, and one icon supposed to mean "you are here"
  ==> users can confuse this icon with the destination itself and so they dont understand why the link is already selected. 

Proposition: 
- add a small text that says "You are here" or something like "departure" and "arrival" 

cc @vazquez @xmatthewx

**Comment by vazquez** [comment]
Great feedback @LauraReynal :hand: 

A design is coming very soon!

**Comment by xmatthewx** [comment]
I agree with the problem, and... let's explore other solutions. I'd like to avoid strings we need to translate if possible. How else could we mark the origin? Grayed out? Arrows emanating from the center?

**Comment by vazquez** [comment]
I think the quickest solution would be to reduce opacity and add a white layer on top of the origin page.

![screenshot 2015-09-04 11 12 38](https://cloud.githubusercontent.com/assets/1119821/9687181/f2f68520-52f5-11e5-9cf6-268e9c6ac45d.png)

More complex idea:
- If the user taps on origin page, we disclose a tooltip educating the user

**Comment by vazquez** [comment]
R+ from @xmatthewx. Creating implementation ticket.
