### ISSUE TITLE
Remove style guides and share preferences 

### ISSUE THREAD

**Issue by lauradereynal** [mozilla/webmaker-core#634]
In your profile you can see the github styles guides today.
cc @gvn @k88hudson

**Comment by ryanwarsaw** [comment]
@LauraReynal Was this in the nightly or release version? Its due to the BuildConfig debug flag being true on a production release, it typically has to be set to false to disable these features.

**Comment by xmatthewx** [comment]
@ryanw-se - it landed in the play store release. cc @k88hudson

**Comment by lauradereynal** [comment]
Update ? 

Im with a user right now and it's still here and confused her

**Comment by lauradereynal** [comment]
She thought it was the place for her to write longer texts and have more complex edits

**Comment by xmatthewx** [comment]
Assigning to @k88hudson to fix in our next release.

**Comment by k88hudson** [comment]
Let's do this on Monday

— K

**Comment by k88hudson** [comment]
Resolved as of 1.3.2
