### ISSUE TITLE
Add FTU query method to JS bridge

### ISSUE THREAD

**Issue by gvn** [mozilla/webmaker-core#642]
Assignee: @ryanw-se 
Related to: #621 

We need a method exposed in Platform that can query the Android wrapper to see if it's a user's first time using the app. 

Something like: `Platform.getFirstTimeUse()` which could just return a boolean value.

**Comment by gvn** [comment]
I actually just decided to use shared preferences w. the existing methods instead of adding extra sugar, so closing this! :sunglasses:

**Comment by ryanwarsaw** [comment]
@gvn do you still want me to do this or did you forget to close it?

**Comment by gvn** [comment]
Sorry, forgot to close. Shared preferences seems to be working out well...thanks though!
