### ISSUE TITLE
Reduce steps to link a page

### ISSUE THREAD

**Issue by vazquez** [mozilla/webmaker-core#643]
Scenario: User adds a button to the page, and edits the button element.

UX below reduces the steps, going directly to the modal, where the user can choose the type of link. After setting a destination, user proceeds to element editor.

![set link destination refined ux](https://cloud.githubusercontent.com/assets/1119821/9740953/7a9a1e60-5625-11e5-968e-6865b35939e1.png)

Notes:
- Modal copy has changed. The string now reads: `You can link your button to a 
  another page or to a destination 
  on the Web.` 
- `Set destination` button is now using an updated style, very similar to the one found in Login.

**Comment by xmatthewx** [comment]
Note: modal appears when user first adds a new link or taps 'set destination' from element editor. 

Note: task to add URLs as destination is filed separately #646

actions:
- tap add new link -> modal appears
- tap edit destination in element editor -> modal appears
- tap Page option in modal -> Page selector
- tap back in Page selector -> element editor
- tap back while viewing modal -> dismiss modal

**Comment by xmatthewx** [comment]
implementation in #646
