### ISSUE TITLE
Small browser-based viewer improvements

### ISSUE THREAD

**Issue by vazquez** [mozilla/webmaker-core#645]
**On Desktop Player**
- The navigation arrow tap/click areas need to be bigger to accommodate for easier interaction between pages
- Add a hover state to the navigation arrows (maybe a little back and forth nudge in the direction the view will move)
  - Also add a `title` attribute to explain the effect of clicking them
- Make it so you can navigate to adjacent pages by tapping them 
- ~~Make it so you can navigate to adjacent pages by mouse-swiping the current page~~
- Arrows could be just a bit smaller
- Fade out navigation arrows while the view is transitioning to another page and fade them in again when the transition is finished

**Comment by xmatthewx** [comment]
@vazquez says all is done or filed elsewhere.... yay
