### ISSUE TITLE
Implement link to a URL

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-core#646]
When users adds a link, a modal appears with the choice of destination: page or URL. If they choose URL, these see the settings view below. 

![set link destination refined ux](https://cloud.githubusercontent.com/assets/1119821/9740953/7a9a1e60-5625-11e5-968e-6865b35939e1.png)

![button link to web](https://cloud.githubusercontent.com/assets/1119821/7638033/134831c0-fa40-11e4-9201-c8f613187e8e.png)

@vazquez - plz confirm that these flows are correct:
- tap add new link -> modal appears
- tap URL option in modal -> URL settings
- tap back in URL settings -> element editor
- tap edit destination in element editor -> modal
- tap back while viewing modal -> dismiss modal

work began in #53

**Comment by ryanwarsaw** [comment]
I'm glad to see this is getting worked on, It'd be cool to see a warning pop-up of some kind when clicking a button that goes to an external URL. Having external URLs is a great thing, but it could be abused, possibly even maliciously, so we should warn people before clicking external links.

**Comment by vazquez** [comment]
@xmatthewx The flows are correct :+1:

**Comment by vazquez** [comment]
@ryanw-se It would be a good idea to do that once we have information as to how people use URLs in the context of Webmaker.

**Comment by gvn** [comment]
@xmatthewx Where would the "Learn more." link go?

**Comment by xmatthewx** [comment]
@gvn - we didn't identify a "learn more" destination. Let's leave that off for now. 

Also:
- the placeholder shouldn't include "i.e." before the example
- we should be prepared for some people to include http//:, but ideally shouldn't require them to type that out
