### ISSUE TITLE
Implement Author project list

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-core#654]
Discover view includes author name on projects. Turn these names into links to load a list of the authors projects. View will be the same as Make view, except for author features (logout, create a project, delete project).

**Comment by xmatthewx** [comment]
@vazquez to confirm this doesn't require any new design...

**Comment by vazquez** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;bBVyLxqs&#x2F;129-implement-author-project-list"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Implement Author project list</a>

**Comment by vazquez** [comment]
![artboard 38](https://cloud.githubusercontent.com/assets/1119821/10206431/de2fc152-6794-11e5-8897-6489bda767b2.png)

**Comment by xmatthewx** [comment]
The author name card looks good. Two things to adjust in the comp. Remove the create button. Remove active tab indicator from Make. It should either be Discover or neither.

**Comment by alanmoo** [comment]
@xmatthewx When you say it should be either Discover or neither, can it have the same heading as other pages do, with the arrow at the top?

I ask this because
- That's how the I currently have it working (and I'm hitting a wall trying to figure out how to get it to show up under discover)
- I'm also genuinely not sure what the best IA for this feature is

I'm not opposed to it being under Discover, just not sure what's best.

**Comment by vazquez** [comment]
(I apologize for not updating the design – fell out of my radar)

You are taking about this header, right?

<img width="347" alt="screenshot 2015-10-29 09 04 39" src="https://cloud.githubusercontent.com/assets/1119821/10819011/2a746c82-7e1c-11e5-8e68-2be5452375c7.png">

If so, a couple of questions:
- Can we modify the title?
- If we press back, where would we go?
- Does the More Actions appear? If so, can we remove it?

Regarding the IA, my intention is to allow people to use the navigation actions they are most used to. For Android, it's the system back button. If you're hitting a hard wall, we can explore the back arrow header instead.

**Comment by alanmoo** [comment]
We can modify the title, though I agree that I really like using the system back button (the current experience is a bit confusing with the top arrows in other views). I'm guessing the title can be dynamic ("Projects by alanmoo"), though I'd have to figure that out. Similarly, we should be able to remove the actions.

**Comment by xmatthewx** [comment]
@alanmoo - let's land this without too much concern about the header. I filed a follow up ticket to tackle that.  If the easiest header is back arrow + "Author" or "User", that's fine.

**Comment by alanmoo** [comment]
Great. I'll see what I can do about making the header the author's name and making the top back button work properly.

**Comment by xmatthewx** [comment]
> Does the More Actions appear? If so, can we remove it?

Sharing a link to an author view could be a nice feature. Remixing an author on the other hand, might push the limits of our science.

**Comment by vazquez** [comment]
Good thoughts @xmatthewx :+1: :cow: :star:

**Comment by alanmoo** [comment]
@vazquez @xmatthewx This is what it's going to look like when #766 lands. Sound good?

![screenshot_2015-11-02-17-16-23](https://cloud.githubusercontent.com/assets/1682681/10896249/b7bdf8a2-8186-11e5-8312-481c6f3003f3.png)

**Comment by vazquez** [comment]
WFM :cow: :star:

**Comment by xmatthewx** [comment]
If we have author name in the header, this is perfect.

**Comment by xmatthewx** [comment]
bump back to 1.6?

**Comment by alanmoo** [comment]
Closed by https://github.com/mozilla/webmaker-core/commit/f33f8a870ac6486beca185cb30233dab2665912a
