### ISSUE TITLE
Project & Discover Hashtags

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-core#655]
Project hashtags would unlock discovery of projects and enable users to gather around interests and affinities, a key feature of a webby world. 

Step 1 - outline the UX and specs 
Step 2 - estimate api work required to enable this
Step 3 - evaluate it

**Comment by vazquez** [comment]
Some thoughts...

![hashtags](https://cloud.githubusercontent.com/assets/1119821/9996258/30a6acc2-6054-11e5-921b-2d5e79e8ed88.png)

**Comment by vazquez** [comment]
@LauraReynal gave me some great feedback. Here's a v2!

The concept behind this approach is to **open hashtags as descriptions**. Similar to the most popular social networks that have already been established, users include hashtags in their descriptions. Let's take a look at Instagram:

![screenshot 2015-09-23 18 36 59](https://cloud.githubusercontent.com/assets/1119821/10060848/2125b8d6-6222-11e5-972e-c544d9b7490c.png)  

As we can see, users write content and naturally include #hashtags in their sentences.
<br>

### Descriptions in Webmaker (or Hashtags v2)

---

![hashtags v2](https://cloud.githubusercontent.com/assets/1119821/10060772/740cc892-6221-11e5-8120-4c736a121775.png)

**Comment by xmatthewx** [comment]
Thanks @LauraReynal for the feeback!

**Comment by xmatthewx** [comment]
Three small edits. Our verbal conversation trumps these bits in terms of priority. 
- 3rd settings view should have Description instead of Title as the header. 
- Make view should exclude username and avatar. 
- More actions in Make shouldn't include Flag...

**Comment by vazquez** [comment]
1. Good catch.
2. I think the username and avatar should remain the same in both Discover and Make. Looking at other benchmarks (Instagram, Facebook, Kickstarter, and Vine), the author view metadata persist the author's name and avatar. I think helps to keep the UI consistent between views.
3. Cool, will remove.

**Comment by vazquez** [comment]
### Enhancing Activity in Webmaker with Hashtags

---

![hashtags activity](https://cloud.githubusercontent.com/assets/1119821/10105320/0f2d19c0-637c-11e5-94e1-601b457cb57d.png)

**Comment by xmatthewx** [comment]
Excellent. I'd like to also see a version of a featured hashtag that is just a white card with text on it.  #newyearsresolution, #privacyday. Let's mark them `featured`. Post high enough resolution that I can integrate to slide deck.

**Comment by vazquez** [comment]
### White Pin

Large resolution available here: https://dl.dropboxusercontent.com/u/43783651/Discover%20View%20Hashtag%20Pins%20Copy.png

![discover view hashtag pins copy](https://cloud.githubusercontent.com/assets/1119821/10147670/57272616-65fd-11e5-870e-241a250a6c52.png)

**Comment by xmatthewx** [comment]
Could the featured hashtag be dark gray instead of blue? This card doesn't feel quite right. A bit tall. The label looked good with the background image, but unbalanced here. Maybe we drop it. Let's give this another pass.

**Comment by vazquez** [comment]
Agree. Some alternate explorations.

![image](https://cloud.githubusercontent.com/assets/1119821/10286658/bdd2869e-6b5c-11e5-986e-fce10ac1eaa9.png)

**Comment by xmatthewx** [comment]
I dig the green hashtag card. For the "featured" label, let's drop the icon and then bring it back later if/when we can design a system that connects with favs etc. 

For settings view, we should explain that a description can include hashtags. 

> **Description**
> Include #hashtags to create a link with related projects in Discover.

Or, ...the field label could be `Description and #hashtags`

**Comment by vazquez** [comment]
I vote for Description and #hashtags :+1:

**Comment by vazquez** [comment]
### Updating UI

Removing Featured label icon:

![image](https://cloud.githubusercontent.com/assets/1119821/10436448/66f45274-70f4-11e5-989b-077390c2f8c8.png)

Adding guide text below `Description`

![image](https://cloud.githubusercontent.com/assets/1119821/10436406/33fbefbc-70f4-11e5-9c0f-d6beb1eb39e9.png)

**Comment by lauradereynal** [comment]
So cool to see this feature come alive :+1: 

One question @vazquez If the user chooses to keep project private, it wont show on their profile ? does that mean that they wont be able to see it themselves ? How will they retrieve it ?

**Comment by vazquez** [comment]
:rocket: 

If the user chooses to keep their project private, it will show up in the Make View, it will just have a little bit of a different look. The design for this is being done in https://github.com/mozilla/webmaker-core/issues/651

**Comment by xmatthewx** [comment]
design is done. implementation begins in #772
