### ISSUE TITLE
Road to Android 2.2 Froyo Support

### ISSUE THREAD

**Issue by ryanwarsaw** [mozilla/webmaker-core#658]
This week I've been experimenting with our Android wrapper trying to get Android 2.2 Froyo support and higher for the app, as that would guarantee close to 100 percent compatibility with all Android devices, which would be optimal. I hit two road blocks during this experiment and decided it was worth discussing.

Currently, the two things blocking this goal is our implementation of Crosswalk (over Webviews) and our usage of Androids v7 support library (FragmentManager). The FragmentManager is minimal and can be easily solved by including those features locally, however Crosswalk is the bigger issue.

The original architecture of the project was based on WebViews and for some reason, (I believe it was performance) we decided to switch to Crosswalk. This doesn't seem to have a very negative effect at first glance, but there are two places where it is absolutely killing us. 

The first one being, our app size. We added probably 20-25 MB worth of size onto our compiled APK when we added Crosswalk, that's a pretty massive change. Another place where it is also secretly killing us, is in Android compatibility. It doesn't like to play well on older devices and thus we can only offer the app on newer phones that are capable of running Android 4+.

I feel confident the performance issue can be alleviated and we can find another solution that will serve us better, while keeping the size small and allowing us to run on basically any Android device you can find, which would be extremely awesome. Thus, I am running this idea through you guys and hopefully looking to get some feedback or suggestions on this.

**Comment by xmatthewx** [comment]
We need to further optimize the experience on 4+ and 5+. I'm not sure the benefit of support of further legacy devices outweighs the cost in testing and support.  

I can't comment on the benefits and disadvantages of Crosswalk.

**Comment by ariefbayu** [comment]
Hi guys,

I would like to weight in my view. Based on [google's dashboard](https://developer.android.com/about/dashboards/index.html), android below 4.0 account for less than 5%. I guess, we can forget froyo device?

**Comment by ryanwarsaw** [comment]
Per discussion with a couple of Android developers this week, it appears we use Crosswalk to maintain the chromium webview compatibility down through Android 4, Crosswalk doesn't play well with devices older than Android 4 and thus this is not a reliable option.

Devices older than Android 4 most likely are using Webkit based WebViews, which I don't believe our application supports and its probably not worth the effort of reworking the app for this compatibility, so I would say yes, this can be closed.
