### ISSUE TITLE
Upgrade to Node v4

### ISSUE THREAD

**Issue by alanmoo** [mozilla/webmaker-core#668]
The project seems to build, but the watch task fails. This may be related to webpack's versioning, as the problems start to appear when making changes to a `.jsx` file when `npm start` has been run.

**Comment by gvn** [comment]
I just upgraded to Node `v4.1.0` and everything seems to be working for me.

Which version are you on?

**Comment by alanmoo** [comment]
I also upgraded to Node `v4.1.0` and removed/reinstalled `node_modules`, I'm still seeing an error after running `npm start`. It looks like the task fails and restarts again, so I have to scroll back up in my console to see the errors

**Comment by alanmoo** [comment]
Of course now I'm realizing that I also see this error running Node `v0.12.3`...maybe this ticket should be closed and another one opened to figure out what that error's about (if anyone else is getting it).

**Comment by ryanwarsaw** [comment]
@alanmoo I did encounter this issue, I couldn't build core with Node v0.12.3, but after upgrading to v0.12.7 I could. The error I encountered wasn't really descriptive so I found the workaround by trying to update my environment. NPM also gives some weird errors if you are using an older version of that, also corrected by updating to a new version.

**Comment by gvn** [comment]
That's a good point too...what version of npm are you running @alanmoo ?

**Comment by alanmoo** [comment]
It wouldn't even start up using v0.12.7 and npm 3.3.3, but after resetting to npm 2.7.6 and then upgrading both to the latest (node 4.1, npm 3.3.3) and reinstalling node_modules, it's working fine. Maybe there some dependency upgrades happened in the last few days. Or it could have just been gremlins :)

**Comment by alanmoo** [comment]
Actually, should I have closed this or should we update `package.json`? What's the process for something like this?

**Comment by gvn** [comment]
Well, technically we already indicate that 3.3.3 isn't supported in our engines property of package.json, so I think it's ok to leave this closed. We could make a new ticket to add 3.X.X support though!

``` json
"engines": {
  "node": "0.12.x",
  "npm": "^2.7.4"
},
```

Looks like we do need to bump up our node version though...

**Comment by gvn** [comment]
Also, it would be good to add this info to the README.
