### ISSUE TITLE
Redirect webmaker.org/me to teach.mozilla.org/me

### ISSUE THREAD

**Issue by cadecairos** [mozilla/webmaker-core#672]
[As part of the deprecation plan](MozillaFoundation/plan#569), we need to redirect /me to the new page being implemented [here](https://github.com/mozilla/teach.mozilla.org/issues/1276)

**Comment by cadecairos** [comment]
I think I filed this in the wrong repo, lol.

**Comment by jbuck** [comment]
@cadecairos Lets upgrade to hapi 10!

**Comment by cadecairos** [comment]
Hapi 10 doesn't have wildcard routing either.

We could just have two routes with the redirect: '/me' and '/{lang}/me' since we can't do something like '/lang?/me'

**Comment by jbuck** [comment]
Oh, okay. Yeah, two routes is a good solution then!

**Comment by xmatthewx** [comment]
Ready for redirect. /me is ready on teach. Will be awesome to unblock launch of Webmaker site. cc @simonwex 

edit: looks like there's an open PR https://github.com/mozilla/webmaker-browser/issues/228
