### ISSUE TITLE
Use too many resources of my device

### ISSUE THREAD

**Issue by mfachrulrazy** [mozilla/webmaker-core#690]
Hello, I have installed Webmaker App on my device, Asus Zenfone 4 (with intel Atom Z2520, 1GB RAM) and when I create a project on Webmaker for about 8 pages, it uses too many resources of my device
- the battery it low very fast
- use too many ram, about 150mb
- my packet data connection for about 50mb
- also my device getting hotter
- it's difficult to arrange the postition of picture and image

here's my opinion for improve webmaker:
- I just wondered if I can use this App offline, when I don't need to get picture from the internet, because most pictures I use in this App just taken from my local gallery
- font size setting maybe great

**Comment by xmatthewx** [comment]
@fahrulrazy - sorry for the trouble with the app on your device. It seems like you're experiencing a memory leak. Even if we had an full offline implementation, you would probably still have performance issues.

cc @ryanw-se - any thoughts on the cause?

**Comment by ryanwarsaw** [comment]
@xmatthewx I do know there are some small ones present that could be contributing to the problem, but I'll continue to look into it and see what I can find.

**Comment by mfachrulrazy** [comment]
I think, It's okay if the app use too many amount of ram.. but I had this opinion, if I can create a project offline first until I finish it, then connection of packet data will be used, but if I only want to publish or share my projects to others. I think this is my idea when this app should offline, and when this app should online.
offline:
- when I create a project from scratch (new project)
  online:
- when discover other person's projects
- when we want to share (email, social media, etc)
- when we need pictures or images from internet

I think it might be good, if the use of packet data connection of this app, always ask for the user first before use... and one more thing, is it correct when I download the apps from play store, it's about 20MB, but when I have installed it, the size of the app become about 100MB

**Comment by xmatthewx** [comment]
tracking in #780
