### ISSUE TITLE
Improve scrolling of element editor views

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-core#692]
At least two improvements are possible: 
- fix the preview to the top of the view. scroll attribute UI up behind it. 
- improve touch/scroll behavior. currently, a swipe-to-scroll often fails when it starts on a slider or element that might have a different interpretation of the swipe. We're certainly not the only app to encounter this ... must be design or code methods to improve this.

**Comment by alanmoo** [comment]
Yeah, I noticed this behavior too. I'm guessing the touchEvent handlers need to be moved to the "knobs" instead of just the whole slider. The side effect would be you wouldn't be able to tap on a part of the slider to adjust to that value, but I feel like that's not a terrible drawback.

**Comment by xmatthewx** [comment]
Agreed.

**Comment by xmatthewx** [comment]
ideas to fix difficult scrolling:
- mask the slider with an element to block touch target outside 
- add margin to editor-options

**Comment by xmatthewx** [comment]
@vazquez - it seems like we'll need to add 40-50px padding on right side to make scrolling easier. @flukeout and I thought we could add a subtle texture to make the asymmetry ok and also make it super chill.

**Comment by alanmoo** [comment]
<img width="389" alt="screen shot 2015-10-19 at 11 02 10 am" src="https://cloud.githubusercontent.com/assets/1682681/10581474/e8283d72-7650-11e5-9dcd-7f7b65a6ea97.png">

@flukeout @vazquez who wants to take this on from a design standpoint? I also added that shadow under the preview (`box-shadow: 0px 2px 6px gray`), but I'm not sure if we have some guidelines for that kind of thing.

**Comment by vazquez** [comment]
I'll take it on @alanmoo. Today I might not get to it as I'm in a workshop day with Cassie, but I'll get to it :)

In the meantime, what kind of design support do you need from me?

**Comment by vazquez** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;yLom8vZt&#x2F;131-l"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> l</a>

**Comment by alanmoo** [comment]
No rush, I've got it on a branch whenever design is ready. Basically the separation between preview and options, and then...something visual for the scroll column? "Grips"?

**Comment by vazquez** [comment]
:+1:

**Comment by xmatthewx** [comment]
ping @vazquez

**Comment by vazquez** [comment]
@alanmoo I really like the box-shadow. I suggest we go with these slightly subtler values:

`box-shadow: 0px 4px 10px 0px rgba(84,94,102,0.30);`

![text options 2](https://cloud.githubusercontent.com/assets/1119821/10895776/f58dd6aa-8183-11e5-8809-1f02aacdb594.png)

**Comment by alanmoo** [comment]
Any design guidance for the space on the right which makes it easier to scroll, @vazquez?

**Comment by vazquez** [comment]
Right. I'm on it

**Comment by vazquez** [comment]
For the right hand side, let's add a visual enhancement that looks like a scrub.

![text options 2](https://cloud.githubusercontent.com/assets/1119821/10914152/1c20df88-821f-11e5-900f-c02999ab4cc4.png)

**Comment by vazquez** [comment]
Scrollbar SVG here: https://dl.dropboxusercontent.com/u/43783651/scrubber.svg

**Comment by xmatthewx** [comment]
R+ !

**Comment by xmatthewx** [comment]
design is ready for @alanmoo to finish up

**Comment by xmatthewx** [comment]
bam. this is gonna be amazing.

**Comment by flukeout** [comment]
:trumpet:
