### ISSUE TITLE
Prepare play store release announcement

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-core#693]
New release in Play Store includes "What's New" information to current and new users. It's a chance to highlight features and encourage a download.

Anything missing? 

Draft copy: 
https://webmaker.etherpad-mozilla.org/whats-new

List of commits: 
https://github.com/mozilla/webmaker-core/pull/691

cc @gvn @k88hudson @vazquez @alanmoo @HPaulJohnson @KevZawacki

**Comment by alanmoo** [comment]
Bad etherpad link?

Edit: nevermind

**Comment by xmatthewx** [comment]
The new release will include a new translation. Please review how I've stated this @alicoding @secretrobotron. See [copy in etherpad](https://webmaker.etherpad-mozilla.org/whats-new).

**Comment by gvn** [comment]
Technically our latest release will be 1.4.0...

https://github.com/mozilla/webmaker-android/commit/dc8ce6a32e6c4098f2d64c6e4aee4e6a6b12ce3b

**Comment by vazquez** [comment]
Looks good to me re: copy :+1:

**Comment by xmatthewx** [comment]
Here's copy extracted from the fallen etherpad, for posting in the play store. 

> Webmaker has been updated again!
> - Load more projects in Discover.
> - Use round corners to crop images into circles.
> - Get help with the tap of a button.
> - Add text more quickly to your pages.
> - Use large italic text.
> - Enjoy various bug fixes and improvements.
> 
> The app is now translated to Bengali (India) thanks to our community!

**Comment by xmatthewx** [comment]
tracking release in #737
