### ISSUE TITLE
A Webmaker Story

### ISSUE THREAD

**Issue by vazquez** [mozilla/webmaker-core#694]
Brief available: https://docs.google.com/a/mozilla.com/document/d/1irOqPUtHV0c-lhEgujLliPmQREJZ9lj21uC9BXTXw40/edit?usp=sharing

Deck available: https://docs.google.com/a/mozilla.com/presentation/d/19TgHgfrDtbm3Q7VLKRcfyxb20pqSPFrcCP9qW2dmJUw/edit?usp=sharing

**Comment by vazquez** [comment]
Some thoughts:

journey begins with a celebration of neighborhood #theHeights ... ends with #streetsmart other people who are using webmaker to document the awesome things about where they live.

**Comment by vazquez** [comment]
@xmatthewx and I conversed joyfully about the goal of this Webmaker story. These are the organized notes:

![scan oct 6 2015 12 35 pm](https://cloud.githubusercontent.com/assets/1119821/10315259/34864a3a-6c27-11e5-9f18-1277f8182271.png)

**Comment by vazquez** [comment]
@xmatthewx - A ~~Ricardo Map~~ System Map

![scan oct 6 2015 1 10 pm](https://cloud.githubusercontent.com/assets/1119821/10316528/ae883180-6c2d-11e5-977b-4411464428b6.png)

**Comment by vazquez** [comment]
Some ideas from design critique:
- Specific stories need more detail that couldn't fit in instagram or twitter or ... tie stories together in a project that couldn't be done on other platforms. map the neighborhood
- Who does he share his project(s) with? send to specific friends on facebook? what's his motivation? 
- I think the 2nd half of the story needs a bit more detail. he connects with another person in his neighb via #silverheights. later he connects with a group #streetsmart that made a nice project as a guide on using documentary to organize neighbors or something...
- Does this design task need to tell a story to achieve it's goal?  
- Does the story introduce more complexity and answers that it removes? 
- Can the story just help inform us on UI and UX choices?
- Maybe expand a bit on how the hashtags give life to the project after it's finished in the story. Who sees the hashtags, what do they do after that.
- How would webmaker make knowing this easier? remix?

**Comment by xmatthewx** [comment]
Let's add one more slide to the end that shows Webmaker featuring the hashtag. Text added, just needs a screenshot. https://docs.google.com/presentation/d/19TgHgfrDtbm3Q7VLKRcfyxb20pqSPFrcCP9qW2dmJUw/edit#slide=id.gcbe874022_0_0

**Comment by vazquez** [comment]
Done :guitar:

**Comment by xmatthewx** [comment]
:speaker: :postal_horn: :microphone:
