### ISSUE TITLE
New color broken on old buttons

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-core#715]
`Beta 1.4` might not render all user-created button properly if they were created in a prior version. 

Project linked below looks fine in the browser (white button, black text). In the app, buttons and text label are both white. Theory: previously, text color was set automatically to black or white based on background color. If color wasn't stored in DB, it may now default to white. Browser-based viewer still uses former rendering method.  

https://beta.webmaker.org/users/99118/projects/3680

Okay in browser:
<img width="1095" alt="screenshot 2015-10-19 13 50 57" src="https://cloud.githubusercontent.com/assets/53411/10586065/74dd1906-7668-11e5-9a79-4baf51c046b8.png">

cc @gvn

**Comment by alanmoo** [comment]
Yeah, looks like the default color is `#FFF` if there's no color attribute on the element. I think what I'll do is put the "figure out a color automatically" code back in to the `render` method on links if there's no color explicitly assigned. Seem like a reasonable solution, @xmatthewx?

**Comment by xmatthewx** [comment]
I'm hesitant to put auto color back in, because it was broken. 

Default `#FFF` will work in most scenarios.  If no color is set, what if we do a quick test on HSL or HSV and switch to black if needed?

> HSL : if ( lightness > .75 ) { color = #000; }
> HSV : if ( saturation < .25 || value > .80 ) { color = #000; }

I think I've chosen a good break points for [HSL](http://hslpicker.com/#fffb80). It's more tricky for [HSV](http://www.rapidtables.com/web/color/color-picker.htm). Yellow (45 < hue < 90) will almost always be bad with white. Since we are only fixing past projects, we're probably ok.

**Comment by alanmoo** [comment]
That's why I was thinking of switching that part back for old projects only- that way they would be consistent as to what it was when the user originally built the project.

**Comment by alanmoo** [comment]
Also, if I dig deep enough to the existing autoColor function, it looks like that's more or less what it's doing (though I can't parse through the math to figure out the effective L values). I'd strongly vote that we use autoColor to render the components in existing projects (so they look the same as they did before), but it won't affect new components at all.

Basically on element creation I'd set the text color as follows:

`color: props.color || getContrastingColor(props.backgroundColor),`

where `props.color` means the user has passed something in (new editor), and if not, do what we did before.

**Comment by xmatthewx** [comment]
:+1:

**Comment by alanmoo** [comment]
There's a slight side effect to this, at least with my current approach: Since I can't assign a default button color of white without risking white-on-light, the above approach results in all new buttons being white text on blue background, and the `getContrastingColor` method being used as the user switches background colors until the user specifically chooses a text color.  (None of the color radios are selected in the editor, the color just changes with the background.) I can probably dig deeper and find another solution, but I'm not sure how much effort I should put in to this. Thoughts?

**Comment by xmatthewx** [comment]
When a new button is created, if we assign white on blue as defaults, I'm ok with user switching around and accidentally creating white-on-light. Is that the concern?

**Comment by alanmoo** [comment]
No, that's an understood possibility. The concern is that until a user specifically picks a text color, it will be on "autopilot" as the background color changes, and the set of colorful radio buttons won't show any text color as specifically chosen (they're all unselected). Once the user does pick a text color, everything's normal.

**Comment by xmatthewx** [comment]
Ok, that's fine if we can't set a default color at the moment the button is created.  Run with it. We can follow up with other fixes later if needed.
