### ISSUE TITLE
Fix button color & style

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-core#720]
Webmaker v1.4 Beta introduce a user feature to set both the button background and text color. There are a couple of issues with the current implementation. 

Box shadow remains with backgrounds are set as transparent. 
Text color includes the option none transparent. 

proposed fix: 
- remove none as an option for text
- set box-shadow opacity to match background opacity to support none and tinker transparency (as suggested by @alanmoo)

**Comment by xmatthewx** [comment]
@vazquez - please confirm this as the simplest fix to the current 1.4 Beta implementation and then assign to @alanmoo for implementation.

**Comment by vazquez** [comment]
This is the simplest fix to close this issue. All aboard! :train:

**Comment by alanmoo** [comment]
I'm removing transparent as an option for text and adding `#8173E4`, right @vazquez?

**Comment by vazquez** [comment]
@alanmoo - :+1: Yes and it's already a LESS variable titled `@purple`.
