### ISSUE TITLE
Prepare Webmaker postcard for Mozfest ??

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-core#724]
A postcard for the Mozfest schwag bag could invite participants to install Webmaker and use it to extend the Mozfest experience. It could include a few recommendations for how to use Webmaker to document brainstorms, capture names and faces, compose a mini-presentation on an idea. 

Good idea? Discuss below.

cc @chadsansing @thornet

**Comment by thornet** [comment]
cc @Saallen 

Seems good if you want to produce it, but please note times are very tight and we can't assist much with printing and wrangling this.

**Comment by jgmac1106** [comment]
Why not fork the Whistler scavenger hunt activity and make it people
driven. I liked that one.

**Comment by xmatthewx** [comment]
Thanks @thornet. We'd handle all logistics ourselves. Will attendees see any info on pathways? If you have draft copy, we can aim for alignment. 

Thanks @jgmac1106. I think we can offer higher quality. I'd also like to emphasize ways we can extend experiential learning.

**Comment by thornet** [comment]
Sounds good!

Here's what will be printed and distributed regarding the pathways:
https://github.com/mozilla/2015.mozillafestival.org/issues/212

On Wed, Oct 21, 2015 at 5:14 PM, matthew w notifications@github.com wrote:

> Thanks @thornet https://github.com/thornet. We'd handle all logistics
> ourselves. Will attendees see any info on pathways? If you have draft copy,
> we can aim for alignment.
> 
> Thanks @jgmac1106 https://github.com/jgmac1106. I think we can offer
> higher quality. I'd also like to emphasize ways we can extend experiential
> learning.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mozilla/webmaker-core/issues/724#issuecomment-149928207
> .

## 

_Michelle Thorne_
Director, Mozilla Learning Programs
Mozilla Foundation

@thornet
michelle@mozillafoundation.org

**Comment by ioana-chiorean** [comment]
Hi all, sorry for bugging in, I quickly scan the link from Michelle and I saw that there are no QR codes ( sorry If i am wrong) 
As it is a mobile app - we should also consider adding a QR Code that people can scan and be directly sent to the Google play to install it. 
Beside the postcards in the bags ( or where we will have it) we might have one or two posters per floor with it. 

What do u think?

**Comment by xmatthewx** [comment]
Thanks @ioana-chiorean. 

First, I'd like to make sure we have a good reason to suggest people use the app at Mozfest. After we nail that down, figure out how to spread the idea.

cc @flukeout

**Comment by xmatthewx** [comment]
Closing this. We've decided to focus the resources we have toward the next release.

**Comment by xmatthewx** [comment]
@vazquez looking at options to create an activity/handout that connects with the Pathways introduction by Robert and Julia. 
https://github.com/mozilla/learning-networks/issues/276

**Comment by xmatthewx** [comment]
done!
