### ISSUE TITLE
Create a simple deck from proposals

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-core#725]
We outlined a few ideas during the work week for how to connect Webmaker to curriculum (or not). Their outlined in a google doc. Create a simple deck to summarize for sharing. No frills, fewest slides possible.

**Comment by flukeout** [comment]
On it! For reference - [Notes from the workweek](https://docs.google.com/document/d/1AOj3nF-wn8uAWGXpzLr8kGHrQxpjvBlRJwW85R63YIo/edit#)

**Comment by flukeout** [comment]
In-progress deck here - https://docs.google.com/presentation/d/1qu7RAhtCkisrsq1fSeOO41O7-q0Qm-Wd8vkgwog541U/edit#slide=id.p

**Comment by xmatthewx** [comment]
Thanks @flukeout for the speediness. Linked to your deck from the recap doc. We can call this done and open new tickets if needed.
