### ISSUE TITLE
Add support email link to the footer.

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-core#728]
We've set up `thimble@mozillafoundation.org` and want to link it on the footer as seen below...

![image](https://cloud.githubusercontent.com/assets/25212/10650024/194a391c-77fc-11e5-9469-4822d14f1017.png)

@hannahkane I had to change some of the link labels so they would all fit, what do you think?

**Comment by hannahkane** [comment]
Hey @flukeout, looks good.
- For consistency, "Email Us" (capitalize Us)
- Maybe "Tweet at Us"?

**Comment by flukeout** [comment]
I like "Email Us", but was thinking that it would be good to keep the word "Twitter" in case someone was searching on the page for it?

**Comment by flukeout** [comment]
Closing because I added this to webmaker-core for some reason.
