### ISSUE TITLE
Incorrect fonts are being used in desktop browser player.

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-core#733]
Parts of this project are rendering in Times New Roman...
https://beta.webmaker.org/?user=56433&project=4778#/project?user=56433&project=4778

Looks like the font **Bitter** isn't working correctly.

![image](https://cloud.githubusercontent.com/assets/25212/10681387/9b9349a4-78dd-11e5-8029-ae1044ab474c.png)

**Comment by alanmoo** [comment]
This looks to be an https vs http issue, according to the console

**Comment by alanmoo** [comment]
Closed by #735
