### ISSUE TITLE
Browser player renders buttons differently in FF and Chrome

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-core#734]
Firefox and Chrome side by side, respectively...

Looks like the button labels are wrapping in FF

![image](https://cloud.githubusercontent.com/assets/25212/10681424/ee879bba-78dd-11e5-8038-5038fb384b82.png)

**Comment by alanmoo** [comment]
Have a project link @flukeout?

**Comment by xmatthewx** [comment]
may or may not be related to #733 and #706

**Comment by flukeout** [comment]
@alanmoo Here it is https://beta.webmaker.org/?user=56433&project=4778#/project?user=56433&project=4778

**Comment by alanmoo** [comment]
Closed by #735
