### ISSUE TITLE
Persist styles on new elements

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-core#740]
When a user creates a button and carefully styles it, they often want to reuse that style on future elements. Let's help them by remembering the most recent styles and using them as the default for that element type. 

Notes: styles do not need to persist across different element types. For example, link font color does not impact text font color.

**Comment by xmatthewx** [comment]
Likely best done with a project-styles column in the DB so it persists. We'll have to start with a spec for the services team. Benefits to doing it in app vs db?

**Comment by alanmoo** [comment]
Is the idea to have this persist across relaunches in the entire project? Or just if you're building a project and want to add multiple of the same item in a row?

**Comment by xmatthewx** [comment]
Open for debate. Ideally ux-wise, if I use a project to periodically post about a thing, it'd be nice to carry those default styles across relaunches of the app. But, even just session persistence would be helpful. Engineering wise, I wonder if it's easier to track styles in db than move props between pages. We should probably pursue the easier engineering approach unless the lift is similar.

**Comment by alanmoo** [comment]
Two thoughts, after an IRC conversation with @gvn

1.) Would the ability to duplicate pages/elements accomplish the same thing? Would it be a better/worse approach?
2.) We wouldn't have to save this to the server, we could use https://github.com/mozilla/webmaker-android#sharedpreferences

**Comment by xmatthewx** [comment]
As we discussed: 
1. There is some overlap, but both persistent styles and page duplication are useful. Since persistent styles will impact all projects and users, we will pursue that first. Duplicating a page is a feature that will support authors who create more involved projects ... particularly useful for layout and repeat images/textures. 
2. Shared preferences sounds like the best approach to persistent styles. **We'll save these styles per project.**
