### ISSUE TITLE
Shuffle featured projects in Discover

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-core#744]
Let's randomize the projects initially loaded into Discover to add more spice to Webmaker life.

**Comment by gvn** [comment]
This is actually already being done! :+1:

**Comment by xmatthewx** [comment]
I'm going to reopen this, and flag for discussion next heartbeat since the ideal solution is very debatable. I think we did this on infinite scroll but not initial loading.

It might not be practical, but an ideal solution might look like this: 
- if anything was featured today, show it first
- random load following projects

"Today" would ideally be a feature date rather than create or edit date.

**Comment by gvn** [comment]
Well, that view gets cached, so it will only be randomized the first time you open it. You'd have to pull to refresh to get a new random order.

**Comment by xmatthewx** [comment]
this is done
