### ISSUE TITLE
[x86 device] QA Feedback - Android App - Project Editing Basics 

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla/webmaker-core#749]
- [x] create a new project, or open an existing one
- [x] you will see the map view of the project, centered on one of the pages
- [x] the blue header says "Project"
- [x] the centered page is selected
- [x] the pencil and trash icons are visible below the page
- [x] dragging the view to pan around the project view
- [x] pinching the view zooms the view in and out
- [x] pan to a place where there is an empty space with a "+" icon
- [x] tap the plus icon, a new blank page will appear in that space
  - [x] the view shifts to place the new page in the center of the view
  - [x] the new page is selected (it has a blue border)
- [x] tap a different page in the project, the view shifts to that page and that page becomes selected
- [x] tap the trash icon, the selected page is deleted
  - [x] there is now a "+" icon where the page used to be

**Adding Elements**
- [x] tap any page in the Project view page to select it
- [x] tap the pencil icon, the view will change to the Page view
- [x] there is a plus icon at the bottom of the screen
- [x] tap the plus icon, the view becomes dark and three new icons are visible
- [x] tap the first icon to add a text element
- [x] repeat the process to add an image element, and a button element
- [x] tap the back arrow, the view returns to the zoomed-out Project view
- [x] the page you were just editing is centered
  - [x] the elements you added to the page are visible, and are in the same position

**Comment by ioana-chiorean** [comment]
All test passed OK on ZTE Grand IN - x86 - API 15 (Android 4.0.4)

**Comment by xmatthewx** [comment]
:+1: thanks @ioana-chiorean ! :cake: 

Are you running the Beta version of the app? You can opt-in to get the latest features for testing: https://play.google.com/apps/testing/org.mozilla.webmaker

I added a note about this to the top of the [QA wiki page](https://github.com/mozilla/webmaker-core/wiki/Webmaker-QA-Template-Issues)

**Comment by ioana-chiorean** [comment]
:tired_face: Of course i did not.. Damn.. I will redo the testing in a few hours..

**Comment by xmatthewx** [comment]
@ioana-chiorean - don't worry about repeating this. I can do it or have @vazquez. Most of the changes in Beta appear in the Page editor and Element editors. Probably more fun for you to dive into a new section and useful for us to have your input on those QA scripts.

**Comment by ioana-chiorean** [comment]
Retried on new beta build - tasks were successful. 
I did notice that the app had some lags in Edition page - Adding elements section. i can do a video in the morning. Can u assign me on this issue pls. Thanks.

**Comment by xmatthewx** [comment]
Thanks @ioana-chiorean - digging thru your QA now!!
