### ISSUE TITLE
Improve layout of login/signup view

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla/webmaker-core#751]
I might have been tired but it took me a bit to figure it out I need to pan the page to get the log in button. 
Nexus 5 - Android 6.0

<img src="https://cloud.githubusercontent.com/assets/1391451/10831436/4f0204f2-7e8e-11e5-8e71-ebaaeaf3fc37.jpg" width="300" height="550" />

**Comment by gvn** [comment]
I've felt the same way...I think we need to make the logo smaller to avoid needing to scroll. We might be able to use Flexbox to keep everything within one screen-height.

**Comment by xmatthewx** [comment]
:+1: @vazquez might some updated UI that would also help.

**Comment by ioana-chiorean** [comment]
:+1:  :tada: :dancers:
