### ISSUE TITLE
[29.11] QA Feedback - Android Beta - Account

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla/webmaker-core#752]
Template from: https://github.com/mozilla/webmaker-core/issues/395 
Environment: Nexus 5 - Android 6.0

**Sign up**
- [x] open the app (or log out from the 'MAKE' tab, if already signed in)
- [x] make sure you are on the screen that says the equivalent of "Join Webmaker" on the button at the bottom
- [x] tap the "Terms" and "Privacy Policy" links at the very bottom
- [x] enter an invalid username by adding a @ in the Username field, check the error message you see
- [x] change to a valid username
- [x] start typing an email address, check the message you see
- [x] start typing a password, check the message you see
- [x] press 'Join Webmaker'

**Sign in**
- [x] open the app (or log out from the 'MAKE' tab, if already signed in)
- [x] make sure yo uare on the screen that says the equivalent of "Sign in" on the button at the bottom
- [x] tap the "Reset Password" link
- [x] enter an invalid username and password, press Sign In
- [x] check the error message you see
- [x] enter a valid username and password, press sign in

**Comment by ioana-chiorean** [comment]
All tests passed OK.
Feedback:
- some users might not see the Log in option: #751 
- error message for already used nickname doesn't disappear #753 
- keep the data entered at Sign in/ Sign up screen #754 
- Inconstancy at logos -Webmaker reset pass #755

cc @xmatthewx

**Comment by xmatthewx** [comment]
:+1:  thanks!
