### ISSUE TITLE
Error message for already used nickname doesn't disappear

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla/webmaker-core#753]
Entering an already taken nick name and tapping submit will display and error message. 
Going to the username field and change it should make the error disappear
- I know it need to press submit to check but if we edit it it should consider it a new entry
- all messages are very responsive to appear - after 1 character entered - so user will be waiting to see this disappear as fast as i appeared.

<img src="https://cloud.githubusercontent.com/assets/1391451/10833960/41946642-7e9e-11e5-91f7-755a55d48226.jpg" width="300" height="550" />

**Comment by xmatthewx** [comment]
tracking in https://github.com/mozilla/webmaker-core/issues/580
