### ISSUE TITLE
Keep the data entered at Sign in/ Sign up screen

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla/webmaker-core#754]
Entering partial data to the Log in screen and switching to Join screen (and viceversa) will loose the data entered. Most of the service use o keep it between screens (ex. FX Accounts)

<img src="https://cloud.githubusercontent.com/assets/1391451/10834029/d27514ea-7e9e-11e5-9b17-d859e193fc26.jpg" width="300" height="550" />

**Comment by vazquez** [comment]
Definitely! :) We are doing this work in #512.
