### ISSUE TITLE
Inconstancy at logos -Webmaker reset pass

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla/webmaker-core#755]
Going on the path to reset the password you will get into a screen with a form of the old webmaker logo. I think some users might be confused and refuse to change/use the page. (50% of users leave on product because of forgotten pass)

<img src="https://cloud.githubusercontent.com/assets/1391451/10834130/9296d95c-7e9f-11e5-8f90-54331551e49a.jpg" width="300" height="550" />

<img src="https://cloud.githubusercontent.com/assets/1391451/10834029/d27514ea-7e9e-11e5-9b17-d859e193fc26.jpg" width="300" height="550" />

**Comment by vazquez** [comment]
Great find, this has been filed in the id.webmaker.org repo

https://github.com/mozilla/id.webmaker.org/issues/405
