### ISSUE TITLE
[29.11.05] QA Feedback - Android Beta App - View Project

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla/webmaker-core#756]
Template from: #396
Environment: Nexus 5 - Android 6.0
- [x] Open the app and tap the Discover tab, which opens the Discover view

**Discover View**
- [x] In the Discover view you see a list of projects. Each projects includes...
  - [x] a title
  - [x] a preview image
  - [x] an author (indicated in blue)
- [x] scroll up and down to view additional projects
- [x] tap on any project in the Discover view, it will open

**Project Play Mode**
- [x] when the project opens, the header title is "Play"
- [x] you see a grid of pages
  - [x] pinch to zoom in and out
  - [x] drag to pan the view
- [x] tap a page to enter the Page view

**Page Vie**
- [x] In the Page view, you see the page you tapped previously, but zoomed in
- [x] there are arrows on the edge of the page that point to any adjacent pages
- [x] tapping an arrow moves the view to the adjacent page in that direction
- [ ] swiping the page in the direction of any of the arrows also moves the view to the adjacent page 
  - [ ] the view animates to the adjacent page smoothly
- [ ] swipe in a direction where there isn't an adjacent page, the view will not move
- [ ] tap the back button in the header to zoom back out to the Project view

**Project View**
- [x] the Project View is centered on the page you were just viewing
- [x] tap the menu (⋮) to reveal the share option
- [x] tap Share option to see a list of applications
- [x] tap anywhere to cancel
- [x] tap the back to exit the project and return to Discover mode

**Comment by ioana-chiorean** [comment]
**Page View**
- swiping the page in the direction of any of the arrows also moves the view to the adjacent page -> the view animates to the adjacent page smoothly
- swipe in a direction where there isn't an adjacent page, the view will not move
- This is not happening - You can not swipe. 
- tap the back button in the header to zoom back out to the Project view
- this will get you back to Discover View. 

@xmatthewx are these bugs or the template is not updated?

**Comment by vazquez** [comment]
@ioana-chiorean Great catch, the template is not updated. We used to allow swiping but we have since removed it.

**Comment by xmatthewx** [comment]
QA template updated
