### ISSUE TITLE
[29.10.05] QA Feedback - Android Beta App - Create & Delete Project

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla/webmaker-core#757]
Template from: #397
Environment: Nexus 5 - Android 6.0
- [x] Open the app and tap the Make tab, which displays the Make view

**Make View**
- [x] you see your username displayed at the top of the view
- [x] tap the "+ Create a Project" button, you will enter the Project view

**Project View**
- [x] you are in the map view of a project with a single page
- [x] the page is selected (there is a blue border around it)
- [x] tap the triple dot menu in the top right corner, you will enter the Project Settings view

**Project Settings**
- [x] the project title is "My project"
- [x] tap the project title to start editing it
- [x] you will see a keyboard
- [x] as you edit the name, the character indicator below the title keeps track of your character count
- [x] change the name to something that is less than or equal to 25 characters
- [x] tap the green arrow on the bottom of the keyboard, you will finish editing
- [x] edit the name again, then tap anywhere outside of the name or keyboard to finish editing
- [x] edit the name again, and make the name longer than 25 characters
- [ ] the character count indicator and underline should turn red
- [x] tap outside of the project name to finish editing
- [x] tap the back arrow, the view switches to the Project view
- [x] go back to the project settings view
- [x] the project title is the same as the last time you saw it in this view
- [x] Tap the back arrow to return to the Project view
- [x] tap the back arrow again, you return to the Make view

**Make View**
- [x] the project you just created is at the top of the list of your projects, just below the Create Project button
- [x] title and thumbnail appear as expected (refresh may be required)
- [x] tap the three-dot menu on that project, the Share & Delete menu opens
- [x] tap "Delete", the Make view refreshes and your project is no longer there

**Comment by ioana-chiorean** [comment]
Feedback: 
- change color for indicator: #759 
- use Capital for name projects #758 
- the character count indicator and underline should turn red 
  This is not happening. Is this an issue or it changed? @xmatthewx @secretrobotron 

<img src="https://cloud.githubusercontent.com/assets/1391451/10865884/3e6a2e20-8024-11e5-97cd-b9dbad1d15ce.jpg" width="300" height="550" />

**Comment by xmatthewx** [comment]
:+1: issues filed and wiki fixed
