### ISSUE TITLE
[1.11]  QA Feedback - Android Beta App - Image Element

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla/webmaker-core#760]
Template from: #399 
Environment: Nexus 5 - Android 6.0
- [x] open one of your existing projects or create a new one
- [x] edit one the pages
- [x] tap the plus icon at the bottom of the page add an image element to the page
  - [x] an image appears in the center of the page (it can be one of many starter images)
  - [x] the image is selected, it has a blue dashed border
  - [x] there is a garbage icon, a plus icon, and a paintbrush icon at the bottom of the page

**Moving the Image**
- [x] drag the image around the page, it moves with your finger
- [x] pinch the image to make it larger and smaller
- [x] rotate the image both directions using two-finger gesture

**Image Options**
- [x] tap the pencil icon to enter the Options view
- [x] change each of the available settings, the preview at the top of the page updates as you do so
  - [x] Opacity
  - [x] Border color
  - [x] Border width
  - [x] Corner radius
- [x] once you've made changes, tap the back arrow in the header to return to the Page view
- [x] the changes you made are reflected in the Page view
- [x] tap the pencil icon to enter the Options view again
  - [x] the changes you made to the image are reflected in the UI
- [x] tap the Change Image button, you see two options Take Photo & Camera Gallery
  - [x] tap Take Photo and complete the process, the image changes as expected
- [x] tap the Change Image button, you see two options Take Photo & Camera Gallery
  - [x] tap Camera Gallery and choose a photo, the image changes as expected
- [x] tap the back arrow to return to the Page view, the image is the same as the one you selected from the phone gallery

**Deleting the Image**
- [x] tap the Garbage icon, the image element is deleted

**Comment by xmatthewx** [comment]
@vazquez ran through this list. everything came back ok!
