### ISSUE TITLE
[2.11]  QA Feedback - Android Beta App - Text Element 

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla/webmaker-core#764]
Issue template from #400 
Nexus 5 - Android 6.0
- [x] open one of your existing projects or create a new one
- [x] edit one the pages
- [x] tap the plus icon at the bottom of the page add a text element to the page by tapping the "Aa" icon
  - [x] a text element appears in the center of the page and contains some text
  - [ ] the text is selected, it has a blue dashed border
  - [ ] there is a garbage icon, a plus icon, and a paintbrush icon at the bottom of the page
- [x] drag the text around the page, it moves with your finger
- [x] pinch the text to make it larger and smaller
- [x] rotate the text using a two-finger gesture, in both directions
- [x] tap the pencil icon to enter the Options view
- [x] change each of the available settings, the preview at the top of the page updates as you do so
  - [x] Font
  - [x] Color
  - [x] Text Style
- [x] once you've made changes, tap the back arrow in the header to return to the Page view
- [x] the changes you made are reflected in the Page view
- [x] tap the pencil icon to enter the Options view again
  - [x] the changes you made to the text element are reflected in the UI
- [x] tap the Edit Text button to enter text editing mode
- [x] you can edit the text by using the keyboard
- [x] tap the Done button to finish editing text
- [x] edit the text again and tap the green arrow on the keyboard to finish editing
- [x] tap the back arrow to return to the Page view
- [x] the text element has the text that you specified
- [x] tap the Garbage icon, the text element is deleted

**Comment by xmatthewx** [comment]
@ioana-chiorean - glad to see you're running Android 6. We haven't started testing with that yet.

**Comment by ioana-chiorean** [comment]
Feedback and issues:
- I was not able to use my regular account https://github.com/mozilla/id.webmaker.org/issues/406
-  "the text is selected, it has a blue dashed border" -> text not selected - template  not updated? 
- " there is a garbage icon, a plus icon, and a paintbrush icon at the bottom of the page" - this should not fall under the text editing mode. 

RE: - glad to see you're running Android 6. We haven't started testing with that yet.
- I choose x86 device and a 6.0 to cover some low covered ones, I can switch to more common ones if needed. 

Improvements for the template: https://github.com/mozilla/webmaker-core/issues/400#issuecomment-153729803

review @xmatthewx ?

**Comment by xmatthewx** [comment]
> I was not able to use my regular account

We'll get this fixed soon. We'll need to submit a hotfix and you'll have to wait for google play to deliver an update to your app. In the mean time, you can create a temp account to continue using the app.

**Comment by ioana-chiorean** [comment]
and the other 2 under feedback, @xmatthewx ?

**Comment by ioana-chiorean** [comment]
ping @xmatthewx or @vazquez for non resolved questions.

**Comment by xmatthewx** [comment]
hey @ioana-chiorean - I'm still getting caught up post-Mozfest. I assigned this to myself to make sure I don't neglect the questions.

**Comment by ioana-chiorean** [comment]
oh , sorry for the pressure @xmatthewx . thanks for clearing this out ( that u did not forget) 
Also let me know if you want me to check some more now ( I have way more free time after mozfest too and I will be able to check faster and more)

**Comment by xmatthewx** [comment]
@ioana-chiorean - we will launch v1.5 to Beta by early next week and would be glad to have your help with another round of QA testing. I'll share a list of the specific changes, so that your tests can focus on that. 

I made many changes to the templates based on your feedback. I probably didn't catch everything, but we can continually improve these. As the app changes, the tests change, so it will be an endless dance :dancers: 

Thanks again for all of your help!
