### ISSUE TITLE
Release 1.5

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-core#765]
- [x] Release is scheduled and a ticket to track the release process is created.
- [x] Tag release on webmaker-core repo.
- [x] Generate signed APK.
- [x] Release notes are drafted in the ticket. https://github.com/mozilla/webmaker-core/issues/765#issuecomment-156539700
- [x] Ticket is assigned to deploy APK to beta channel.
- [x] Coordinate release for Browser if relevant.
- [x] Once APK has been released to beta channel wait about 4 hours.
- [x] QA beta on several devices (flag people to test in release ticket) (Set tag: Needs QA). #796
- [x] Once everyone flagged for QA approves the release, change tag to Passed QA.
- [x] Check crash logs to ensure that no significant problems were reported.
- [x] Promote beta APK to production.
- [ ] Send out email with release notes.
- [ ] File issues for follow up research.
- [x] Close the release ticket.

**Comment by xmatthewx** [comment]
Let's push issues in this milestone back to 1.6 unless we have a PR in review. @gvn @alanmoo 

Here's a draft schedule to set a rhythm for the next couple of releases.  Let's discuss. 

| Week | Release | Build |
| :-: | :-- | :-- |
| 1 | 1.5 to Beta (Nov 13) | Begin 1.6 |
| 2 | 1.5 to Production (Nov 17) | Finish 1.6 |
| 3 | 1.6 to Beta (Nov 23) | Begin 1.7 |
| 4 | 1.6 to Prod (Nov 30) | Finish 1.7 |
| 5 | 1.7 to Beta (Dec 7) | Orlando |
| 6 | 1.7 to Prod (Dec 14) | Begin 1.8 |
| 7 | 1.8 to Beta (Dec 23) | Finish 1.8 |

cc @alanmoo @vazquez

**Comment by alanmoo** [comment]
I'm not sure I follow how Thanksgiving and Orlando fit in to this

**Comment by xmatthewx** [comment]
I'll push back the 1.8 beta release to account for Orlando. For Thanksgiving, let's adjust the number/scope of issues we tackle, rather than break the rhythm of releases.

**Comment by ryanwarsaw** [comment]
1.6 is going to be a huge update in terms of performance (on webmaker-android), I've got a ton of awesome things in the works and I really think people are going to be excited with the results. I also have off from school around that time, so we don't really need to adjust the number/scope of issues.

**Comment by xmatthewx** [comment]
Here are draft notes for the release. Thinking it'd be good to retain notes from last release as well.  

> New in version 1.5!
> - View more projects by each user in Discover
> - Add background color to text
> - Choose a text color for button links 
> - Scroll more easily in element editor
> - View page layout with more consistency between app and browser 
> - Enjoy various bug fixes and improvements
> 
> New in version 1.4
> - Load more projects in Discover.
> - Use round corners to crop images into circles.
> - Get help with the tap of a button.
> - Add text more quickly to your pages.
> - Use large italic text.
> - Enjoy various bug fixes and improvements.
> 
> The app is now translated to Bengali (India) thanks to our community!

**Comment by debodirno** [comment]
I wish to test this.

**Comment by xmatthewx** [comment]
Thanks @debodirno for emailing an offer to help! I shared some instructions here: https://github.com/mozilla/webmaker-core/issues/796

**Comment by gvn** [comment]
I can't generate an APK due to an [un-localized string](https://github.com/mozilla/webmaker-android/commit/cd1674f55bfb32d326aa24a51b0e71595aa33111#diff-01dafb3fd0217441330103cfc8300094R14).

Options:
1. Localize it
2. Put English in the non-english locale XML files (Ali, is this bad?)
3. Refactor Android to fall back to English for missing localized strings

My preference is 3, but I'm not sure how to do it.

CC: @alicoding

**Comment by alicoding** [comment]
@gvn I think we can do 2 first then people will do 1 and in the meanwhile we can take our time to do 3.

**Comment by xmatthewx** [comment]
:+1: to @alicoding's suggestion. 

@alanmoo - are we using the phrase "User Projects" or is that replaced with the username? Maybe we can just remove this? 

Option 2 is definitely ok for a Beta release while we translate.

**Comment by alanmoo** [comment]
It appears temporarily while the page is loading, I suppose we could just remove it and have nothing show while the view is loading...

**Comment by xmatthewx** [comment]
Is it possible we have an error because the string isn't in [en-US.yaml](https://github.com/mozilla/webmaker-core/blob/master/src/locales/en-US.yaml)? Maybe the fallback would otherwise work ok?

**Comment by gvn** [comment]
No, this is an Android string, not a core string. Core will fallback to English already.

Opened a PR for Android strings: https://github.com/mozilla/webmaker-android/pull/2450

**Comment by gvn** [comment]
Ok, beta APKs for 1.5.0 are up. Allow a few hours to propagate. :+1:

**Comment by xmatthewx** [comment]
hurrah!! exciting stuff. thanks everyone for the push to wrap this up.

**Comment by xmatthewx** [comment]
@gvn - any thoughts on what we'll include in 1.5.1? 
- Can we add improved scrolling in editor? I think that includes NaN fix for image editor 
- Two fixes for set destination mask? (Yours and @vazquez's)
  Any other blockers still open on this?

**Comment by gvn** [comment]
Yep all that should be in there. I'm going to start building APKs now...

**Comment by gvn** [comment]
Ok, `1.5.1` is now uploaded to the beta channel. Should be available in a couple hours!

**Comment by xmatthewx** [comment]
Fab. Everything is looking great. Looks like we can finish testing tomorrow and push to production on Monday as planned.

**Comment by xmatthewx** [comment]
@gvn - looking at the checklist above...
- I'll let you check for crash reports on Monday as you phase to production. We're good to go unless something new pops up. 
- Will analytics show us views of author lists? Or does that require a follow up ticket for next heartbeat?

**Comment by alanmoo** [comment]
I wasn't aware analytics of specific views existed, so I didn't do anything special when I created the new view, AFAIK. So unless it hooks in globally, it's doubtful it'll be there.

**Comment by xmatthewx** [comment]
No big deal. I'm going to file a new bug alerting Adam to changes coming down the pipe.

**Comment by gvn** [comment]
So far so good...

<img width="868" alt="screenshot 2015-11-20 12 41 56" src="https://cloud.githubusercontent.com/assets/206379/11311347/29908f8e-8f84-11e5-8b6c-4b37eb3d01bd.png">

**Comment by gvn** [comment]
@xmatthewx I can't fit all the notes from the 1.4 release in our new release notes due to character count. Should I just go with the 1.5 release notes?

**Comment by xmatthewx** [comment]
I tried to edit and squash them in there too, but no dice. Notes for just 1.5 is fine. Thanks for updating that.

**Comment by gvn** [comment]
1.5.1 has been promoted to production. :tada:

**Comment by gvn** [comment]
I also pushed `webmaker-browser` to prod. 

It required a patch to core, so it's actually at `1.5.2` now.

**Comment by xmatthewx** [comment]
Excellent. Update to webmaker-browser resolved some lingering rendering issues!
