### ISSUE TITLE
Please, post the package to f-droid repo as well

### ISSUE THREAD

**Issue by mcepl** [mozilla/webmaker-core#767]
Not everybody uses Google Ad infested Play Store. I for one would a way more prefer the package on https://f-droid.org/

Thank you

**Comment by ryanwarsaw** [comment]
Almost all Android devices sold on the market come with Google apps installed, (playstore, etc). If you don't want to search for the package, there is a direct link you can use as well. To add onto this, I've literally never seen an Ad in the Google Play store ever.

To add onto this, I'm not sure how powerful f-droid is, we serve different APK files to use on x86 and ARM devices, I'm not sure if it allows for that capability. And at the end of the day, anyone without Google apps installed is most likely a technical person could just compile the package.

**Comment by mcepl** [comment]
OK, I guess I just don't need your app that much.
