### ISSUE TITLE
 [3.11] QA Feedback - Android Beta App - Button Element

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla/webmaker-core#768]
Issue template from #401 
Nexus 5 - Android 6.0
- [x] open one of your existing projects or create a new one
- [x] make sure the project has at least two pages, add one if necessary
- [x] edit one the pages
- [x] tap the plus icon at the bottom of the page add a Button by tapping the third icon
  - [x] a blue button appears in the center of the page
  - [x] the button label is "Button link"
  - [x] the button is selected, it has a blue dashed border
  - [x] there is a white "Set Destination" button below the button
  - [x] there is a garbage icon, a plus icon, and a paintbrush icon at the bottom of the page

**Moving the Button**
- [x] drag the button around the page, it moves with your finger
  - [x] the "Set Destination" button moves with it
- [x] pinch the button to make it larger and smaller
- [x] rotate the button using a two-finger gesture, in both directions

**Button Options**
- [x] tap the pencil icon to enter the Options view
- [x] change each of the available settings, the preview at the top of the page updates as you do so
  - [x] Corner Radius
  - [x] Font
  - [x] Background color
  - [ ] Text color
- [x] once you've made changes, tap the back arrow in the header to return to the Page view
- [x] the changes you made are reflected in the Page view
- [x] tap the pencil icon to enter the Options view again
  - [x] the changes you made to the button element are reflected in the UI
- [x] tap the Edit Label button to enter text editing mode
- [x] you can edit the text by using the keyboard
- [x] tap the Done button to finish editing text
- [x] edit the label again and tap the green arrow on the keyboard to finish editing
- [x] tap the back arrow to return to the Page view
- [x] the button has the label that you specified

**Setting the Button Destination**
- [x] tap the "Set Destination" button, the Set Destination view opens
- [x] the view is centered on the page with the button
  - [x] the page is darker
- [x] tap another page
  - [x] it has a blue flag icon on it and is darker
  - [x] a "Set Destination" button appears at the bottom of the view. Tap it.
- [ ] you now see the link editor with "Edit Label", Font, etc.
- [ ] tap "Set Destination" again to enter the Set Destination view
- [x] tap another page to select the destination
- [x] tap the green "Set Destination" button at the bottom of the page
- [x] the view returns to the Edit view, tap the back arrow to return the page

**Follow the Link**
- [x] in the page editor, the button now has a "follow link" button below it
- [x] tap "follow link" button
- [x] page editor should transition to the destination page
- [x] exit the page editor by tapping the back arrow
- [x] tap "more actions" menu. to "Play" to view the project
- [x] tap to open the page with the button link
- [x] tap the button
  - [x] view should pan to center on your destination page

**Deleting the Button**
- [x] return the page editor
- [x] tap the Garbage icon, the link element is deleted

**Comment by ioana-chiorean** [comment]
Feedback:
- " Text color" - I can not change it myself but it does change depending on the background color. 
- After setting a destination you are in page view not button edition view: " you now see the link editor with "Edit Label", Font, etc.
- after u set a destination - returning to button editing will display "Change Link Destination "not "Set Destination"  - template not updated or bug?

Improvements for the template:  https://github.com/mozilla/webmaker-core/issues/401#issuecomment-153737874

review @xmatthewx ?

**Comment by xmatthewx** [comment]
- text color will land in the next release
- updating the QA template with feedback
