### ISSUE TITLE
Create 'Project List' component

### ISSUE THREAD

**Issue by alanmoo** [mozilla/webmaker-core#769]
After some discussion in #766, we've realized that project lists should be their own component. I wanted to start this issue to figure out what features they need. So far I'm thinking

Properties:
- Data source (I'm leaning towards individual keys, so we can pass nothing (discover behavior), an author, hashtag, and maybe other combinations of search keys as necessary.)
- Shuffle (Boolean)
- Infinite Scroll (default to true)
- Show Author name (which might expand to other data points later on)

Edit to add:
- Show actions

Thoughts @gvn @xmatthewx @vazquez?

**Comment by xmatthewx** [comment]
Excellent thinking. Will this be used by the Make view as well? When the project is yours, the card includes the "more actions" kebab and may include an indication as to whether it's public/private (not currently implemented). We don't currently have "more actions" in Discover (when the project isn't yours), but might want that later for remix and share. I don't want to make your task more complicated—no need to tackle this now—just lending thoughts on the range of factors.

**Comment by alanmoo** [comment]
That's already a prop on the card component, so it'd just have to be passed down similarly to how it is already, so good call.

**Comment by gvn** [comment]
Whatever we come up with let's just be sure to get it in the style guide!

@vazquez Can you confirm that that appearance of cards under hashtag lists will be the same (or very similar) as under Discover and Make?

**Comment by xmatthewx** [comment]
Yes. Cards under hashtag lists will be the same as Discover. Both will change a bit to include new descriptions, but they will be consistent.

**Comment by gvn** [comment]
:+1:

**Comment by alanmoo** [comment]
Closed by https://github.com/mozilla/webmaker-core/commit/f33f8a870ac6486beca185cb30233dab2665912a
