### ISSUE TITLE
UI for page background color

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-core#782]
Let's consider an approach that utilizes an element-editor-like view. Unique UI for this one feature is too heavy of a lift. 

This view could include our typical color picker and maybe later an option to set a background image. 

see: #63

**Comment by xmatthewx** [comment]
This could be accessed via an icon on either the page editor or the project editor (if we still have a selected page state). Wherever it fits more super chilly.

**Comment by vazquez** [comment]
### Design Annotation

![change background page colour](https://cloud.githubusercontent.com/assets/1119821/11149476/f7d1f2dc-89f0-11e5-8346-3f798c2dd94a.png)

**Comment by xmatthewx** [comment]
Implementation notes:
- [ ] shorten the header to just Page Background
- [ ] apply most recently used color on newly created pages (if we need to, let's add a column in DB for a project's recent/default element and page styles)

**Comment by alanmoo** [comment]
@vazquez Is that paint fill icon already in the repo somewhere?

**Comment by xmatthewx** [comment]
I don't love this paint bucket. It's a bit hard to read.

**Comment by alanmoo** [comment]
As I'm building this I'm simply using the paint brush as a placeholder. Do we keep that for consistency?

**Comment by vazquez** [comment]
The paint brush can be a good alternative since we removed the paint brush in all other views in favour of the pencil.

**Comment by vazquez** [comment]
@xmatthewx We can also try

![screenshot 2015-12-01 11 15 24](https://cloud.githubusercontent.com/assets/1119821/11506314/ea495440-981c-11e5-900c-2652bb1bcae7.png)  

or  

![screenshot 2015-12-01 11 15 43](https://cloud.githubusercontent.com/assets/1119821/11506315/ea51853e-981c-11e5-890b-343dc64cb983.png)

**Comment by xmatthewx** [comment]
I like the palette. 

If we use the paintbrush, let's adjust it so it looks less like the pencil. Current, both point down from top-right to bottom-left. They don't have enough contrast. Brush could be oriented like the wand above, with brush upward.

**Comment by vazquez** [comment]
I think I like the palette better.

![screenshot 2015-12-01 15 03 03](https://cloud.githubusercontent.com/assets/1119821/11512576/c25af6b2-983c-11e5-9438-252a51865e25.png)  

![screenshot 2015-12-01 15 03 35](https://cloud.githubusercontent.com/assets/1119821/11512575/c2587680-983c-11e5-98dd-1aae77a4a5f8.png)

Palette icon (with svgo optimization): https://dl.dropboxusercontent.com/u/43783651/Mozilla/Android/palette-icon.svg

**Comment by xmatthewx** [comment]
R+ on the palette

**Comment by alanmoo** [comment]
@vazquez Default color options? Normal set with transparent replaced by that dark one in the comps? If so, what is that one color?

**Comment by xmatthewx** [comment]
Dark one is probably the same as text color on text element. 

Wondering: should we swap the blue for the yellow. If page background often match the app header, things might get a bit weird.

**Comment by alanmoo** [comment]
Yeah I was wondering if we should have a different palette altogether. I'm not sure how often the default colors get used for elements vs tinkered ones, but new colors here that complement the default element ones could result in more good looking projects.

**Comment by vazquez** [comment]
Let's have these colours:

![screenshot 2015-12-02 14 48 35](https://cloud.githubusercontent.com/assets/1119821/11542323/d72c11b6-9904-11e5-988d-101fbd02706c.png)

We have a blackish colour, a greyish colour, and some colours that are complementary with a blue header.

New Colour Values:
- Black: `#484B50`
- Grey: `#6D7886`
- Green: @green LESS variable
- Orange: @orange LESS variable
- Purple: @purple LESS variable

**Comment by alanmoo** [comment]
Transparent vs white? Thoughts?

**Comment by vazquez** [comment]
I don't have a strong preference. @xmatthewx what do you think? How should we communicate "white" in this case?

**Comment by xmatthewx** [comment]
Good point. White is probably better. (I bet most people read that as none, not transparent. But still, white requires less thinking.)

**Comment by alanmoo** [comment]
Turns out it's not actually white, but an off-white `#f2f6fc`. After a quick in person discussion (!), @xmatthewx and I decided we should use that instead of `#FFF` in the palette.
