### ISSUE TITLE
Make new links on usernames obvious

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-core#783]
When we add links from username to author project list, odds are good that nobody will notice. In current release, usernames are already blue. We can call it out in release notes and assume that new users will tap to try. For existing users, we could underline the links or add a generic user icon sometimes included in @vazquez's mockups. Thoughts?

cc @alanmoo

**Comment by alanmoo** [comment]
The plan was to have them blue and underlined...not sure what happened, I'll check on it.

**Comment by xmatthewx** [comment]
@alanmoo - I don't think the design included underline. It's not a common practice in apps. This is an oversight on our end when we first launched Discover without links ... not an error of yours. Let's see what @vazquez has to say.

**Comment by alanmoo** [comment]
Ok. I thought @vazquez and I covered this in an issue comment, though I can't find it.

**Comment by vazquez** [comment]
Whoops, wrong GH username heh :P, I'm @vazquez.

Matthew brings up a good point. I think the best way to proceed would be to add an avatar. By doing this, we give enough visual difference to the users to warrant their curiosity in tapping the author link.

![screenshot 2015-11-12 15 57 57](https://cloud.githubusercontent.com/assets/1119821/11130984/2ced214e-8956-11e5-8342-41fc52adbdc2.png)

The avatar SVG can be found here: https://dl.dropboxusercontent.com/u/43783651/Mozilla/Android/avatar-icon.svg

What do you think @alanmoo?

**Comment by alanmoo** [comment]
Fair point. I assume actually uploading a photo isn't part of this?

**Comment by vazquez** [comment]
That's correct, just the static image.

**Comment by xmatthewx** [comment]
:+1:  Icon would just be a static SVG. I think this also offers a nice tap target. Someday, we could add the feature to add a photo avatar, but that day is not today ;)

**Comment by alanmoo** [comment]
How does the avatar affect the tap targets? Seems like avatar and username should bring you to the user's projects, but project name should bring you to the project itself (as well as the existing behavior of the preview image bringing you to the project).

**Comment by vazquez** [comment]
How about this:
- Avatar and username will bring you to the user's projects.
- The Thumbnail image will bring you to the project.
- The Project title itself is not tappable.

**Comment by xmatthewx** [comment]
:+1:

**Comment by alanmoo** [comment]
Cool. I'm planning on making the image and username separate links that go to the same place though, just for clean markup.

**Comment by xmatthewx** [comment]
:+1: :+1:

**Comment by vazquez** [comment]
Awesome :cow: :star:

**Comment by alanmoo** [comment]
Closed by https://github.com/mozilla/webmaker-core/commit/f33f8a870ac6486beca185cb30233dab2665912a
