### ISSUE TITLE
Add an icon to buttons that link to URL

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-core#791]
Some buttons will pan to another page, while others leave the app and open the browser. Wondering if we should add an icon or other indicator to buttons that exit the app.

**Comment by vazquez** [comment]
In Android-land, there are two icons within its visual language that indicate to the user they are leaving the app, or opening something within the app:

<img width="68" alt="screenshot 2015-11-13 16 06 19" src="https://cloud.githubusercontent.com/assets/1119821/11157674/c357bed0-8a20-11e5-880e-75e00912d83c.png">  

and  

<img width="71" alt="screenshot 2015-11-13 16 08 40" src="https://cloud.githubusercontent.com/assets/1119821/11157685/d8297f92-8a20-11e5-8d95-c541d5fea6d8.png">

---

ps. We would remove the button icon if we add an icon to buttons that link to a URL.

**Comment by xmatthewx** [comment]
:+1: just a matter of seeing how this balances with centered text. maybe matches colors of button label but with half opacity? make a pile of options.

**Comment by vazquez** [comment]
What are you thinking @xmatthewx? I like the third option from the top.

<img width="304" alt="screenshot 2015-11-16 14 10 08" src="https://cloud.githubusercontent.com/assets/1119821/11191899/f7b9c98c-8c6b-11e5-84f7-ca400277c704.png">

**Comment by vazquez** [comment]
For context:

![play page view](https://cloud.githubusercontent.com/assets/1119821/11191917/24009bce-8c6c-11e5-9061-7a1e6e004a8e.png)

**Comment by xmatthewx** [comment]
Yep. Icon within the button looks good. Wondering if some opacity would be nice. Your call.

**Comment by vazquez** [comment]
Yes, yes I like that.

**Comment by vazquez** [comment]
![play page view](https://cloud.githubusercontent.com/assets/1119821/11192697/84c4c832-8c70-11e5-9a0d-c0ba55679b6f.png)

**Comment by vazquez** [comment]
What do you think about this icon for the Link element?

<img width="239" alt="screenshot 2015-11-16 14 45 37" src="https://cloud.githubusercontent.com/assets/1119821/11192740/c2610034-8c70-11e5-852b-9cd68ef5578d.png">

**Comment by xmatthewx** [comment]
:+1: prep some annotation and then assign to @gvn

**Comment by vazquez** [comment]
## Design Annotation

![url buttons annotations](https://cloud.githubusercontent.com/assets/1119821/11194977/4e266a8a-8c7d-11e5-94a6-4164cd560b5a.png)

**Comment by vazquez** [comment]
Tracking implementation in #797
