### ISSUE TITLE
Build project descriptions

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-core#794]
First step toward Discover with hashtags is to build out project descriptions. 
- [ ] add description field to settings view
- [ ] display description on project card

@vazquez - let's add annotated comps for just this chunk of work

**Comment by gvn** [comment]
@vazquez you can assign back to me when this is ready to build...

**Comment by xmatthewx** [comment]
@vazquez test a max length. 100 or 140 characters? See how that would look in Discover.

**Comment by vazquez** [comment]
## Design Annotation

![project description annotation](https://cloud.githubusercontent.com/assets/1119821/11217691/a1fcb234-8d1f-11e5-9a94-66f3b621152e.png)

**Comment by xmatthewx** [comment]
:leopard:

**Comment by xmatthewx** [comment]
Heck yes
