### ISSUE TITLE
Build tag list view

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-core#795]
Build a Discover list view filtered by hashtags

@vazquez - let's add a annotated comp here with just the list view.

**Comment by vazquez** [comment]
## Design Annotation

![filtered hashtags annotation](https://cloud.githubusercontent.com/assets/1119821/11216375/d6761a0c-8d18-11e5-8e15-6d9a2e3d39ec.png)

**Comment by xmatthewx** [comment]
@gvn do you want to take this? Or @alanmoo since this continues your work on the project card lists?

**Comment by gvn** [comment]
I can take it since I'm already working on the description stuff...

**Comment by alanmoo** [comment]
The stuff I did should be pretty self explanatory for you to use, @gvn
