### ISSUE TITLE
Implement icon to buttons that link to URL

### ISSUE THREAD

**Issue by vazquez** [mozilla/webmaker-core#797]
## Design Annotation

![url buttons annotations](https://cloud.githubusercontent.com/assets/1119821/11195004/72882b8e-8c7d-11e5-9eaf-63c50d37ce40.png)

**Comment by gvn** [comment]
@vazquez Do you have an SVG for the icon? We're not including ionicons in our build...

**Comment by xmatthewx** [comment]
That's the icon currently used for add link element (soon to be changed for chain link icon). This should match color of link's label. Doable?

**Comment by vazquez** [comment]
Err... I merged in the new icon already, and removed the old one. @gvn I
will have something for you tomorrow first thing.

On Monday, November 23, 2015, matthew w notifications@github.com wrote:

> That's the icon currently used for add link element (soon to be changed
> for chain link icon). This should match color of link's label. Doable?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mozilla/webmaker-core/issues/797#issuecomment-159115703
> .

## 

Ricardo Vazquez
UI Designer, Webmaker
Mozilla Foundation
@iamrvazquez http://twitter.com/iamrvazquez
IRC: ricardo

**Comment by vazquez** [comment]
Here it is: https://dl.dropboxusercontent.com/u/43783651/external-url.svg
