### ISSUE TITLE
Webmaker 1.5 Android Account Testing

### ISSUE THREAD

**Issue by debodirno** [mozilla/webmaker-core#803]
**Sign up**
- [x] open the app (or log out from the 'MAKE' tab, if already signed in)
- [x] make sure you are on the screen that says the equivalent of "Join Webmaker" on the button at the bottom
- [x] tap the "Terms" and "Privacy Policy" links at the very bottom
- [x] enter an invalid username by adding a @ in the Username field, check the error message you see
- [x] change to a valid username
- [x] start typing an email address, check the message you see
- [x] start typing a password, check the message you see
- [x] press 'Join Webmaker'

**Sign in**
- [x] open the app (or log out from the 'MAKE' tab, if already signed in)
- [x] make sure you are on the screen that says the equivalent of "Sign in" on the button at the bottom
- [x] tap the "Reset Password" link
- [x] enter an invalid username and password, press Sign In
- [x] check the error message you see
- [x] enter a valid username and password, press sign in

**Comment by debodirno** [comment]
Everything working fine. Just a proposal:

Add this message to the Sign Up: 
- [ ] enter an already taken username and check the error message you see

**Comment by xmatthewx** [comment]
Great. And thanks for the suggestion... I added it to the list for future tests.
