### ISSUE TITLE
Webmaker 1.5 Android Viewing Project

### ISSUE THREAD

**Issue by debodirno** [mozilla/webmaker-core#804]
- [x] Open the app and tap the Discover tab, which opens the Discover view

**Discover View**
- [x] In the Discover view you see a list of projects. Each projects includes...
  - [x] a title
  - [x] a preview image
  - [x] an author (indicated in blue)
- [x] scroll up and down to view additional projects
- [x] tap on any project in the Discover view, it will open

**Project Play Mode**
- [x] when the project opens, the header title is "Play"
- [x] you see a grid of pages
  - [x] pinch to zoom in and out
  - [x] drag to pan the view
- [x] tap a page to enter the Page view

**Page View**
- [x] In the Page view, you see the page you tapped previously, but zoomed in
- [x] there are arrows on the edge of the page that point to any adjacent pages
- [x] tapping an arrow moves the view to the adjacent page in that direction
- [ ] ~~swiping the page in the direction of any of the arrows also moves the view to the adjacent page~~ (not availabe)
  - [ ] ~~the view animates to the adjacent page smoothly~~ (not availabe)
- [ ] ~~swipe in a direction where there isn't an adjacent page, the view will not move~~ (not availabe)
- [x] tap the back button in the header to zoom back out to the Project view

**Project View**
- [x] the Project View is centered on the page you were just viewing
- [x] tap the menu (⋮) to reveal the share option
- [x] tap Share option to see a list of applications
- [x] tap anywhere to cancel
- [x] tap the back to exit the project and return to Discover mode

**Comment by debodirno** [comment]
Everything working just fine, however, I feel you should write:

tap the zoom out(minus '-' button) in the right top to zoom back out to the Project view.

Because tapping the back button(←) leads to the Discover view rather than the Project view.

**Comment by xmatthewx** [comment]
Perfect. Thanks for the correction ... I added it to the wiki page. The back arrow is used when you are in the project editor, but the project viewer as you noticed.
