### ISSUE TITLE
Infinite scroll seems to be finite

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-core#805]
Sometimes I get a few additional projects. Sometimes I get many. I never seem to get all of the featured projects.

**Comment by alanmoo** [comment]
What view is this in, discover?

**Comment by xmatthewx** [comment]
Yes. There are known featured projects I can't always view in Discover, even when I hit the end of infinity.

**Comment by xmatthewx** [comment]
cc @gvn

**Comment by gvn** [comment]
Hmm. Somewhat related: should we stop randomizing the load order for Discover now that we have infinite scroll? Seems a tad weird to have it still...

**Comment by xmatthewx** [comment]
I think yes. Was my mediocre idea. Filed here: https://github.com/mozilla/webmaker-core/issues/901

**Comment by gvn** [comment]
I think this is resolved now...
