### ISSUE TITLE
Images Options show NaN and undefinedpx values

### ISSUE THREAD

**Issue by vazquez** [mozilla/webmaker-core#813]
### STR:
- In the Editor, tap the plus icon at the bottom of the page add an image element to the page.
- Tap the pencil icon to enter the Options view

When entering the Image Options view, this is what you see:
### Issues Found
1. View is broken, you can scroll left and right
2. Opacity value shows as `NaN%`
3. Border width shows as `undefinedpx`

![screenshot_20151118-134547](https://cloud.githubusercontent.com/assets/1119821/11250578/119acf28-8dfb-11e5-851b-2095fcc8d349.png)

**Comment by xmatthewx** [comment]
Uh oh. cc @gvn @alanmoo

**Comment by alanmoo** [comment]
I noticed this when working on #799, so if that gets merged in it should fix this. For some reason, the value attribute was missing on those sliders.

https://github.com/mozilla/webmaker-core/pull/799/files#diff-e858a41c1876cbd4433de2314fa2172dR55

**Comment by xmatthewx** [comment]
So we'll need to make sure that we add #799 to Beta and test, before we go to production.

**Comment by xmatthewx** [comment]
resolved

**Comment by ioana-chiorean** [comment]
:tada: :dancer:
