### ISSUE TITLE
Webmaker 1.5 - Error loading projects in Make

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla/webmaker-core#816]
I am getting this in Make tab. Reload the tab, error appears. 

<img src="https://cloud.githubusercontent.com/assets/1391451/11255106/2b312ee4-8e4d-11e5-89ce-8787e222f4c5.png" width="300" height="550" />

**Comment by ioana-chiorean** [comment]
So , with my regular old account it works fine. 

<img src="https://cloud.githubusercontent.com/assets/1391451/11255329/51babffc-8e4e-11e5-88b8-7ad98f57f362.jpg" width="300" height="550" />

**Comment by xmatthewx** [comment]
@ioana-chiorean - the account you made on 1.4 Beta won't work here. That Beta was incorrectly linked to a separate database used during development. This Beta correctly links to the real live database.

**Comment by ioana-chiorean** [comment]
Makes sense. Thanks.
