### ISSUE TITLE
Wrong display of text - overlaps button

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla/webmaker-core#818]
Play view:
<img src="https://cloud.githubusercontent.com/assets/1391451/11256979/b8a29df8-8e57-11e5-88b6-03adf1192e91.jpg" width="300" height="550" />

Preview:
<img src="https://cloud.githubusercontent.com/assets/1391451/11256976/b89bf7f0-8e57-11e5-8b0a-de5a02daec96.jpg" width="300" height="550" />

Page view:
<img src="https://cloud.githubusercontent.com/assets/1391451/11256977/b89f1a70-8e57-11e5-8ec9-0aa92c5501a7.jpg" width="300" height="550" />

**Comment by alanmoo** [comment]
Should be solved by #735

**Comment by xmatthewx** [comment]
Seems resolved in 1.5.1. Can you confirm @ioana-chiorean?

**Comment by ioana-chiorean** [comment]
Looks good indeed! 
<img src="https://cloud.githubusercontent.com/assets/1391451/11295887/46bd0770-8f77-11e5-8e5c-b962d0fb211b.jpg" width="300"  height="550" />
