### ISSUE TITLE
Buttons can't be set to top/bottom of page nor margins

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla/webmaker-core#821]
Not sure if intended, did not see any specs..
1. I am trying to move the button above the picture. 
2. I am able only till a point. 
3. I can move the picture thought 
4. Try to set the buttom at the bottom of the page

<img src="https://cloud.githubusercontent.com/assets/1391451/11258217/12179142-8e60-11e5-8f67-647f447f5451.png" width="300" height="550" />

<img src="https://cloud.githubusercontent.com/assets/1391451/11258228/1f4c36ec-8e60-11e5-93b0-b607421d11d8.png" width="300" height="550" />

**Comment by ioana-chiorean** [comment]
I am able to set them now anywhere on the page with 1.5.1:

<img src="https://cloud.githubusercontent.com/assets/1391451/11296720/86d6a406-8f7c-11e5-9b94-5011f1d523cf.jpg" width="300" height="550" />

**Comment by xmatthewx** [comment]
:fireworks:
