### ISSUE TITLE
Set destination "mask" appears in project editor

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-core#828]
cc @vazquez @gvn @alanmoo 
## STR
1. Create or Edit a Project
2. Add a Link Element
3. Tap on "Set Destination"
4. Once you're in the Set Destination screen, tap the back arrow on the header
5. Tap the back arrow again on the header
6. You are now in the Project. The selected page has a gray mask and is disabled.
7. Tap on "More Actions" at the top right hand side
8. Press "Play"
9. The page that appeared with a gray mask in the editor is now displayed very faintly on Play view.

The problem is resolved one you go back into the Editor and set a destination to the link.

**Comment by xmatthewx** [comment]
Might push back to 1.6

**Comment by xmatthewx** [comment]
When I leave a project, open another, edit it, and return to the original one ... the mask remains. Pretty important to fix this. If I choose a select a different page, I can no longer edit that button to set a destination. There's no way out of this.

**Comment by alanmoo** [comment]
This doesn't always happen up when I follow these STR, but I'm going to review #830 anyway.
