### ISSUE TITLE
UI Polish - Discover

### ISSUE THREAD

**Issue by vazquez** [mozilla/webmaker-core#832]
- Discover/Make Selected Header underline indicator should be dark blue, not white.

**Comment by vazquez** [comment]
The colour we need is `#315D8A`

![screenshot 2015-12-17 16 17 39](https://cloud.githubusercontent.com/assets/1119821/11882322/b50a19b2-a4d9-11e5-89cb-4e963ef45a44.png)

**Comment by ryanwarsaw** [comment]
PR containing the changes requested has been merged, this can be closed! :snowman:

**Comment by vazquez** [comment]
Thanks so much Ryan :smile:
