### ISSUE TITLE
UI Polish - Set Destination

### ISSUE THREAD

**Issue by vazquez** [mozilla/webmaker-core#837]
User needs some help
- could be arrows on the origin page
- https://www.google.com/search?q=community+butthole+flag&espv=2&biw=1120&bih=951&source=lnms&tbm=isch&sa=X&ved=0CAYQ_AUoAWoVChMI4MiBka-dyQIVxhk-Ch1QigQG 
- could be FTU overlay +1 [requires localization]
- could be help text in element editor next to set destination button [requires localization]

**Comment by xmatthewx** [comment]
Something like this arrow icon could work:

![image](https://cloud.githubusercontent.com/assets/53411/11285255/8c8088ea-8edc-11e5-8635-0089ff2ec3a0.png)

**Comment by vazquez** [comment]
@xmatthewx What about this?

![button pick destination page copy](https://cloud.githubusercontent.com/assets/1119821/11307692/d9977ffc-8f87-11e5-9889-b75f286fa923.png)

**Comment by xmatthewx** [comment]
I read that as a move this page icon. What if it is much larger without the background circle? I think 6-8 arrows will also read more as directional links.

**Comment by xmatthewx** [comment]
Try a bunch a quick rough ideas side-by-side.

**Comment by vazquez** [comment]
![screenshot 2015-11-20 15 18 57](https://cloud.githubusercontent.com/assets/1119821/11310830/0cc6ad78-8f9a-11e5-8dbb-ce07c9491694.png)

**Comment by xmatthewx** [comment]
What do you think? The 3rd reminds me of a first person shooter. I prefer the second over the first, but not a strong preference.

**Comment by vazquez** [comment]
Hahaha right, I see it now. I meant to create an abstract compass.

I also like the 2nd the best.
