### ISSUE TITLE
UI Polish - Loading indicator

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-core#839]
The loading spinner with full screen blue background is a bit overwhelming. Consider white or gray. Consider a smaller modal.

**Comment by alanmoo** [comment]
I'm not entirely sure when this shows up vs the horizontal loader. Are there rules about this? I feel like maybe I saw something about network performance in the code?

**Comment by xmatthewx** [comment]
Good question. Maybe it's used just within projects?

Loosely related to #781
