### ISSUE TITLE
Quality test 1.5.3

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-core#881]
A new release is in Beta on the play store. It includes several enhancements and fixes. 
- when rotating elements, they snap to horizontal if they're near to horizontal to make alignment easier
- links can now point to a page or any web URL
- UI clean up in several sections, including login screen
- select element now required before you can tap to move element in front of others

cc @vazquez @ioana-chiorean @debodirno

**Comment by ioana-chiorean** [comment]
On it.. 🎯🔎🐞

**Comment by vazquez** [comment]
Tests done:

Account Basics - https://github.com/mozilla/webmaker-core/issues/891
Viewing a Project - https://github.com/mozilla/webmaker-core/issues/891
Creating & Deleting Projects - https://github.com/mozilla/webmaker-core/issues/892
Project Editing Basics https://github.com/mozilla/webmaker-core/issues/893
Image Element - https://github.com/mozilla/webmaker-core/issues/894
Button Element - https://github.com/mozilla/webmaker-core/issues/895
Text Element - https://github.com/mozilla/webmaker-core/issues/896

**Comment by vazquez** [comment]
:star: All tests have been done using the following device and OS :star: 

Android OS: Android 6.0
Device: Nexus 5
App Version: Webmaker 1.5.3

**Comment by xmatthewx** [comment]
Super! Thanks for the swiftness.
