### ISSUE TITLE
Linkify tags in description

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-core#904]
Two things to do:
- [x] use same regex to identify tags on server and client
- [x] wrap tags with html links on client

Anything else?

cc @cadecairos

**Comment by xmatthewx** [comment]
see https://github.com/mozilla/api.webmaker.org/pull/184

**Comment by gvn** [comment]
Note: [tag regex](https://github.com/mozilla/api.webmaker.org/pull/184/files#diff-beddffc7ddf1369364eb944549dbed78R173)

**Comment by xmatthewx** [comment]
So... for an FAQ: 

> Tags begin with "#" and will link to a list of other projects with the same tag. They can only contain standard Latin characters A through Z in upper and lowercase. Any hyphens or other characters will disable the tag. 

Correct?

**Comment by xmatthewx** [comment]
Question: Will #NewYears load the same projects as #newyears? 

"No" is fine for a first release of this. Ideally, we'd preserve the user's string as entered, but load a case insensitive list. 

cc @cadecairos
