### ISSUE TITLE
Add featured tags to discover

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-core#905]
Design complete by @vazquez. Let's add a spec that covers this for implementation.

**Comment by vazquez** [comment]
![featured hashtags](https://cloud.githubusercontent.com/assets/1119821/11788910/619154fa-a261-11e5-800b-81246482a67f.png)

**Comment by xmatthewx** [comment]
Nice connection with January's campaign.

**Comment by xmatthewx** [comment]
Implementation: 
- admins can manually specify 1-10 featured tags
- admins can set a date on featured tag
- featured tags would be mixed with projects in Discover view, sorted by date
- featured tag links to list view by tag

**Comment by alanmoo** [comment]
@xmatthewx What's this "set a date" feature? All the API seems to return is an array of strings.

**Comment by xmatthewx** [comment]
I was thinking that projects were sorted by date and that we'd want to mix these intentionally. But, it's not important. You can mix them in free style, after the 1st, 3rd, 5th project or something like that. I don't imagine we'll run more than 3 or 4 at a time.
