### ISSUE TITLE
Text element background tinker color starts with zero opactiy

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-core#906]
If a user taps tinker when no previous background color is selected, it seems like the color picker doesn't work, because opacity is set to zero. It should default to 1. Background color default can be set to 'none' to avoid need for zero opacity.

**Comment by alanmoo** [comment]
But what would the color be when tinker opens up? Since it's RGB, it needs something...

**Comment by alanmoo** [comment]
Do we want some edge case behavior like "if the opacity is 0 and the user adjusts one of the other values, make opacity jump to 1"?

**Comment by xmatthewx** [comment]
Interesting. Your suggestion would help people who paint themselves into an no opacity corner in addition to the scenario I described.  

In my scenario, the 2D picker shows the bottom left selected. We could pick that or any color as a default when someone enters tinker for an attribute not yet defined.

**Comment by alanmoo** [comment]
Right, but would it make sense to just throw a color at a user when they hit tinker mode?

**Comment by xmatthewx** [comment]
I hear ya. Let's try your approach. Seems like a good solution.

**Comment by alanmoo** [comment]
Should this behavior happen in both "spectrum" and "RGB slider" views?

**Comment by xmatthewx** [comment]
Yes, is that a pain? It'd be helpful since the Opacity slider is below the fold and the same UX bug occurs. It's an edge case, but very confusing when it happens.

**Comment by alanmoo** [comment]
That's fine, just helps decide an approach to take
