### ISSUE TITLE
Add padding to text element for background color

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-core#908]
When a text element has a background color, a little padding would improve appearance (particularly on the left/right).

**Comment by alanmoo** [comment]
This can be tricky, I think I had a specific reason for the padding being set this way when I fixed the layout rendering, so we just have to be careful when changing this.

**Comment by xmatthewx** [comment]
What if we used a border of the same color and opacity? Or outline since that isn't counted in box model dimensions? The look is less than ideal currently. cc @vazquez

**Comment by alanmoo** [comment]
With #858 getting fixed, should I still take a look at this? @vazquez what do you think?

**Comment by xmatthewx** [comment]
I think so. #858 provides a hack, but won't help most users. I fully understand that adjusting padding can be a nightmare. Let's see if there's an easy alternative before we punt this to the backlog.  

Something like this might work:

```
background: rgba(111,111,111,0.5);
outline: 10px solid rgba(111,111,111,0.5);
```

**Comment by alanmoo** [comment]
Ah, outline. Good idea, I'll give it a try.
