### ISSUE TITLE
Update logo on Mozilla Assets page

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-core#912]
There's one last logo to update here: https://assets.mozilla.org/portal/assets/#category/16.

**Comment by vazquez** [comment]
I've sent out a request to the Mozilla Assets team. Keeping open till I hear back.

**Comment by vazquez** [comment]
Done.

**Comment by xmatthewx** [comment]
yippee!

**Comment by ioana-chiorean** [comment]
:tada:

**Comment by ioana-chiorean** [comment]
:tada:
PS: @vazquez  what was the process as we need to change it? we need to do this was several others

**Comment by vazquez** [comment]
@ioana-chiorean Email tflanagan@mozilla.com with the assets.

**Comment by xmatthewx** [comment]
@ioana-chiorean - is this about the old Webmaker logo in different places, or another project on that assets site?

**Comment by ioana-chiorean** [comment]
@xmatthewx - was for a different project.. 

but.. in the meanwhile - if u mention it - the logo for Webmaker app on Firefox OS app is till the old one. 
Not sure who is owner for that app. 

Should I add a new issue and screens?
