### ISSUE TITLE
Offer unofficial support cyanogenmod

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-core#936]
create message for @KevZawacki use on help desk and in playstore
cc @ryanw-se

**Comment by xmatthewx** [comment]
@KevZawacki -- We'd like to adjust our message to people who inquire about Cyanogenmod. It is a fork of Android. Some people install it themselves, but it is also the default OS on a few popular devices.

Something like: 

> Webmaker is not officially supported on Cyanogenmod, but it should work as expected (we have limited staff resources). If you find a bug, feel free to email us [help@webmaker.org] or post it to Github [https://github.com/mozilla/webmaker-core/issues/]

Why? Most likely, these users are seeing bugs experienced by standard Android users. Some in this group are likely to be more expert than the usual suspect, and helpful for feedback.

**Comment by KevZawacki** [comment]
@xmatthewx Thanks! I've added to our [Webmaker FAQ](https://docs.google.com/document/d/12OC1yjFyYIBJy9HwbuSc7hlcIT6yBQjOqsnoPWqiTiY/edit), and will begin using when Cyanogenmod questions arise.

**Comment by xmatthewx** [comment]
Closing. Thanks @KevZawacki.
