### ISSUE TITLE
Make tag lists case-insensitve

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-core#948]
In an ideal world, 
- we preserve the user's string as entered for display of description
- but we load a case insensitive list

For example, #newyears #NewYears yield the same inclusive list of projects. 

In a less than idea world,
- we rewrite all tags to be #lowercase

**Comment by cadecairos** [comment]
fixed in mozilla/api.webmaker.org#189

**Comment by xmatthewx** [comment]
belated :clap: :clap: thanks @cadecairos
