### ISSUE TITLE
Quick design review

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-core#955]
It'd be good if @vazquez could complete a quick design review today before we release 1.6 beta. Maybe after tags are merged to develop? Or, for simplicity, @gvn and @alanmoo could post screenshots to this thread. 
- descriptions and tags in discover
- tag list view :heavy_check_mark: 
- page background colors ui :heavy_check_mark: 
- improved tinker layout :heavy_check_mark:

**Comment by vazquez** [comment]
Awesome work @gvn and @alanmoo.

One little bug that I found is on the description field. If you leave a trailing space it converts it to a `&nbsp;`. Other than that, this is solid.

**Comment by vazquez** [comment]
Filed issue for the above #956

**Comment by gvn** [comment]
Got that bug fixed & merged. Anything else sticking out?

**Comment by vazquez** [comment]
No, everything is looking great otherwise :smile:
