### ISSUE TITLE
Gray block being the keyboard in login screen 

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla/webmaker-core#962]
1. Go to log in
2. Type user name and password
3. Dismiss the keyboard

Actual results:
- the block being the keyboard is gray
- u can barely read the text on it

Expected results:
- the block should maintain original blue color and you should be Able to read the text and links on it

<img src="https://cloud.githubusercontent.com/assets/1391451/12041009/4706c8ec-ae76-11e5-9dae-693d098e66cd.jpg" width="300" height="550" />

**Comment by xmatthewx** [comment]
Thanks @ioana-chiorean. I wasn't able to reproduce this problem on Nexus 5 with Android 6. Worked fine. Link to your screenshot is broken. Anyone else see this?

**Comment by alanmoo** [comment]
I think I might have spotted this a few weeks ago....might be something to do with the way the keyboard shrinks the viewport and the height of the blue background being set by `vh` units.

**Comment by ioana-chiorean** [comment]
@xmatthewx i did updated the screenshot now. 
It is not 100% reproducible indeed

**Comment by xmatthewx** [comment]
Ah. So `vh` isn't miracle cure for everything. That's too bad.

**Comment by ioana-chiorean** [comment]
Some more screen just to showcase different looks :cry:  :disappointed: 

<img src="https://cloud.githubusercontent.com/assets/1391451/12100619/ca2661bc-b338-11e5-9a79-f29dcfaea637.jpg" width="300" height="550" />
<img src="https://cloud.githubusercontent.com/assets/1391451/12100620/ca28ee14-b338-11e5-8670-9ec4e866c174.jpg" width="300" height="550" />

**Comment by alanmoo** [comment]
I think we may just need to remove `#login { height: 100vh }`, as the heights of `#login`'s children don't rely on the height of it. Quick testing in the desktop browser seems to show that works.

**Comment by xmatthewx** [comment]
cc @vazquez
