### ISSUE TITLE
Revise tag view header

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-core#975]
Since the tag filter view can't include the Discover/Make tabs, we'll revise the initial design. 
- remove extraneous details: "tags", "hashtag", "X", and the underline
- blue header contains back arrow and no text
- leave large "#chicago" in a medium gray (like avatar or "X")

**Comment by xmatthewx** [comment]
On the Android side, should we set all the strings to an empty string? Or remove the label from the manifest and remove all the string definitions?

**Comment by gvn** [comment]
I'm setting them to an empty string because it seems to need a string even if it's just empty...
