### ISSUE TITLE
Thumbnails are missing page background color

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-core#990]
Example: https://beta.webmaker.org/#/player?user=421495&project=53760

Update webmaker-desktop? cc @alanmoo @gvn

**Comment by alanmoo** [comment]
Agreed, I think this just needs a redeploy/update of webmaker-desktop...

**Comment by gvn** [comment]
I bumped -desktop up to the latest core, so this should be resolved soon I think...

**Comment by xmatthewx** [comment]
Fixed. Working as expected. :smile:
